### ISSUE TITLE
Motion is always being detected for any mode of edit_based_on 

### ISSUE THREAD

**Issue by pascal-mueller** [WyattBlue/auto-editor#102]
Hi,

I wanted to check if the conversion is faster without motion detection so I used e.g. 

`auto-editor "perf models scheduling.mp4" --edit_based_on not_motion --motion_threshold 0`

and other modes that don't include motion but I keep seeing the tool to actualy try and detect motion.

`auto-editor "perf models scheduling.mp4" --edit_based_on not_motion --motion_threshold 0`

**Comment by WyattBlue** [comment]
**This is intention.**
 Auto-Editor needs to calculate where motion occurs so it can cut based on where movement does not happen. 

Use `audio` or `not_audio` if you don't want motion considered at all when making cuts. 

Also, a visualization on the difference between `audio` and `not_motion`

<img src="https://github.com/WyattBlue/auto-editor/raw/master/resources/audio.png?raw=true" width="240">

<img src="https://github.com/WyattBlue/auto-editor/blob/master/resources/not_motion.png?raw=true" width="240">

**Comment by pascal-mueller** [comment]
I just wanted to delete the issue since I did noticed that I did something wrong. Noticed it when I was looking for a bug and didn't find anything. :p
