### ISSUE TITLE
parameters in exportMediaOps section not working

### ISSUE THREAD

**Issue by axeis** [WyattBlue/auto-editor#107]
(Make sure you're using the latest version)
```
auto-editor --version
Auto-Editor version 20w50a
```

**What went wrong**
My Output results in way bigger files so I tried following along #58
But when using any of the options from the exportMediaOps section I get:

```
auto-editor Week1.mp4 --my_ffmpeg --video_codec h264
Traceback (most recent call last):
  File "c:\pathto\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\pathto\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\pathto\Python39\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
    import sys
  File "c:\pathto\python39\lib\site-packages\auto_editor\__main__.py", line 188, in main
    args = ParseOptions(sys.argv[1:], Log(), option_data)
  File "C:\pathto\Python39\Lib\site-packages\auto_editor\vanparse.py", line 91, in __init__
    parent = option['grouping']
KeyError: 'grouping'

```

even if I use the --help on an option `auto-editor --preset --help` it crashes

I get this result for 
```
  --video_bitrate,
  --audio_bitrate
  --sample_rate
  --video_codec
  --preset
  --tune
  --constant_rate_factor
```

**What does the program output when `--debug` is appended to your command/use case**
--debug also results in a crash

**Comment by WyattBlue** [comment]
Thank you for the bug report. Luckily, this issue has already been fixed in the experimental branch and new version with this fix will be published soon. It is still worth it to document these problems in active builds so this issue is not a waste of time.

You can get your command working right now by changing:

```
auto-editor Week1.mp4 --my_ffmpeg --video_codec h264
```

to 

```
auto-editor Week1.mp4 --my_ffmpeg exportMediaOps --video_codec h264
```


What should have happened when you ran your original command was this error:

```
Error! Option --video_codec needs to be in group: exportMediaOps

Example:
    auto-editor exportMediaOps --video_codec uncompressed
```

**Comment by WyattBlue** [comment]
Fixed in 20w50b.
