### ISSUE TITLE
Parallel processes (and variable frame rates)

### ISSUE THREAD

**Issue by p4jo** [WyattBlue/auto-editor#12]
I really appreciate this project and want to suggest two things:
a) Since the program writes its temporary files to .CACHE running two instances in parallel causes both of them to crash (both using the same folder). This could be fixed by creating a folder like .cache{Videoname, Date, random number, etc.} for each instance.

b) My video was a screen capture with variable frame rate and this caused some trouble. Entering a frame rate would lead to keeping the wrong parts of the video as the audio gets mismatched. Converting into a fixed frame rate should do the trick, maybe you could integrate this or at least tell the user to convert to fixed frame rate. 

Best regards,
Johannes

**Comment by WyattBlue** [comment]
Thanks for your feedback

a) While that is definitely possible, it would require reworking more things than you mentioned. I'll put that suggestion in the back burner. If you really need a temporary workaround. You can duplicate the master folder, then run the two versions together and they won't trip over each other.

b) variable frame rates is something I would like to support. Could you send me a video with variable sample rate for testing? I'll see if it is possible to convert it to a regular vid with ffmpeg

**Comment by p4jo** [comment]
Hello WyattBlue,

here are some related files I created:
a) A Powershell script that automatically uses several folders to parallelize tasks. It copies the script and ffmpeg files into a new auto-edit folder if needed. An active folder is marked by an 'in-progress' folder. This makes it easy to avoid the problem mentioned in a) above.
Call by using .\auto-edit videofile.mp4 -fastSpeed (or similar)

b) A video file with variable frame rate for you to test the program with. 

[auto-edit-files-p4jo.zip](https://github.com/WyattBlue/auto-editor/files/4742853/auto-edit-files-p4jo.zip)

Since variable frame rate videos play at 'different' speeds throughout the video, I wonder if one could do the task of auto-editor by just changing the frame_rate(t) 'track' of the video (and editing the video as normally) without dissecting the video into single frames. That's just a thought, I know this is probably very difficult to line up and it works well as is.

Best regards,
Johannes

**Comment by WyattBlue** [comment]
I guess that's a no. The issue is pretty much solved.

**Comment by p4jo** [comment]
Hello WyattBlue,

variable frame rate videos work great now, thanks! 
I created a better version of my auto-edit script which allows for easy parallel use. I also added the feature that it installs auto-editor if it's not present in the -Loc location. So that's more or less an installer now (for Windows at least). 
A user just needs this one file and it automatically clones this repository and guides you to download ffmpeg. It also automatically searches for the ffmpeg*.zip and extracts the needed binaries. This script really makes auto-editor even easier to use, I think you should try it out and maybe add in into the installation description. 
Of course, running .\auto-edit -? helps. 
Oh, before using any shell script, one must allow that first. (Google "allow execution of powershell scripts"). That's a bit inconvenient, I forgot that. 

Sorry for not replying to your request, I was busy and I also thought you would probably not need my video anymore, after some testing on your side (as I understand it, that's true). 

[auto-edit.zip](https://github.com/WyattBlue/auto-editor/files/4776732/auto-edit.zip)

Best regards,
Johannes

**Comment by p4jo** [comment]
Short follow-up: The program is not yet fully tested: Here is a small bugfix (Links to the internet were problematic). I would like to consistently contribute, maybe I will make a repository for this, especially since your new version (in experimental) requires copying more than one python file.
Also, this is very inefficient and uncomfortable for you and me.

[auto-edit.zip](https://github.com/WyattBlue/auto-editor/files/4777346/auto-edit.zip)

**Comment by WyattBlue** [comment]
The best way to contribute, I think, would be to fork this repository, and change the python code for adding the changes you want, and when it's ready, creating a pull request.

I would also highly recommend joining on discord, since that's where most of the bug reports and feature requests come from. I also respond a lot quicker to discord messages than github posts.
https://discord.com/invite/kMHAWJJ

I'd say around 50% of our users use Mac or Linux and those operating systems can't run powershell, and even your method was rewritten in python, (don't do this) it still isn't ideal to copying the entire directory. 

Finding the ffmpeg binaries automatically/adding the program to -Loc is actually a good feature and I would be happy to add them in if you find a way to do it with python. Or add any other feature or change. There's no pressure.

Just be aware that there's a lot of people using this program besides windows users.

 -WyattBlue
