### ISSUE TITLE
Some tested improvements can be add. 

### ISSUE THREAD

**Issue by HaujetZhao** [WyattBlue/auto-editor#125]
Conclusion: 

* Using PyAv to read the video frame one by one and using `subprocess.Popen('ffmpeg .....', stdin=subprocess.PIPE).stdin.write()` can have a huge improved speed, faster than opencv 2x more. It is really fast! 
* Using [soundstretch](http://www.surina.net/soundtouch/soundstretch.html) to alter the audio speed can get a perfect output, way better than audiotsm. 
* Using [spleeter](https://github.com/deezer/spleeter) can isolate the vocal audio, so that while splitting chunks, background music or noise won't effect the splitting. 

I have implemented them in my [JumpCutter-Improved](https://github.com/HaujetZhao/JumpCutter-Improved), so come here to send a friendly message and some useful informations.

**Comment by WyattBlue** [comment]
I played around with *soundstretch* and it does sound a lot better than audiotsm does! I'll find a way to get this program in auto-editor, even though packaging it might be difficult. The homepage download didn't work and building from the source is reallly complex, so I just installed it with homebrew.

I quickly looked at the PyAv homepage/docs and I didn't see **how** to do what you're describing. I'll take a closer look at PyAv later in the day.

Isolating vocals is cool in theory but when well planned users can split their audio in a commentary track and a sound effect/music track, and it's not **as** useful as it seems. It would also almost certainly take more time than just looking a pure volume, yet I can still see it being very useful for a large group of users so I'll include it if I can. The biggest problem is **design**. Putting the different settings in terms that regular users can understand.

I'll try to implement the top two and solve some other issues before looking at spleeter for now.

Thanks for the information!

**Comment by HaujetZhao** [comment]
I tanslated some my code into English, this function may help you understand PyAv process. PyAv really have few docs, these code wasted me so much time. 

This output process will be very fast: 

```python

import av, subprocess

def ffmpeg_and_PyAv_process_video_stream(arameter, tempOutVideo, chunks):
    
    speed = [parameter.silenceSpeed, parameter.soundedSpeed]

    input_ = av.open(parameter.inputFile)
    inputVideoStream = input_.streams.video[0]
    inputVideoStream.thread_type = 'AUTO' # this can make reading input in multiprocess
    
    width = inputVideoStream.width
    height = inputVideoStream.height
    pix_fmt = inputVideoStream.pix_fmt
    averageFramerate = float(inputVideoStream.average_rate)

    process2 = subprocess.Popen(['ffmpeg', '-y',
                                 '-f', 'rawvideo',
                                 '-vcodec', 'rawvideo',
                                 '-pix_fmt', pix_fmt,
                                 '-s', f'{width}*{height}',
                                 '-framerate', f'{averageFramerate}',
                                 '-i', '-',
                                 '-pix_fmt', pix_fmt,
                                 '-vcodec', parameter.codec, # like 'libx264'
                                 '-crf', f'{parameter.crf}', # like '23'
                                 tempOutVideo], stdin=subprocess.PIPE, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    inputEquavalentNumber, outputEquavalentNumber = 0, 0
    chunk = chunks.pop(0)
    for packet in input_.demux(inputVideoStream):
        for frame in packet.decode():
            index += 1
            if len(chunks) > 0 and index >= chunk[1]: 
                chunk = chunks.pop(0)
            inputEquavalentNumber += (1 / speed[chunk[2]])

            while inputEquavalentNumber > outputEquavalentNumber:
                in_bytes = frame.to_ndarray().astype(np.uint8).tobytes()
                process2.stdin.write(
                    in_bytes
                )
                outputEquavalentNumber += 1
    process2.stdin.close()
    process2.wait()
    
``

**Comment by HaujetZhao** [comment]
And I recorded this video to show difference between using and not using spleeter in JumpCut process: 

https://user-images.githubusercontent.com/19181833/103759219-58a7df80-504e-11eb-8a21-5e97b0040ea5.mp4

**Comment by WyattBlue** [comment]
You're right! av is faster than opencv. 

Typically, it takes around a high 4 to a low 5 seconds to render example.mp4 on my machine using the default settings.

The av method takes a high 2 to a low 3 to render. Much better indeed.

One thing I noticed, it always seems to add the first frame, even if you explicitly cut off the first second.

Will look in to this more.

note: I did have to edit your example a bit to make it run so here's [a gist](https://gist.github.com/WyattBlue/b401fcc794ba6daaa9396a28d2d9aa68)

**Comment by HaujetZhao** [comment]
If you are sure your videos are all 8bit, remove the `.astype(np.uint8)` could speed up 20% more again.

**Comment by WyattBlue** [comment]
@HaujetZhao 

I removed `.astype(np.uint8)` and it's working fine so thanks for the tip.

I got soundstretch working but I'm planning to add it in audiotsm2 instead of auto-editor itself.

I'll close this thread since most of the points are addressed. 

For future lurkers, if you need to put bullet points in your feature tab, it's probably a good idea to make each point its own separate issue.
