### ISSUE TITLE
[Question] Is there some way to go faster?

### ISSUE THREAD

**Issue by Ieremies** [WyattBlue/auto-editor#127]
So, I'm on the verge of my finals and I got some lectures to catch up. I downloaded it all, and I found this program to help me trim the lectures (around 30% less boring lectures yeeey). But, since I got a good amount of video to trim (around 6.5G), it will take some time to do it (naturally)

Since I don't need the output to be crystal clear, is there any configuration I can do to do it faster (at an expense of video quality)? I don't really know a lot about video editing...

**Comment by WyattBlue** [comment]
Auto-Editor is fastest by default, so there's not many options to change in the **program itself**

I have 2 suggestions
 * If you don't need the video part, just export as a wave file. `auto-editor lecture.mp4 --export_as_audio`. It's **300x** times faster than making a new video.
 * If you need the video, but don't care about small details, you can **scale** the videos down using a separate program **then** edit with auto-editor. Scaling down makes auto-editor do a lot less work, so it goes much faster.
