### ISSUE TITLE
Can't use short flags

### ISSUE THREAD

**Issue by trueMiskin** [WyattBlue/auto-editor#128]
Version: 21w01a

I can't use short flags like "-vcodec" or "-vb".

```bash
auto-editor video.mp4 -vb 250k

Error! Unknown option: -vb
```

```bash
auto-editor video.mp4 -vcodec copy

Error! Unknown option: -vcodec

    Did you mean:
        --video_codec, --audio_codec
```

But when I use `--video_codec copy` or `--video_codec libx264`, then it print this:

```bash
auto-editor video.mp4 --video_codec copy

Error! Option --video_codec needs to be in group: exportMediaOps

Example:
    auto-editor exportMediaOps --video_codec uncompressed
```

Program is not now usable, because 1,5 h video has ~1GB, but source video has ~200 MB.

I 100% sure, this options works in version 20w41a.

**Comment by WyattBlue** [comment]
Short option flags work, they just need to be in a grouping just like the full command ones.

```
auto-editor video.mp4 exportMediaOps -vb 250k
```

**Comment by trueMiskin** [comment]
Thanks.
