### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by stefankablowski** [WyattBlue/auto-editor#129]
Hello, i love the project but i feel like the exploring the features via the _--help_ command is very tedious. Specifically the commands _--ignore_ and _--cut_out_ are not explained in a way that i understand. Please add some more explanation or maybe a markdown file with all the commands. This would make the software so much more user friendly.

I think a great way would be a config file where all settings with their default values are commented out, and as a user you can easily comment in the desired settings and see the default value very easily. That way you could create different config files for different usages and are very flexible. Maybe it could look something like this:

 _auto-editor myFile.mp4 -load_cfg standard.aecfg_

Hope you find my idea helpful.

**Comment by WyattBlue** [comment]
Some commands do need more things written about them.

The configuration idea intrigues me but I think having a portable config file would make the learning curve too steep. 

It would be better to have a single config file that auto-editor always looks, and it could be changed users.

**Comment by stefankablowski** [comment]
I understand your concern. Maybe you could have the option to load a custom config file like mentioned above. 
On installation there could be a command like: 

_auto-editor --init_config_

which creates a standard config file (which contains command descriptions for beginners) and is used unless you use a command like _--load_custom_config myConfig.cfg--_
This is just a suggestion of course. I appreciate that you like the idea and think having the option to load different configs would make the software very convenient for frequent use.

**Comment by WyattBlue** [comment]
closing since a config file is now available. Feel free for anyone to make attention comments here or in another issue on this topic.
