### ISSUE TITLE
Wrong path Premiere Pro External Drive

### ISSUE THREAD

**Issue by stefankablowski** [WyattBlue/auto-editor#130]
When generating the Premiere Pro Project i always need to relocate Media on first startup.

![grafik](https://user-images.githubusercontent.com/49285379/104332279-4ca99b00-54f0-11eb-9516-e9481bd7b9be.png)

I am Working on Windows 10 with the latest Version of auto-editor. The _\\localhost_ must be removed to be a correct path to my mp4 file.

**Comment by WyattBlue** [comment]
Thanks @stefankablowski , premiere pro was sometimes able to find it depending on the location, but I was able to replicate the same error you got.

The pathurl element is set to 

```xml
<pathurl>file://localhostC:\Users\WyattBlue\Desktop\example.mp4</pathurl>
```

when it should be

```xml
<pathurl>file://localhost/C%3a/Users/WyattBlue/Desktop/example.mp4</pathurl>
```

I'll fix this soon.
