### ISSUE TITLE
Audio removal offset

### ISSUE THREAD

**Issue by stefankablowski** [WyattBlue/auto-editor#131]
Hello, I am experiencing the issue that all cuts made by auto-editor are _slightly too long_ which always "eats up" the beginning of my sentence on a normal voice recording. I experience this when I export into Adobe Premiere and use the Command:

_auto-editor test2.mp4 --export_to_premiere --frame_margin 5 --silent_threshold 0.04 --silent_speed 1.00_

In the waveforms from the picture below it is clearly visible that all silent areas (highlighted) are slightly too long.

![grafik](https://user-images.githubusercontent.com/49285379/104370820-b42b0f00-551f-11eb-88ba-b06d451edba3.png)

Maybe i have been overlooking something. Help is hugely appreciated.

**Comment by WyattBlue** [comment]
**Typically** these weird cuts are caused by the program and premiere pro using different frame rates.

`29.97` is the default fps value auto-editor choices for  Premiere Pro but you can change with framerate auto-editor uses by using this command:

```
auto-editor example.mp4 metadataOps --force_fps_to 24
```

**Comment by stefankablowski** [comment]
This fixed the issue. My footage was 30 FPS and did not match the exported 29 FPS from auto-editor.
Thank you so much, you made my day! Unbelievable that this technique of editing video is not widely used.
