### ISSUE TITLE
Way to change the file download/output location of youtube links

### ISSUE THREAD

**Issue by 03172008** [WyattBlue/auto-editor#133]
I would like to be able to change the file output location of both the altered and unaltered version of the video. For example, if i wanted it to go to C:\Desktop\ instead of C:\Users\me\.

I would use it so that it goes directly to the folder that i want it to go into, instead of me having to move it. in youtube-dl, you can easily do that with a config.txt.

Make sure that it is something that YOU need, not that just seems useful. ✔

(Make sure you're using the latest version) ✔

**Comment by WyattBlue** [comment]
Thanks @03172008 

It is now possible to do that with `--output_dir` in the `urlOps` grouping.

Example:
```
auto-editor "https://url.com/" urlOps --output_dir C:\\Users\me
```
