### ISSUE TITLE
Trojan warning

### ISSUE THREAD

**Issue by KeithDalby** [WyattBlue/auto-editor#134]
I've used this script quite a bit over the last few days, but today for some reason Kaspersky gave me a trojan warning, and blocked the script from running.

**Comment by WyattBlue** [comment]
You can try removing the ffmpeg/ffprobe binaries and install you own else where, but if your anti-virus program detects all python files as security risks, the only thing you could do is whitelist the associated programs or turn off that program while using it. 

Auto-Editor is open source software so everything can be inspected for being run or installed.

The only exception being the ffmpeg and ffprobe blobs, which are the compilation result of ffmpeg's and ffprobe's publicly avaiable code. They can't be easily inspected, but can be replaced by other compiled builds from trusted sources (choco, homebrew, yourself, etc)
