### ISSUE TITLE
Davinci Resolve Export - Windows 10 - .MP4/.MOV does not work

### ISSUE THREAD

**Issue by danfleser** [WyattBlue/auto-editor#135]
Davinci Resolve Export - Windows 10 - .MP4/.MOV does not work

1. Command
$> auto-editor C0005.MP4 --export_to_resolve
2. This is the exported file
https://drive.google.com/file/d/1omBCklVmMiaQDGwKMLs_4YDqCyAimenE/view?usp=sharing
3. Davinci Resolve -> Top menu File -> Import -> Timeline -> C0005.xml(AAD/EDL/XML/FCPXML/DRT/ADL Files option)
<img width="732" alt="Screenshot_3" src="https://user-images.githubusercontent.com/20419925/106954720-db4eb800-673c-11eb-83fc-3ff0b80d9584.png">
4. After I press OK, this shows up
<img width="736" alt="Screenshot_4" src="https://user-images.githubusercontent.com/20419925/106954808-fd483a80-673c-11eb-9daa-2a35af7a25bd.png">
5. I Press OK again, then this shows up
<img width="675" alt="Screenshot_2" src="https://user-images.githubusercontent.com/20419925/106954851-0a652980-673d-11eb-8ae2-ed2fe498f3ad.png">

I see that does not work so I created a new project, added the C0005.MP4 file, made some cuts, then exported the timeline to check what are the differencies, I found that the pathurl differ a litle bit, but the files were loaded from the same directory. This is the timeline.xml file exported from davinci resolve.
https://drive.google.com/file/d/1-_KfnJP4xFx5wcOLdhinRqxtM5ZtLieO/view?usp=sharing

How can I make it work?

**Comment by WyattBlue** [comment]
Thanks for the report @danfleser 

I was able to replicate your error and found the root problem. DaVinci couldn't recognize the format the pathurl was in so it needs to be changed. Example: 

```diff
+   <pathurl>file:///C:/Users/WyattBlue/example.mp4</pathurl>
-   <pathurl>file://localhost/C%3a\Users\WyattBlue\example.mp4</pathurl>
```

Premiere Pro doesn't recognize this new format, but does recognize the old one, so that will have to be considered when making the new patch.

**Comment by danfleser** [comment]
I tried changing the path like you said and it works, but the first video cut it is offline, all the rest cuts are ok and show up in the timeline, I attached an image.
<img width="1082" alt="Screenshot_5" src="https://user-images.githubusercontent.com/20419925/107119863-f6334080-6892-11eb-97e5-471833a96875.png">

Also, do I need to check/uncheck some settings in the import window? There are the defaults I use, I am using Davinci Resolve 17 beta.
<img width="734" alt="Screenshot_6" src="https://user-images.githubusercontent.com/20419925/107119911-398daf00-6893-11eb-9016-7afa11fb5b03.png">


Can I help with any info?

**Comment by WyattBlue** [comment]
I just released the fix for pip today. It should work fine now.

**Comment by danfleser** [comment]
I tested now and no longer works :))
1. I ran the upgrade command in command line: $> pip3 install auto-editor --upgrade
2. This is the import screen settings I used:
<img width="1617" alt="123" src="https://user-images.githubusercontent.com/20419925/107147491-19bfbf00-6957-11eb-866f-a524f8c58b41.png">
3. This is the error window logs
<img width="1617" alt="123" src="https://user-images.githubusercontent.com/20419925/107147500-23e1bd80-6957-11eb-8c11-974cacb1bfff.png">
4. This is the exported .xml file
https://drive.google.com/file/d/1AIh2cS4cqOY5B-6aDetBXvYRGi5_yxZP/view?usp=sharing

Thank you

**Comment by danfleser** [comment]
Hi, I found what is the problem.

This errors occur when path contains empty spaces. So for example, the windows directory "1. VIDEO RESOURCES" which has 2 empty spaces in it will not work until I replace empty spaces with "%20", like this "1.%20VIDEO%20RESOURCES".
I exported a resolve timeline in .xml and saw it uses "%20" instead of empty space, this is how I figured it out.

Also instead of all backslashes "\", there should be slash "/".

After I run the script it exports this pathurl: $>auto-editor 300greenscreenEffects.mp4 --export_to_resolve
<pathurl>file:///D:\youtube\1. VIDEO RESOURCES\300greenscreenEffects.mp4</pathurl>
Changes in the .xml file I needed to do, for Resolve to import it correctly:
<pathurl>file:///D:/youtube/1.%20VIDEO%20RESOURCES/300greenscreenEffects.mp4</pathurl>

**Comment by danfleser** [comment]
@WyattBlue
