### ISSUE TITLE
Option to encode to H.264 or HTML5 compatible format

### ISSUE THREAD

**Issue by filvi** [WyattBlue/auto-editor#144]
Hi thank you for this great tool! I love it, I was wandering if it was possible to convert the video to H.264 or other HTML5 supported format with this. I didn't find anything on the web or in the issue tab. And I was wandering if was actualy an option.

I would like to encode in some HTML5 format in order to display it in a webpage, but when I try to play the "altered" video it gives me only the audio.  Looking at the info with MediaInfo the original video Stream was AVC and  was working but the "altered" video was MPEG-4 Visual.
I don't know if it could help, 

Thank you for your time

**Comment by WyattBlue** [comment]
You can use the `--video_codec` option to change the output file to the h264

Example:
```
auto-editor example.mp4 --video_codec h264
```

And you can verify the output using `info`:

```
auto-editor info example_ALTERED.mp4
```

```
file: example_ALTERED.mp4
 - fps: 30.0
   - mode: VFR:0.000000 (0/526)
 - duration: 17.566667
 - resolution: 1280x720 (16:9)
 - video codec: h264
 - video bitrate: 207k
 - audio tracks: 1
   - Track #0
     - codec: aac
     - samplerate: 48.0 kHz
     - bitrate: 127k
```
