### ISSUE TITLE
Doesn't work with Apple Silicon (M1) due to broken dependencies

### ISSUE THREAD

**Issue by togume** [WyattBlue/auto-editor#147]
Leaving this here in case anyone has the same situation. I was able to to install this without problems on an iMac 2017, i7 using asdf for python 3.9.2. However, on the new MacBook Pro 13" M1 I could not install it because of unmet dependencies which are not yet available on the M1.

I didn't have much time to dig into it, but hopefully this saves people time and we can comment on here as things develop/improve with the M1.

**Comment by bigfangfang** [comment]
please help me to install  on macbook pro 2019 (not M1 chip) command not found: auto-editor
I do have python 3.8 
and run pip3 install auto-editor 
Successfully installed auto-editor-21.8.1
but when I run the command with "auto-editor -h"
but ...
zsh: command not found: auto-editor
ZZZzzz....

**Comment by togume** [comment]
@bigfangfang this is not the right thread to be asking this because it distracts from the original issue and we all lose value from the system. You might want to consider creating a new issue to get more visibility, or posting in a better forum that has people that might point you in the right direction.

**Comment by WyattBlue** [comment]
@togume Can you give us some more details about what exactly went wrong? 

Also you don't need every dependency to work to use auto-editor. See [Installing #dependencies](https://github.com/WyattBlue/auto-editor/blob/master/articles/installing.md#dependencies)

Notes:
Python supports m1 chips natively since 3.9.1
Opencv-python has an open issue about supporting amd64 https://github.com/opencv/opencv-python/issues/429
PyAv might also be causing this issue.

**Comment by RalstonLiu** [comment]
Hello, I also use the M1 chip Macbook. During the installation of auto-editor, the system reported the following error message as follows: ![](https://cdn.jsdelivr.net/gh/RalstonLiu/MdnicePic2/2021-3-22/1616422026166-image.png), my system is macOS Big Sur 11.2.3 (20D91) .

Because I'm not a programmer, I just want to use this tool to speed up my video editing, so the expertise may not be very good, I hope you can help me, by the way, I think this is a great tool.

**Comment by togume** [comment]
@RalstonLiu this is the same issue I encountered with `numpy` dependency (program required to run auto-editor). Hang around here as we try to get this issue solved :).

@WyattBlue sorry! For some reason I missed your notification until now.

The issue I'm seeing is that the `numpy` dependency seems to be a version (1.19.3) that's only found in older version of Python, which are not available in aarch64.

I just tried installing without deps, and here's what I found:
* Installed OK by itself
* Installing `numpy` by itself caused it to go back fishing version by version with an error every time

After some more digging, I realized that `numpy` is not yet available for the M1. Given that it's a hard requirement for auto-editor, it's not going to work with native M1 Python.

Next, I tried installing an older version of Python using the `arch -x86_64` command. However, it didn't work because the compiler/gcc/etc is the M1 version. Therefore, I need to run an x86-64 dev environment on the machine in order to get the full python stack to play nice. The way I've found to do that is to install Homebrew with x86_64 mode so that I can install all deps with Rosetta 2.

That said, I've run out of time to play with this today 😢 .

So, the conclusion for now is that aarch64 doesn't yet have numpy (I didn't check the other deps), so until that comes out, we need to run auto-editor with Homebrew & Python in arch -x86_64 mode (through asdf, pyen, or direct install).

Does that jive with your experience? Hopefully I'm wrong and I missed something really simple 🤞.

**Comment by togume** [comment]
Update: I've been able to slowly crank through dependencies.
* numpy: available for aarch64, installed independently
* audiotsm2: available for aarch64, installed independently
* av: installing natively didn't work because ffpmpeg deps fail --> able to install
  * Installed ffmpeg using Homebrew and then installed the bindings `pip install av --no-binary av`
* opencv-python: 🤕, messy - latest version doesn't support aarch64, but previous ones do - looks like manually compiling previous version that did support it is the way to go... Got stuck here and left a comment over there --> https://github.com/opencv/opencv-python/issues/429#issuecomment-806069540

Feedback welcome!

**Comment by WyattBlue** [comment]
I see aarch64 for both numpy and opencv-python now, so I'm guessing opencv-python can be installed on m1 chips now.

If it still can't, note that unless you're using zooming features or motion detection, you don't need to install opencv-python to use auto-editor.

```
pip3 install auto-editor --no-deps
```

For these reasons plus inactivity, I'm closing this issue. If auto-editor still can't be installed on m1 chips, feel free to make a new issue.
