### ISSUE TITLE
Cannot create final cut pro xml 

### ISSUE THREAD

**Issue by axtonliu** [WyattBlue/auto-editor#150]
Hi there,  While I use --export_to_final_cut_pro, it always told me that : Error! The file test1.xml was not created.  
The FCPX version is 10.5. 
--export_to_premiere or export to an altered video are both fine. The --debug does not give any further message.

**Comment by WyattBlue** [comment]
Thanks for the notice! I was able to reproduce this bug and patch it in master. The fixed version will be released in a few days.
