### ISSUE TITLE
Final Cut Pro xml was not created

### ISSUE THREAD

**Issue by dunbin** [WyattBlue/auto-editor#151]
Hi! Thanx for creating such wonderful tool, it helps me save a lot of time. 

But While I use --export_to_final_cut_pro, or -exf , it print 

```
Error! The file /Users/****/Movies/5TH.xml was not created.                  

This is not a normal error.
 This message will only show up if there's something definitely wrong with the program. 
```

I tested on my win PC and Mac , the bug is always the same.

Hope you can help me fix it.
Thanx a lot!

**Comment by WyattBlue** [comment]
Was able to reproduce, see https://github.com/WyattBlue/auto-editor/issues/150.
