### ISSUE TITLE
New feature next

### ISSUE THREAD

**Issue by ShenMengBJ** [WyattBlue/auto-editor#154]
At first, Auto-editor is a great job! And I write a simple GUI to help the unprofessional friends using it.

But I suggest this feature should be existed in the future version.

#The current "Frame_Margin" argument

Adding a silent frame margin before/after a loud part is strange, but it will be better keep a start/end buffer of the loud part, or means could cut less a X(could be defined by an argument) seconds or frames. The voice will be more natural.

Hope Auto-Editor will be better and better! Good luck!

**Comment by WyattBlue** [comment]
I don't agree it will be more natural. Also closing because this issue is ancient.
