### ISSUE TITLE
Exported XML cannot be imported into Final Cut Pro

### ISSUE THREAD

**Issue by axtonliu** [WyattBlue/auto-editor#156]
Hi there,

I just update to the new version, and --export_to_final_cut_pro can work correctly and generate a xml file. But while I am trying to import this file to Final Cut Pro X 10.5, this file is grey and cannot be selected.

So maybe it generates a wrong format FCPXML file. Please help to check it. 

Thanks.

**Comment by makzan** [comment]
Same here. I have a quick check on the source code, the output is `.xml` instead of what FCP wants: `.fcpxml` and the content is not valid FCP XML as well.

**Comment by WyattBlue** [comment]
Fixed in 21w11a. Thank you for your feedback.
