### ISSUE TITLE
Need a simple GUI

### ISSUE THREAD

**Issue by ShenMengBJ** [WyattBlue/auto-editor#157]
Hi Wyatt,

Using auto-editor some days, there is a little of shortcoming for the command line. If set up these options, like as "--silent_threshold", "--min_cut_length", and "--min_clip_length", cannot find out whether the value is suitable, except for the process is finished. It will waste more time.

Hope it will have a simple GUI for observing the brief editing result.

**Comment by WyattBlue** [comment]
I think that's a great idea, and one that i've been working on privately for a while now.

I'm not going to put it on this github page, but I'm going to release it soon. I just need to add a few minor features and squash some bugs.

**Comment by ShenMengBJ** [comment]
> I think that's a great idea, and one that i've been working on privately for a while now.
> 
> I'm not going to put it on this github page, but I'm going to release it soon. I just need to add a few minor features and squash some bugs.

Look forward to wait the releasing, and a simple GUI will help more people to use auto editor.

**Comment by ShenMengBJ** [comment]
> Hi, I'm a junior video editor and programmer. I'm interested in python projects with video. I could help you with a simple interface in Thkinter if you want.

Would you provide to GitHub? Thanks!!!

**Comment by carlosmatthews** [comment]
yes I would provide to GitHub ,but I´am junior programmer i will some help to understend the program y funcion to create the GUI

**Comment by WyattBlue** [comment]
The GUI is out

Auto-Editor is now available as it's own standalone application. It costs a one-time purchase of $30 with free upgrades down the line. It's available on Windows, Mac, and Linux.

To go https://auto-editor.com/app if you're interested.
