### ISSUE TITLE
hola tengo el siguiente problema

### ISSUE THREAD

**Issue by flavio1974-art** [WyattBlue/auto-editor#159]
Coloco en la terminal gnome ubuntu 18.04
$ auto-editor --edit_based_on audio_or_motion '/home/r/1.mkv' 
Error! Unknown short: /home/r/1.mkv  
solo pasa cuando ingreso un comando. 
![Captura de pantalla de 2021-03-22 13-13-02](https://user-images.githubusercontent.com/55705860/112021729-5a8f2400-8b10-11eb-8a03-fe5fe995633f.png)

**Comment by WyattBlue** [comment]
The file must go first, so the correct command would be:

```
auto-editor '/home/r/1.mkv' --edit_based_on audio_or_motion
````
