### ISSUE TITLE
Impossible to install on Mac OS

### ISSUE THREAD

**Issue by ElectFreak** [WyattBlue/auto-editor#163]
(Make sure you're using the latest version)

**What went wrong**
```
I've installed it with manual it it dosen't work;

Paste the terminal output here
```
electfreak@MacBook-Pro-Arsenij ~ % pip3 list | grep auto
auto-editor       21.11.1
electfreak@MacBook-Pro-Arsenij ~ % auto-editor -h
zsh: command not found: auto-editor
electfreak@MacBook-Pro-Arsenij ~ % 

**Does the example video work? (if applicable)**
No

**What does the program output when `--debug` or `--show_ffmpeg_debug` is appended to your command/use case**
```
output here:
No
```

**What's your platform? (if applicable)**
```
Mac OS 11.2.3
output here, run: `auto-editor --debug` if possible.
```
auto-editor --debug 
zsh: command not found: auto-editor

**What's your input? (if applicable)**

```
output here, run: `auto-editor info path/to/video
```

**Comment by WyattBlue** [comment]
Auto-Editor is installed, pip just didn't add it to the PATH. 

Here are the steps to fix it [here](https://github.com/WyattBlue/auto-editor/issues/149#issuecomment-794598285).

**Comment by ElectFreak** [comment]
OK, thank's a lot, but why did this happen?
