### ISSUE TITLE
Concurrent video processing cannot find the sped up video

### ISSUE THREAD

**Issue by UndercoverButter** [WyattBlue/auto-editor#164]
**What went wrong**

I made a Python script which automatically processes all videos in a folder with auto-editor. To achieve this it calls auto-editor via command line with the subprocess library (AFAIK this is equivelant to opening multiple consoles and entering the command into each console concurrently).
When the processes are done creating the new video, almost every process says, that the spedup.mp4 is not used in any stream. Then the same subprocess says that the spedup video cannot be found. These two messages are always in this order.

The exact messages for one thread:
```
Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (C:\Users\[Username]\AppData\Local\Temp\tmpjz65q67r\spedup.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.

C:\Users\[Username]\AppData\Local\Temp\tmpjz65q67r\spedup.mp4: No such file or directory
```

auto-editor --debug:
```
Python Version: 3.9.2 64-bit
Platform: Windows 10
Config File path: C:\Users\Erik\AppData\Roaming\Python\Python39\site-packages\auto_editor\config.txt
FFmpeg path: C:\Users\Erik\AppData\Roaming\Python\Python39\site-packages\auto_editor\win-ffmpeg\bin\ffmpeg.exe
FFmpeg version: 4.3
Auto-Editor version 21w11a
```

**Comment by TimDev9492** [comment]
I get the same error, even when I'm not running the audio_editor concurrently.

**Comment by elvisbegovic** [comment]
Hi there just discover the lib, and cannot make it working on fresh installation

No concurrency but same here.


ENV: 
```
Python Version: 3.9.5 64-bit
Platform: Windows 10
Config File path: C:\Users\eb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\auto_editor\config.txt
FFmpeg path: C:\Users\eb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\auto_editor\win-ffmpeg\bin\ffmpeg.exe
FFmpeg version: 4.3
Auto-Editor version 21w19b
```

Running command on .mp4 got : 

![image](https://user-images.githubusercontent.com/2789203/118543496-9cc19400-b754-11eb-892a-1244c4abf61c.png)

Does someone have workaround to just get it workin?


cc @UndercoverButter

**Comment by WyattBlue** [comment]
@elvisbegovic Try adding these options to your command
 ```
--preset unset --constant_rate_factor unset
```

**Comment by elvisbegovic** [comment]
thx @WyattBlue but `unset` seems invalid for theses options
![image](https://user-images.githubusercontent.com/2789203/118609544-21df9400-b7bb-11eb-9747-0b78de90aa52.png)

**Comment by WyattBlue** [comment]
Hey @elvisbegovic 

I experienced the same problem and fixed it in the latest version. Sorry about that. 

Anyway, settings those options should work now. Let me know if adding them solves the issue.

**Comment by ykchannel1119** [comment]
Hi someone can help me to fix this issue??"Error! Could not find file"
![Capture](https://user-images.githubusercontent.com/87517509/125907005-6bfc7707-96bf-40af-b8e5-f2a06550e1e9.PNG)

**Comment by WyattBlue** [comment]
@UndercoverButter If you still care this issue, the problem is probably Windows since multiple programs can't read the same text file at once. That text file, in this case, is the config file. Removing the config file should fix your issue.

Since this issue is rather old, you upgrade auto-editor to latest, the issue might have been accidentally been fixed even if my theory is not correct.
