### ISSUE TITLE
Export to Shotcut

### ISSUE THREAD

**Issue by igavronski** [WyattBlue/auto-editor#167]
Descript what feature/improvement you would like here.
An option to export the mlt file for the open-source Shotcut video editor.
Descript how you would use it.
I believe the same way the other users do in their own video editors...

Make sure that it is something that YOU need, not that just seems useful.
The user base of Shotcut is quite large, given the simplicity and "freeness" of the software.

(Make sure you're using the latest version)

**Comment by elvisbegovic** [comment]
I discover this lib (auto-editor) because /tagg remove silent part is not available on open source tool : shotcut

It seems current export if only for paid video tool like (final_cut_pro, premiere), it would be geat to support `--export_to_shotcut`

**Comment by elvisbegovic** [comment]
I discover this lib (auto-editor) because /tagg remove silent part is not available on open source tool : shotcut

It seems current export if only for paid video tool like (final_cut_pro, premiere), it would be geat to support `--export_to_shotcut`

cc/ @igavronski

**Comment by WyattBlue** [comment]
I'm working on this now.

**Comment by WyattBlue** [comment]
Done! Released in 21w22a. Use the `--export_to_shotcut` flag.
