### ISSUE TITLE
Global ini file with defaults

### ISSUE THREAD

**Issue by igavronski** [WyattBlue/auto-editor#168]
Descript what feature/improvement you would like here.
I would like to have the option to add a global defaults file (say, in the likes of vimrc or bashrc) where I could store my personal preferences for all videos.
Descript how you would use it.
Most times I compress my videos, I use the same --silent_speed, the same --ignore, etc. Would be time-saving if I could store those preferences in a file instead of modifying the source.

Make sure that it is something that YOU need, not that just seems useful.
I would use it every single time I compressed my videos!

(Make sure you're using the latest version)

**Comment by WyattBlue** [comment]
That already exists! You can edit `config.txt` to change defaults. It's not in the home directory but you can run `auto-editor --debug` to see where it exists on your machine.

That being said, I'm a big disappointed no one else pointed that out before I responded.
