### ISSUE TITLE
Why --video_bitrate 5000k --audio_bitrate 192 didn't work?

### ISSUE THREAD

**Issue by yigexuezha** [WyattBlue/auto-editor#171]
I tired,but it(--video_bitrate --audio_bitrate) didn't work! 
auto-editor  test.mp4 --keep_tracks_seperate --cut_by_this_track 1 exportMediaOps --video_bitrate 2716k --audio_bitrate 192k
auto-editor  test.mp4 --keep_tracks_seperate --cut_by_this_track 1 exportMediaOps --video_bitrate 2716 --audio_bitrate 192
auto-editor  test.mp4 --keep_tracks_seperate --cut_by_this_track 1 --my_ffmpeg --video_bitrate 2716k --audio_bitrate 192k 
auto-editor  test.mp4 --keep_tracks_seperate --cut_by_this_track 1 --my_ffmpeg exportMediaOps --video_bitrate 2716k --audio_bitrate 192k 

**Hope someone can help me!**

**Comment by WyattBlue** [comment]
You need to set `--video_codec` also!

It doesn't really matter what value you set it. (It can be the same as the original video), it can't just be "uncompressed", the default value.
