### ISSUE TITLE
`mclip` arg help message seems off

### ISSUE THREAD

**Issue by AtilioA** [WyattBlue/auto-editor#173]
`--min_clip_length`/`-mclip`
`'set the minimum length a clip can be. If a clip is too short, cut it.'`

Shouldn't it be 'If a clip is too **long**, cut it'? It doesn't make sense to cut an already short clip.

**Comment by igavronski** [comment]
Hi Atilio,
I understand it is meant to cut the "ã", "é", and "né" from your speech.
Iuri

**Comment by AtilioA** [comment]
So if a short clip within the video is created because there's silence around it, `-mclip` determines the clip's minimum length for it to be included in the altered output?

**Comment by WyattBlue** [comment]
Yes, the help message is correct. "if a clip is too long, cut it" would describe the maximum clip length.
