### ISSUE TITLE
Could add --frame_marginBegin and  --frame_marginEnd?

### ISSUE THREAD

**Issue by yigexuezha** [WyattBlue/auto-editor#176]
Could add --frame_margin**Begin** and  --frame_margin**End**?
Because usually when you read, the word begin is loud voice,the end is low voice. 
So it can precise control.Some world in the end won't lost.

**Comment by yigexuezha** [comment]
the label should be enhancement, but i can't change

**Comment by WyattBlue** [comment]
You can now specify start margin and end margin separately in 22w01a!

Instead of making two new options though, I allowed `--frame_margin` to use a comma as a delimiter 

```bash
# Set a start margin of 3 frames and an end margin of 8 frames
auto-editor example.mp4 --frame_margin 3,8
```

I'm closing this issue because of this new feature.
