### ISSUE TITLE
Code problem I am a win10 system. Follow the steps or not!

### ISSUE THREAD

**Issue by hn179** [WyattBlue/auto-editor#180]
Hello! First of all, thank you very much for developing this product! I am a Chinese user and my English is not good. This was translated with an English translator, and I cannot express my respect for you! I installed it according to the steps, but it doesn’t work. Is there a PC terminal? It’s simple and clear. You can buy it with money. I believe many UP owners are willing to pay.
Problem code:C:\WINDOWS\system32>auto-editor C:\Users\123\Desktop\test.mp4
['C:\\Users\\123\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\auto_editor\\win-ffmpeg\\bin\\ffmpeg.exe', '-hide_banner', '-y', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-pix_fmt', 'yuv420p', '-s', '1920*1080', '-framerate', '29.97002997002997', '-i', '-', '-pix_fmt', 'yuv420p', '-vcodec', 'h264', '-crf', '15', '-preset', 'medium', '-movflags', '+faststart', '-strict', '-2', 'C:\\Users\\123\\AppData\\Local\\Temp\\tmpsgoi9kql\\spedup.mp4']
Error! Broken Pipe Error!

C:\WINDOWS\system32>Input #0, rawvideo, from 'pipe:':
  Duration: N/A, bitrate: 745750 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1920x1080, 745750 kb/s, 29.97 tbr, 29.97 tbn, 29.97 tbc
Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (C:\Users\123\AppData\Local\Temp\tmpsgoi9kql\spedup.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Codec AVOption preset (Configuration preset) specified for output file #0 (C:\Users\123\AppData\Local\Temp\tmpsgoi9kql\spedup.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
C:\Users\123\AppData\Local\Temp\tmpsgoi9kql\spedup.mp4: No such file or directory

**Comment by jeanviet** [comment]
Hello @WyattBlue 


Thank you a lot for Auto-Editor ! it saved me a lot of time for my YouTube video edits.

I talked about it on a video : 
https://youtu.be/bHBFeghSRm0?t=290

And made a tutorial here on my blog 
https://jeanviet.fr/auto-editor-jumpcut/ 

I will be very happy to make you a 10$ donation, but i don't have a crypto wallet.
Do you plan to have a PayPal donation link ?

I have the same problem detailed by @hn179  here in France on my Windows 10 PC. 
If I want to generate a video, I need to export XML on DaVinci Resolve.
Can't generate it directly

` auto-editor MVI_4860.mp4 -exr`

No problem on my Mac book pro. I can easily create directly a video with Jump cuts from the terminal with this command :
` auto-editor MVI_4860.mp4`

On PC / Windows 10, I have this error if I copy and paste the same command 

`st: 0 edit list: 1 Missing key frame while searching for timestamp: 1001░░░░] 0.0% done ETA 08:34 AM
st: 0 edit list 1 Cannot find an index entry before timestamp: 1001.
['C:\\Users\\jeanv\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\auto_editor\\win-ffmpeg\\bin\\ffmpeg.exe', '-hide_banner', '-y', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-pix_fmt', 'yuvj420p', '-s', '1920*1080', '-framerate', '59.94005994005994', '-i', '-', '-pix_fmt', 'yuvj420p', '-vcodec', 'h264', '-crf', '15', '-preset', 'medium', '-movflags', '+faststart', '-strict', '-2', 'C:\\Users\\jeanv\\AppData\\Local\\Temp\\tmp31znwy6n\\spedup.mp4']
Error! Broken Pipe Error!
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, bitrate: 1491500 kb/s
    Stream #0:0: Video: rawvideo, yuvj420p, 1920x1080, 1491500 kb/s, 59.94 tbr, 59.94 tbn, 59.94 tbc`

Then this

`Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (C:\Users\jeanv\AppData\Local\Temp\tmp31znwy6n\spedup.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Codec AVOption preset (Configuration preset) specified for output file #0 (C:\Users\jeanv\AppData\Local\Temp\tmp31znwy6n\spedup.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.`

My PC configuration is low : 
Intel Celeron J4005 2 GhZ, Intel UHD Graphics 600, 8 Go of DDRAM

Maybe it's normal ? Tell me if I can install something to solve that.

Best regards and many thank for the great work !

Jean-Baptiste

**Comment by WyattBlue** [comment]
If you're getting an error that contains `Codec AVOption crf `

you can easily fix it by adding a few options. For example:

```
auto-editor video.mp4
```

becomes:

```
auto-editor video.mp4 --constant_rate_factor unset --preset unset --tune unset
```

Note: these setting will become the default in newer verison.


@jeanviet  I recently made a PayPal. You can donate at wyattblue@protonmail.com

**Comment by jeanviet** [comment]
@WyattBlue PayPal payment sent with a little extra, thanks to the euro rate change ;) 

Thanks for the quick fix. I'm still having an error on Windows 10, with the new command line.
Here a new copy and paste

`auto-editor MVI_4860.mp4 --constant_rate_factor unset --preset unset --tune unset

st: 0 edit list: 1 Missing key frame while searching for timestamp: 1001░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0.0% done ETA 11:08 AM

st: 0 edit list 1 Cannot find an index entry before timestamp: 1001.

['C:\\Users\\jeanv\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\auto_editor\\win-ffmpeg\\bin\\ffmpeg.exe', '-hide_banner', '-y', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-pix_fmt', 'yuvj420p', '-s', '1920*1080', '-framerate', '59.94005994005994', '-i', '-', '-pix_fmt', 'yuvj420p', '-vcodec', 'h264', '-movflags', '+faststart', '-strict', '-2', 'C:\\Users\\jeanv\\AppData\\Local\\Temp\\tmpsdivibpa\\spedup.mp4']
Error! Broken Pipe Error!
Input #0, rawvideo, from 'pipe:':
  Duration: PS C:\Users\jeanv\Videos\jumpcut> N/A, bitrate: 1491500 kb/s
    Stream #0:0: Video: rawvideo, yuvj420p, 1920x1080, 1491500 kb/s, 59.94 tbr, 59.94 tbn, 59.94 tbc
C:\Users\jeanv\AppData\Local\Temp\tmpsdivibpa\spedup.mp4: No such file or directory`

**Comment by WyattBlue** [comment]
@jeanviet Not sure what's causing this error

try adding `--video_codec uncompressed`

**Comment by jeanviet** [comment]
Perfecto ! Problem solved with this new parameter. 
Video generated in 3 mn 13

Many thanks @WyattBlue 

`auto-editor MVI_4860.mp4 --constant_rate_factor unset --preset unset --tune unset --video_codec uncompressed`

st: 0 edit list: 1 Missing key frame while searching for timestamp: 1001░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0.0% done ETA 12:58 PM
st: 0 edit list 1 Cannot find an index entry before timestamp: 1001.
Finished. took 192.53 seconds (0:03:13)

**Comment by WyattBlue** [comment]
@hn179 This problem should be solved by upgrading to 21w22a.

```bash
pip3 install --upgrade auto-editor
```
