### ISSUE TITLE
Automatic J and L cuts

### ISSUE THREAD

**Issue by Aaron-Conroy** [WyattBlue/auto-editor#181]
First of all, thank you so much for all the hard work. This is an amazing tool and it's going to save me a ton of time in the future. 

J and L cuts are techniques video editors use to improve cut transitions. Basically, as the cut happens the audio overlaps before the visual cut. It's a really great technique and it adds a level of smoothness and professionalism to the edit.  

It could work like the frame-margin feature except it would only be for the audio track. I guess this would mean there needs to be two audio tracks so they can overlap.  

This feature isn't needed, it's still a great tool regardless. But I do think it would step it up a level if this was done well. 

Thanks again.

**Comment by WyattBlue** [comment]
I don't think **automatic** J / L cuts are worth implementing, simply because I can't imagine making a good algorithm that can edit these cuts in a non annoying way. 

also because the internal design of the program will have to be rewritten to accommodate J and L cuts
