### ISSUE TITLE
Edit based on keywords

### ISSUE THREAD

**Issue by syntacops** [WyattBlue/auto-editor#185]
Hey devs,

TechSmith (the owner of the video editing software „Camtasia“) recently introduced their new audio editing technology called „*Audiate*“ (https://www.youtube.com/watch?v=0Y8KrEnGG-Y&t=1s)

Audiate transcribes what is spoken and visually adds the text to the audio track. Deleting text removes the corresponding audio parts. So far I haven’t seen any other software with a feature like this and it seems to be very powerful, but also expensive.

I was thinking about how to integrate a similar feature into Audio-Editor without creating an elaborate GUI for it. 

## I would like to suggest the following feature:
`--edit_based_on keywords`

Let’s say I’m recording a tutorial. While recording I make use of two keywords, for example **SAVE** and **CUT**. 

Whenever I say "*SAVE*" (with a small break/silence before and after) a savepoint is set (like in a video game). Whenever I say "*CUT*" I want everything recorded until the last save point to be deleted (the part where I say „SAVE“ and "CUT" included).

Audio-Editor would have to detect those keywords and delete everything between a „*CUT*“ and preceding „*SAVE*“, if there is one. (the keywords included)

## Here some examples:

Raw audio:
>„Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod --CUT-- tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. --SAVE--“

After running audio-editor (the deleted parts are crossed out):
>After running audio-editor (the deleted parts are crossed out):
~~„Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod --CUT--~~ tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. ~~--SAVE--~~“

—————

Raw audio:

> „Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor --SAVE-- invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. --SAVE-- At vero eos et accusam et justo duo dolores et ea rebum. --CUT-- Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. --SAVE-- At vero eos et accusam et justo duo dolores et ea rebum. --CUT-- Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. --SAVE--“

After running audio-editor (the deleted parts are crossed out):
> „Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor ~~--SAVE--~~ invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. ~~--SAVE-- At vero eos et accusam et justo duo dolores et ea rebum.--CUT--~~ Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ~~--SAVE-- At vero eos et accusam et justo duo dolores et ea rebum. --CUT--~~ Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ~~--SAVE--~~“

## The benefit of this feature

This feature would mean that you have a kind of "savegame" while you record. That means you really only have to **record once** because it doesn't matter how many mistakes happen to you. If something goes wrong you just say the keyword to delete and if your recording is error free you can save the recording by saying the keyword to save. 

I'm not sure how elaborate it would be to integrate such a feature, but I think it would be incredibly useful.

What do you think?

Best regards
Jay

**Comment by igavronski** [comment]
I see the benefits of this keyword-based editing, but the feature I liked the most about Audiate is the hesitation detection feature. That would be a *huge* time-saver in auto-editor!

**Comment by WyattBlue** [comment]
@syntacops  It's a fine idea, but there's no good way currently to get the text transcribe of a video or audio file (besides the subtitle tracks, but that would defeat the entire purpose)

None of current audio text analyzers are really suitable. These types of programs are really big and I don't want auto-editor making API calls either. 

Also, it's a demanding feature to add and there are other easier potential editing-on-subtitles features to add. That's why I'm declining this feature request. It doesn't mean I'm forever forsaking the idea, just that I'm not interesting in adding this feature for the time being.

> Note: No, I'm not going to try to implement audio detection for just the SAVE and CUT keywords since it'll be inherently flimsy anyway. I'll rather use a well-tested 3rd party general audio text analyzer.

the core idea of editing based on the message/subtitles is a good one...
