### ISSUE TITLE
Is there a way to downgrade auto-editor?

### ISSUE THREAD

**Issue by igavronski** [WyattBlue/auto-editor#187]
Hi!
I make very long instructional videos and the new frame-based range is too much work for me. I don't have a way to know the actual frames.
Is there a way to downgrade auto-editor to 16?
Thanks in advance.
Iuri

**Comment by WyattBlue** [comment]
Yes! Use pip's == operator.

```
pip3 install auto-editor==21.16.1
```

**Comment by igavronski** [comment]
Thanks!
