### ISSUE TITLE
Audio track normalization before editing

### ISSUE THREAD

**Issue by bdutta** [WyattBlue/auto-editor#189]
Sometimes we have videos -- especially such as that of some online video conference or webinar, where some participant has very low volume audio, however rest of the audio from other participants is quite loud (or normal). The low volume part could be something for which one might have to apply a very high gain, but uniform gain application to entire video would mean significant distortion of already loud parts due to clipping. 

Would be nice if before the chopping/rejoining of parts, an audio channel normalization using something like a 2 pass ffmpeg `dynaudnorm` filter can be applied. This (ideally) should make sure that true silence, pink noise is not amplified (hopefully).

This is definitely something that I'd have immense use for, because I often need to compact, clean-up and archive some key discussions which are then referred by various other people. Being able to reduce lengthy calls (with shared desktop video, or webinar'esque presentation video), to sometimes half of their original length, is extremely useful capability.

Currently using the absolute latest version,

**Comment by WyattBlue** [comment]
I think that audio normalization is desirable, but I don't see the benefit of putting this functionality in auto-editor.

I recommend using [ffmpeg-normalize](https://github.com/slhck/ffmpeg-normalize) on your media then using auto-editor.

**Comment by WyattBlue** [comment]
I changed my mind on this, although I think it makes more sense to apply this *after* editing for more balanced normalizing and efficiency.

**Comment by bdutta** [comment]
Great, and doing it _after_ editing certainly makes sense. It should be normalized across the edited video.
