### ISSUE TITLE
Filesize w/ frame_margin=8 & min_clip_length=6 is smaller, that with defaults

### ISSUE THREAD

**Issue by bdutta** [WyattBlue/auto-editor#191]
(Make sure you're using the latest version)
With a frame_margin=8 and min_clip_length=6, I was expecting the filesize to be larger than using auto-editor without those options (i.e. default values for those options), since I'd imagine more aggressive reduction, but I see that the filesize is smaller (about 22%).

The source is mkv with 1 video and 1 audio stream, with about 3.5hrs of webinar recording done using CISCO Webex, with following characteristics:
```
    Stream 0
        Codec: H264 - MPEG-4 AVC (part 10)(avc 1)
        Res: 1600x900
        Frame rate: 12
    Stream 1
        Codec: MPEG Audio layer 1/2 (mpga)
        Sample rate: 44100 Hz
        Bits per sample: 32
        Bitrate: 32 kb/s
```

With the defaults, the resulting output of auto-editor is 11.2GB, but frame_margin=8 & min_clip_length=6 the resulting output is 9.2GB. Didn't expect such a difference.

**Does the example video work? (if applicable)**
Yes

**What does the program output when `--debug` or `--show_ffmpeg_debug` is appended to your command/use case**

```
Python Version: 3.8.5 64-bit
Platform: Linux 5.11.0-18.1-liquorix-amd64
Config File path: /home/bdutta/.local/lib/python3.8/site-packages/auto_editor/config.txt
FFmpeg path: ffmpeg
FFmpeg version: 4.2.4-1ubuntu0.1
Auto-Editor version 21w22a
```

**What's your platform? (if applicable)**

```
Python Version: 3.8.5 64-bit
Platform: Linux 5.11.0-18.1-liquorix-amd64
Config File path: /home/bdutta/.local/lib/python3.8/site-packages/auto_editor/config.txt
FFmpeg path: ffmpeg
FFmpeg version: 4.2.4-1ubuntu0.1
Auto-Editor version 21w22a
```

**What's your input? (if applicable)**

```
file: Day4_VJonly.mkv
 - fps: 12
 - duration: 03:05:55.17
 - resolution: 1600x900 (16:9)
 - video codec: h264
 - video bitrate: None
 - audio tracks: 1
   - Track #0
     - codec: mp3
     - samplerate: 44100
     - bitrate: 32 kb/s
```

**Comment by WyattBlue** [comment]
The reason the file size is smaller probably is that `--min_clip_length` is higher than the default 3. This causes auto-editor to cut out *more* and is why the size is smaller.
