### ISSUE TITLE
Multiple range linked variable frame cropping and full-frame blanking/freeze-frame

### ISSUE THREAD

**Issue by bdutta** [WyattBlue/auto-editor#192]
Currently I am working with bunch of webinar recordings whose flow goes like this:

- Pre-meeting introduction where multiple participants are visible with their photos, names, email-ids, but some context is also built for the rest of the talk
- Powerpoint presentation on screen which is sometimes not in full-screen mode and has the rest of the editor window visible, but my interest is only in the presentation canvas, so need to crop to a smaller part of the frames.
- Someone suggest or presenter realizes and Powerpoint presentation goes full-screen so no further cropping is required
- Someone needs to demo something in one or more terminal windows, but the font-size is small, so cropping and zooming to specific part of screen (x,y of top-left of bounding-box and length/bredth) which is scaled to fit window would be desirable

All of the above happen in the course of a single video, but having scanned through the window I would have noted down the time offsets in hh:mm:ss format, and know when to do what i.e. in what ranges what should be done, like crop-scale (zoom) with one setting, full-screen, crop-scale (zoom) with another setting, full-screen, crop-scale (zoom) with previous setting, and sometimes blanking out the screen so as to hide the personal details of meeting attendees, or replacing with a fixed image that stays displayed for a length.

**Comment by bdutta** [comment]
Perhaps a part of what I'm hoping for is possible using the newly introduced zoom feature, but I'm not sure if it is so exactly as I'm yet to try it out. Also, any kind of estimation of time required for each phase would be highly desirable. Right now, when working with large files, it is not clear if my i5-8400 (6 cores, 12 threads) and 32GB RAM would remain at >90% CPU (for almost all cores) for 1 hour or 3 hours. If I knew how long the job would take (even approximately), I could just go and get a coffee, read news or use my other PC for work.

**Comment by WyattBlue** [comment]
The zoom effect and the rectangle effect should do what you need.
