### ISSUE TITLE
Offset to Sync Video and Audio?

### ISSUE THREAD

**Issue by JesperDramsch** [WyattBlue/auto-editor#193]
I record my videos with external audio, so sometimes, the files have different start times. It would be fantastic to be able to give a number of frames as the offset between the video and audio track, so I don't have to export a synced file first.

´auto-editor file_name --video_offset 5 -exr`

Since this is using FFmpeg, I was looking at the usage of the `--itsoffset` flag. I don't know if this would be viable. Here's a good link I found about it: https://superuser.com/questions/982342/in-ffmpeg-how-to-delay-only-the-audio-of-a-mp4-video-without-converting-the-au

I don't expect the auto-editor to automatically find the offset. That would be some magic I don't know how to do. But supplying a constant offset rather This example would cause the video to be offset by a constant 5 frames against the audio syncing both. I have looked through the help and the documents and couldn't see it. Apologies if it exists already.

**Comment by JesperDramsch** [comment]
Also, thank you for this amazing tool.

**Comment by WyattBlue** [comment]
yeah I don't see the benefit of this being embedded in auto-editor.
