### ISSUE TITLE
XML Exported to premiere always show media pending (only in V21.22.1 and after)

### ISSUE THREAD

**Issue by honjiaxuan** [WyattBlue/auto-editor#195]
This bug only appear starting from 21.22.1, 21.21.1 and before has no issues.

XML Exported to premiere always show media pending.

I have attached the xml file (but rename to txt file), the width and height is set to None for V21.24.1 and V21.22.1

[file created using V21.21.1.txt](https://github.com/WyattBlue/auto-editor/files/6680844/file.created.using.V21.21.1.txt)
[file created using V21.24.1.txt](https://github.com/WyattBlue/auto-editor/files/6680845/file.created.using.V21.24.1.txt)

**What's your platform? (if applicable)**
Macbook, the Premiere Pro version is V14.0.0 (Build 572)

**Comment by WyattBlue** [comment]
Can't confirm, I tried importing the example file on MacOS and Windows and it worked correctly.

Your premiere version is very old, I just upgraded to v15.2 and you should do so as well.

**Comment by honjiaxuan** [comment]
I think it is not related to the Premiere, I run the code and that is the xml file as the result. It is different for the width and height before I import into Premiere

**Comment by Ergs751** [comment]
im having an issue with the xml files too when i put export to premier

**Comment by WyattBlue** [comment]
I have found one problem, when using a video that has multiple audio tracks, the definition of `<file-2>` are not placed in >=21.22.1 but are correctly put in 21.21.1 and lower. 

For the width and height being `None`, I have not experienced this, and I'm not sure if that is what's causing premiere pro to not work or some other issue.

**Comment by Ergs751** [comment]
> I have found one problem, when using a video that has multiple audio tracks, the definition of `<file-2>` are not placed in >=21.22.1 but are correctly put in 21.21.1 and lower.
> 
> For the width and height being `None`, I have not experienced this, and I'm not sure if that is what's causing premiere pro to not work or some other issue.

The only problem I'm getting now is that when I do xml the audio comes out in mono and doesn't do left and right

**Comment by WyattBlue** [comment]
> The only problem I'm getting now is that when I do xml the audio comes out in mono and doesn't do left and right

Good to know, I'll see if adding more stereo attributes will help.

**Comment by WyattBlue** [comment]
@honjiaxuan @Ergs751 I released a new version to address some of the problems. Let me know if it fixes the problem or not.

**Comment by Ergs751** [comment]
> @honjiaxuan @Ergs751 I released a new version to address some of the problems. Let me know if it fixes the problem or not.

I'm sorry I have taken too long to check, thank you alot!

**Comment by honjiaxuan** [comment]
@WyattBlue 
Hi, thank you for helping us to fix it!

The file is created successfully but the resolution do not match the original video file.

My original video file is 1080*1920 but the exported xml file has the height 720 and width 1280.

I attached my exported xml file for your reference
[xml file.txt](https://github.com/WyattBlue/auto-editor/files/6737879/xml.file.txt)
