### ISSUE TITLE
Why --audio_bitrate 192k  is not work?

### ISSUE THREAD

**Issue by yigexuezha** [WyattBlue/auto-editor#198]
Why --audio_bitrate 192k  is not work? out put is 128k

 --cut_by_this_track 0 --frame_margin 25  --my_ffmpeg exportMediaOps  --video_codec copy --silent_threshold 0.12   --constant_rate_factor 30 --preset superfast --audio_bitrate 192k --no_open

**Comment by WyattBlue** [comment]
Please don't make duplicate issues. You are allowed to bump previous issues. Original #172.
