### ISSUE TITLE
XML : Keep deleted silent parts

### ISSUE THREAD

**Issue by Toonie88** [WyattBlue/auto-editor#199]
Hello,

First of all, thank you for your wonderful script.

I want to know if it's possible to have a function to keep the deleted parts in the xml file ?

just add all the silent cuts in the file, and let the creator remove himself the cuts he wants.

thank you

**Comment by WyattBlue** [comment]
I don't see this feature being worth complicating the design of auto-editor, so I'll be declining this request.

One workaround is to set `--silent_speed` close to 1 so that it is similar but not 1 so that it doesn't get merged with the loud sections.
