### ISSUE TITLE
Different volume level between originalAudio.py and fastVideo.py

### ISSUE THREAD

**Issue by sasa** [WyattBlue/auto-editor#20]
Thank you for auto-editor, which is amazing and a real glimmer of hope that this project will thrive.

I have noticed that videos are rendered way faster with the addition of fastVideo. Thank you for that.

But the audio treatment is different, too. Making an additional step necessary in post. Is there any way to match the output level of audio between these two? Because I use both when creating clips that I later render out as one file.

Hoping that there is an easy solution.

Greetings
Saša

**Comment by WyattBlue** [comment]
Hi Saša,

I'll look into this issue and see what I can do. 

It is possible to change the editing script from fastVideo to originalMethod by adding `--hardware_accel 0` option.

**Comment by WyattBlue** [comment]
I couldn't find an easy way to match the way fastVideo handles audio to originalAudio. 

I'm not giving up on this issue though, I'll figure out a way to do it eventually.

**Comment by sasa** [comment]
I appreciate that, Wyatt. I have also looked into it. But I am not that familiar with Python or cv2. I wonder though why the loudness is different. It looks to me as if the audio processing is actually the same between the different methods. Maybe the audio processing could be refactored into one function or method so the same code is called from everywhere. Also, I wish the source code would be better documented. Especially in places where the picture and audio splitting and recombining is done. I have a hard time understanding what is going on. Otherwise, I could be of more help and probably others, too.

I do have other requests and ideas for which I will probably add more issues.

**Comment by WyattBlue** [comment]
I fixed this issue by removing originalAudio.py and using fastAudio I built from the ground up. It should sound the same as fastVideo.py

**Comment by sasa** [comment]
With fastVideo working for silent speed 1 and above there is actually no need for that anymore. But anyway, thank you so moch. auto-editor is really getting awesome.
