### ISSUE TITLE
Error! Could not find file (because of spaces in the folder/files names)

### ISSUE THREAD

**Issue by Flokonn** [WyattBlue/auto-editor#202]
When I tried to auto-edit a file it says "Error! Could not find file: file path"
Of course when I remove the spaces it works.

**Comment by WyattBlue** [comment]
This is bash/zsh thing, sometimes you need to wrap things in quotes or else the interpreter gets confused or inputs incorrect arguments to auto-editor

```
# bad!
auto-editor path/to/my file.mp4

# good
auto-editor "path/to/my file.mp4"
```
