### ISSUE TITLE
Broken pipe error

### ISSUE THREAD

**Issue by IBrUh123** [WyattBlue/auto-editor#203]
I have checked and i think i am doing everything right but I keep getting a broken pipe error.

**Comment by WyattBlue** [comment]
Context please? Is it displaying any other information. What options are you using.

**Comment by IBrUh123** [comment]
Sorry for the vague comment and lack of context I was just in a hurry,
I am using frame margin and that's it
![Screenshot 2021-08-10 221631](https://user-images.githubusercontent.com/88745923/128936222-c238941e-b875-4382-bb1d-12e75cf163a9.png)
I have very little experience in coding and have close to no clue what I am doing.

**Comment by WyattBlue** [comment]
I think you're using an old version of auto-editor that had a mistake.

Try upgrading auto-editor

```
pip3 install auto-editor -U
```
