### ISSUE TITLE
Shotcut project repair

### ISSUE THREAD

**Issue by Abhisekvishal** [WyattBlue/auto-editor#205]
After completion of shotcut project when i open the same project in shotcut it says "your shotcut project needs repair". After clicking yes it repairs it. It allows me then to edit in the project. Using shotcut version 21.03.21.

**Comment by WyattBlue** [comment]
Hmm, I'm not having getting any prompt when I import my XML file. Maybe your shotcut is too old?

I've tested Shotdcut using version `ARCH-21.06.29` and `21.05.18` on MacOS.

**Comment by WyattBlue** [comment]
Closing because no word from author. Please share more details.
