### ISSUE TITLE
--export_to_resolve do not export right setting when fps value is not an Integer

### ISSUE THREAD

**Issue by anosanstudio** [WyattBlue/auto-editor#207]
(Make sure you're using the latest version) yes

**What went wrong**

When the fps value of the input video is not an integer(like 29.97 or 23.98), the output xml file is set to an incorrect value

The input video file is 23.98fps
but the output file settings:
<img width="912" alt="xml" src="https://user-images.githubusercontent.com/90784912/133474130-901429c9-6fbb-425a-9e45-a18924a3b6a9.png">
frameDuration should be: 1001/24000s(in 23.98fps) and 1001/30000s(in 29.97fps)
FFVideoFormat should be: 2398(in 23.98fps) and 2997(in 29.97fps)
Causes DaVinci Resolve to not set the frame rate correctly

Thanks in advance!

**Comment by WyattBlue** [comment]
`--export_to_resolve` is not supported anymore due to issues with finding clips. Thank you for reporting this.
