### ISSUE TITLE
Do not playback videos after finishing

### ISSUE THREAD

**Issue by sasa** [WyattBlue/auto-editor#21]
I have another issue for which I have simply removed the last lines of the code.

The problem: I use auto-editor mainly for creating screencasts. I record 2 to 5 minutes of screen activity (explaining something) in which I pause often to think what to say next. All the pauses are then removed by auto-editor. Which is great. When I am finished with a clip I immediately start the next recording, while auto-editor is working on the current one. I created a script for that in which each recording is put into a queue directory and processed. Since I have 16 cores I can sometimes process 5 videos at once.

That said, it is very irritating when a video just starts because it is finished rendering. I think this should not be the default behavior or it should at least be configurable.

**Comment by WyattBlue** [comment]
I added the `--no_open` option that stops the program from starting videos.

Thanks for the suggestion :)
