### ISSUE TITLE
Improve documentation on ranges

### ISSUE THREAD

**Issue by igavronski** [WyattBlue/auto-editor#211]
Could you please update the range documentation to show the options you provided on #184 ?
There are no mentions to negative ranges, for example.

**Comment by WyattBlue** [comment]
I've updated the [range syntax page](https://auto-editor.com/cli/range_syntax) with new feature mentioned in #184. Thanks for point that out.

**Comment by igavronski** [comment]
There are no references to negative numbers...

**Comment by WyattBlue** [comment]
<img width="978" alt="Screen Shot 2021-10-03 at 18 39 36" src="https://user-images.githubusercontent.com/57511737/135775764-8a158461-d4a1-476b-9362-cd5980d4047f.png">
