### ISSUE TITLE
Multicam synchronization by audio aligning

### ISSUE THREAD

**Issue by forart** [WyattBlue/auto-editor#214]
Hi there, thanks for your very interesting video tool !

Due to its "Exporting to Editors" feature, it would be very useful to make it able to synch multiple video tracks of the same event (aka multicam recordings), an ability available on commercial products such as [PluralEyes](https://www.maxon.net/it/red-giant-complete/pluraleyes) or [Syncaila](https://syncaila.com/).

The most interesting/complete resource to easily implement it is [AudioAlign](https://github.com/protyposis/AudioAlign) (wich is based on .NET [Aurio](https://github.com/protyposis/Aurio) library) by @protyposis.

Hope that inspires !

**Comment by WyattBlue** [comment]
Not sure why I kept this alive for so long. Auto-Editor doesn't even have a system to move timeline clips.
