### ISSUE TITLE
how to prevent and run command smoothly

### ISSUE THREAD

**Issue by chye5200** [WyattBlue/auto-editor#215]
Microsoft Windows [Version 10.0.19043.1288]
(c) Microsoft Corporation. All rights reserved.

C:\Users\chye8>auto-editor -h

  progressOps:
  --machine_readable_progress: set progress bar that is easier to parse.
  --no_progress: do not display any progress at all.

  metadataOps:
  --force_fps_to: manually set the fps value for the input video if detection fails.

  motionOps:
  --dilates, -d: set how many times a frame is dilated before being compared.
  --width, -w: scale the frame to this width before being compared.
  --blur, -b: set the strength of the blur applied to a frame before being compared.

  urlOps:
  --format: the format youtube-dl uses to when downloading a url.
  --output_dir: the directory where the downloaded file is placed.
  --limit_rate, -rate: maximum download rate in bytes per second (50k, 4.2m)
  --id: manually set the YouTube ID the video belongs to.
  --block: mark all sponsors sections as silent.
  --download_archive: Download only videos not listed in the archive file. Record the IDs of all downloaded videos in
  it
  --cookies: The file to read cookies from and dump the cookie jar in.
  --check_certificate: check the website certificate before downloading.

  exportMediaOps:
  --video_bitrate, -vb: set the number of bits per second for video.
  --audio_bitrate, -ab: set the number of bits per second for audio.
  --sample_rate, -r: set the sample rate of the input and output videos.
  --video_codec, -vcodec: set the video codec for the output media file.
  --audio_codec, -acodec: set the audio codec for the output media file.
  --preset, -p: set the preset for ffmpeg to help save file size or increase quality.
  --tune, -t: set the tune for ffmpeg to compress video better in certain circumstances.
  --constant_rate_factor, -crf: set the quality for video using the crf method.
  --has_vfr: skip variable frame rate scan, saving time for big video files.

  effectOps:
  --zoom: set when and how a zoom will occur.
  --rectangle: overlay a rectangle shape on the video.
  --circle: overlay a circle shape on the video.
  --background: set the color of the background that is visible when the video is moved.
  --scale: scale the output media file by a certain factor.
  --combine_files: combine all input files into one before editing.
  --mark_as_loud: the range that will be marked as "loud".
  --mark_as_silent: the range that will be marked as "silent".
  --cut_out: the range of media that will be removed completely, regardless of the value of silent speed.
  --add_in: the range of media that will be added in, opposite of --cut_out
  --set_speed_for_range: set an arbitrary speed for a given range.
  --motion_threshold: how much motion is required to be considered "moving"
  --edit_based_on, --edit: decide which method to use when making edits.
  --cut_by_this_audio, -ca: base cuts by this audio file instead of the video's audio.
  --cut_by_this_track, -ct: base cuts by a different audio track in the video.
  --cut_by_all_tracks, -cat: combine all audio tracks into one before basing cuts.
  --keep_tracks_seperate: don't combine audio tracks when exporting.
  --export_as_audio, -exa: export as a WAV audio file.
  --export_to_premiere, -exp: export as an XML file for Adobe Premiere Pro instead of making a media file.
  --export_to_resolve, -exr: export as an XML file for DaVinci Resolve instead of making a media file.
  --export_to_final_cut_pro, -exf: export as an XML file for Final Cut Pro instead of making a media file.
  --export_to_shotcut, -exs: export as an XML timeline file for Shotcut instead of making a media file.
  --export_as_json: export as a JSON file that can be read by auto-editor later.
  --export_as_clip_sequence, -excs: export as multiple numbered media files.
  --temp_dir: set where the temporary directory is located.
  --ffmpeg_location: set a custom path to the ffmpeg location.
  --my_ffmpeg: use the ffmpeg on your PATH instead of the one packaged.
  --version: show which auto-editor you have.
  --debug, --verbose, -d: show debugging messages and values.
  --show_ffmpeg_debug: show ffmpeg progress and output.
  --quiet, -q: display less output.
  --preview: show stats on how the input will be cut.
  --no_open: do not open the file after editing is done.
  --min_clip_length, -mclip: set the minimum length a clip can be. If a clip is too short, cut it.
  --min_cut_length, -mcut: set the minimum length a cut can be. If a cut is too short, don't cut
  --output_file, --output, -o: set the name(s) of the new output.
  --silent_threshold, -t: set the volume that frames audio needs to surpass to be "loud".
  --silent_speed, -s: set the speed that "silent" sections should be played at.
  --video_speed, --sounded_speed, -v: set the speed that "loud" sections should be played at.
  --frame_margin, --margin, -m: set how many "silent" frames of on either side of "loud" sections be included.
  --help, -h: print info about the program or an option and exit.
  (input): the path to a file, folder, or url you want edited.

  Have an issue? Make an issue. Visit https://github.com/wyattblue/auto-editor/issues

  The help option can also be used on a specific option:
     auto-editor --frame_margin --help

C:\Users\chye8>auto-editor d:\downloads\ss.mp4
Traceback (most recent call last):
  File "C:\Users\chye8\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chye8\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\chye8\AppData\Local\Programs\Python\Python310\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
  File "C:\Users\chye8\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_editor\__main__.py", line 748, in main
    main_loop(input_list, ffmpeg, args, speeds, segments, log)
  File "C:\Users\chye8\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_editor\__main__.py", line 729, in main_loop
    cuts, output_path = edit_media(i, inp, ffmpeg, args, progress, speeds,
  File "C:\Users\chye8\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_editor\__main__.py", line 555, in edit_media
    make_video_file(inp, chunks, output_path)
  File "C:\Users\chye8\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_editor\__main__.py", line 515, in make_video_file
    from auto_editor.render.av import render_av
  File "C:\Users\chye8\AppData\Local\Programs\Python\Python310\lib\site-packages\auto_editor\render\av.py", line 4, in <module>
    import av
ModuleNotFoundError: No module named 'av'

C:\Users\chye8>

**Comment by WyattBlue** [comment]
You need to have the `av` pip module installed. av currently doesn't have pre-build wheels for Python 3.10, so you should download Python 3.9 and then install auto-editor with pip.
