### ISSUE TITLE
About #172

### ISSUE THREAD

**Issue by yigexuezha** [WyattBlue/auto-editor#217]
Thank you for fixed.
mp4 is fixed.
But mp3 to mp3 is still 128k
Is somewhere still wrong?

auto-editor test.mp3 -o input.mp3 --frame_margin 16 --my_ffmpeg exportMediaOps --audio_codec mp3 --audio_bitrate 320k  --no_open

**Comment by WyattBlue** [comment]
I noticed this problem when I was reviewing the exporting code.

This should be fixed in `21w46a` when I removed redundancies on how new audio and video files get created.
