### ISSUE TITLE
Errors: Audio and low quality output video

### ISSUE THREAD

**Issue by nugoha** [WyattBlue/auto-editor#218]
**What went wrong**

If you use the auto-editor to output a xml file to put it into DaVinci Resolve software, the stuttering sound is very annoying. I didn't get this error before. Now I don't understand why. For the most part I export to DaVinci Resolve for further editing.

Previously, using the command: `auto-editor D:\video\example.mp4 -exr` gave a good result (no error) but now doing so the sound is corrupted and the video speed is naturally faster without Use another command.

If you use auto-editor to output mp4 files without any command, the video quality will be low. The original video is more than 300Mb but the new video is only 80Mb. Blurry image is not clear. I tried the video codec command and the video bitrate still doesn't work.

**Paste the commands you've tried**
```
auto-editor D:\video\example.mp4 -exr 
```
and also
```
auto-editor D:\video\example.mp4
```

**Describe what went wrong**
Low quality video or problem with audio sound in DaVinci Resolve

**What's your platform? (if applicable)**

```
Python Version: 3.9.6 64-bit
Platform: Windows 10
Config File path: C:\Users\KyThuat88\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\config.txt
FFmpeg path: C:\Users\KyThuat88\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
FFmpeg version: 4.3
Auto-Editor version 21w46b
```

**Comment by WyattBlue** [comment]
Tried both methods. Can't confirm. Closing.
