### ISSUE TITLE
Lossless recording formats for video and audio (make them configurable)

### ISSUE THREAD

**Issue by sasa** [WyattBlue/auto-editor#22]
I know that auto-editor should probably stay true to what it was supposed to do in the beginning, convert YouTube videos. My screencasts will also eventually end up on YouTube, but while editing a little more flexibility with formats would be great. For example, I would prefer if auto-editor would be configurable enough to also handle different video and audio codecs. FFMPEG can already do this. Since I use OBS with the StreamFX plugin I can record to almost any format combo.

https://github.com/Xaymar/obs-StreamFX

Right now I record to MKV container with PNG and 16 BIT Wave (pcm_s16le) so essentially lossless.

![image](https://user-images.githubusercontent.com/9251/85222719-1ab7d680-b3f0-11ea-9a3f-a78a5d3b030e.png)

It would be great if the whole cutting process would internally work with lossless formats, too, so for audio not with a bit rate of 160 Kbps. (Although it would also be nice to make the bit rate configurable).

Since the standard process creates JPGs of all the frames, the question would be: Would it be possible to record in a format that would make the first step obsolete. Meaning, if I already record to PNGs in a MKV container, can the script not recognize that and go immediately to step 2 and use the lossless PNGs?

Or maybe there could be a convention saying that a certain combination of video and audio format will give the best result in terms of speed or quality. StreamFX also allows to use Apple ProRes.

So a lot of thoughts in this issue. But I'm looking to start a conversation and see how far the usefulness could be pushed or if I just have to find other ways to do this, because my work flow is just not common enough.

**Comment by WyattBlue** [comment]
It is theoretically possible to skip splitting the video into jpegs and audio tracks if the user already has in an image sequence (png is okay) and has the audio tracks too. (I would just need to do a quick patch and a new dedicated flag)

In my limited knowledge of mkvs, the best way to split that container into any kind of image sequence is with ffmpeg, and that is what auto-editor is already doing. Again, I don't know much about the mkv video container and it might be possible to get the lossless pngs directly somehow. 

Setting ``--frame_quality`` to 1 is always an option to get better results, but that still doesn't produce a lossless vid. 

I might depreciate ``--frame_quality`` and just always set it to 1 internally in the future. Low frames quality didn't seem to save time any time or storage space anyway.

Thank you for sending such a high quality and well researched issue. It's people like you who make auto-editor great.

**Comment by sasa** [comment]
Please wait a little while. I am trying to find out what the best option would be. Encoding to PNG was not reliable. OBS sometimes doesn't want to do it. I tried lossless jpeg, but this made the file size huge. Which is a problem when doing multiple encoding jobs in parallel. I also only got around 20 % of the performance (0.75 fps instead of 4-5 fps). Now I am trying ffv1 which is actually ffmpeg internal lossless raw format which is compressed and way smaller that mjpeg). I wonder if it would be possible to just go frame by frame over the lossless format, but do it in one step, not two. Isnt that what OpenCV does anyway? I can upload a ffv1 mkv if you need one. Just let me know. I am also going to report back in a couple of days if this is a workable solution.

**Comment by sasa** [comment]
Also I have experimented with output quality in the final encoding. If I record a webpage with light colors, just like this one here on Github. The light gray especially gets lost. Doesnt look nice. What I do right now is:

`cmd = ['ffmpeg', '-y', '-framerate', str(frameRate), '-i',
        f'{TEMP}/newFrame%06d.jpg', '-c:v', 'ffv1', f'{TEMP}/output{extension}']`

Output quality should be configurable. I use ffv1 here because I produce many clips that I import into my NLE and cut/correct/grade for a final time.

**Comment by sasa** [comment]
I noticed that auto-editor now just copies the video and audio stream now. This is perfect. Thanks for all your work Wyatt. I think this can be closed. Although for some ppl it would probably still be a good feature to determine the output codecs for video and audio.

**Comment by WyattBlue** [comment]
I agree. Choosing codecs is a good feature and I'll think about implementing that in the future.
