### ISSUE TITLE
Export to Davinci Resolve

### ISSUE THREAD

**Issue by danfleser** [WyattBlue/auto-editor#222]
**What version are you running?** 
$latest

**What went wrong**
Export to Davinci Resolve version:
![image](https://user-images.githubusercontent.com/20419925/145718251-bf1756c0-7509-4c4a-af3b-f2ac1e557f6e.png)

does not work to import file this is what errors I got, even if I manually import the file into DaVinci resolve media pool

also for the file example.mp4 the command: python -m auto_editor example.mp4 --export_to_resolve works blazing fast, but for my video works very very slow(5 min approx) and it says this extracting audio thing
![image](https://user-images.githubusercontent.com/20419925/145718413-f6d5d50c-8d21-4caa-9811-f9f3022dc25f.png)
then works 
![image](https://user-images.githubusercontent.com/20419925/145718416-4bbaf932-0a35-4a4c-ac74-5e73e593960c.png)

import settings:
![image](https://user-images.githubusercontent.com/20419925/145718449-64f57217-0b4e-410c-8834-939100addfd0.png)

error message even if I already imported the video into media pool:
![image](https://user-images.githubusercontent.com/20419925/145718459-ab199d2b-a4a5-4028-b960-b1f94d0aae36.png)

**Comment by danfleser** [comment]
[video.txt](https://github.com/WyattBlue/auto-editor/files/7699007/video.txt)
 this is the generated video.xml file,  I renamed it to .txt in order to upload it here, as github does not allow me to upload .xml file

**Comment by danfleser** [comment]
This is the exported timeline if I edit the video manually in davinci resolve then export it to final cu pro 1.9 timeline exidted and exported via davinci resolve to finalcutpro 1dot9.fcpxml
[timeline exidted and exported via davinci resolve to finalcutpro 1dot9.txt](https://github.com/WyattBlue/auto-editor/files/7699010/timeline.exidted.and.exported.via.davinci.resolve.to.finalcutpro.1dot9.txt)

**Comment by danfleser** [comment]
video information 
![image](https://user-images.githubusercontent.com/20419925/145719918-6414a2ea-0956-4e74-8c1f-97945324180d.png)

**Comment by danfleser** [comment]
@WyattBlue

**Comment by WyattBlue** [comment]
I'm removing support for DaVinci resolve. Thank you for being patient.

**Comment by AhmedThahir** [comment]
Any chances for bringing back support for davinci resolve?

**Comment by amarques** [comment]
Hello,
Sorry to bother u guys but, again... any chances for bringing back support for DavinciResolve?

Thanks and Kind Regards.
