### ISSUE TITLE
dyld[76947]: Library not loaded: /usr/local/opt/fdk-aac/lib/libfdk-aac.2.dylib 

### ISSUE THREAD

**Issue by kedar264** [WyattBlue/auto-editor#223]
I m running on Auto-Editor version 21w50a

I'm getting error
![Screenshot 2021-12-14 at 10 41 32 AM (2)](https://user-images.githubusercontent.com/10330492/145937716-492d20d6-3d0c-4f2a-9f23-c09ab8ae89b9.png)

```
I tried the below command which works flawless previously
auto-editor /Volumes/BX500/AAI/Pav\ bhaji/pav\ bhaji\ raw.MOV  --frame_margin 13 --export_to_final_cut_pro
```

I think the fk-aac is throwing this error I tried to downgrade fdk-aac but brew switch command not found

**What's your platform? (if applicable)**
I'm running on Mac OS Monterey 12.1 Beta

Python Version: 3.9.7 64-bit
Platform: Darwin 21.2.0 x86_64
Config File path: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/auto_editor/config.txt
FFmpeg path: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/auto_editor/ffmpeg/Darwin/ffmpeg
FFmpeg version: dyld[76975]:
Auto-Editor version 21w50a

```
![Screenshot 2021-12-14 at 10 41 32 AM (2)](https://user-images.githubusercontent.com/10330492/145937716-492d20d6-3d0c-4f2a-9f23-c09ab8ae89b9.png)
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/auto_editor/ffmpeg/Darwin/ffmpeg
  Reason: tried: '/usr/local/opt/fdk-aac/lib/libfdk-aac.2.dylib' (no such file), '/usr/local/lib/libfdk-aac.2.dylib' (no such file), '/usr/lib/libfdk-aac.2.dylib' (no such file)
Auto-Editor made 1 cut, which would have taken about 30 seconds if edited manually.
```

**Comment by kedar264** [comment]
I tried reinstalling everything after cleaning up python from my system but still no luck

**Comment by WyattBlue** [comment]
Try installing ffmpeg with brew and using the `--my-ffmpeg` flag with auto-editor
