### ISSUE TITLE
Variable frame margin

### ISSUE THREAD

**Issue by yigexuezha** [WyattBlue/auto-editor#225]
If sentences or time is long, the frame margin is 16.
If sentences or time is short, the frame margin is 8.

example:
(B is frame margin)

aaaaaaBaaaaaBaaaaaaaaaaaaaBBaaaaaaBaaaBaaaaBaaaaaaaaaaaaaaaaaaaaBBaaaaaBaaaaaBaaaaaaaaaaaaaaaaaaBBaaaaaaaaaaaaaaaaaaaaBBaaaaaaaaaaaaaaa

**Comment by WyattBlue** [comment]
`--frame_margin` already allows for seconds units, which changes the frames based on the fps.

Example:

```
auto-editor example.mp4 --margin 0.6sec 
```

**Comment by yigexuezha** [comment]
> `--frame_margin` already allows for seconds units, which changes the frames based on the fps.
> 
> Example:
> 
> ```
> auto-editor example.mp4 --margin 0.6sec 
> ```

You have misinterpreted what I mean.
