### ISSUE TITLE
Included FFmpeg for MacOS doesn't work on new Macs

### ISSUE THREAD

**Issue by medicrit** [WyattBlue/auto-editor#227]
**What version are you running?** 
pip-21.3.1

**What went wrong**

```
Paste the command you've tried. 
auto-editor /Users/IMAC/Movies/ScreenFlow2.mov

**Describe what went wrong**
The file Movies/ScreenFlow2_ALTERED.mov was not created```

Paste the terminal output here.
iMac-de-Gamal:~ IMAC$ auto-editor /Users/IMAC/Movies/ScreenFlow2.mov
dyld[9389]: Library not loaded: /usr/local/opt/libxcb/lib/libxcb.1.dylib       
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/ffmpeg/Darwin/ffmpeg
  Reason: tried: '/usr/local/opt/libxcb/lib/libxcb.1.dylib' (no such file), '/usr/local/lib/libxcb.1.dylib' (no such file), '/usr/lib/libxcb.1.dylib' (no such file)
Error! The file /Users/IMAC/Movies/ScreenFlow2_ALTERED.mov was not created.    

Something went wrong!
Create a bug report at:
  https://github.com/WyattBlue/auto-editor/issues/
**What conditions must be met for it to be wrong** 

**Does the example video work? (if applicable)**

**What's your platform? (if applicable)**
Run: `auto-editor --debug`

MAC
```
Paste output here.
```IMAC$ auto-editor --debug
Python Version: 3.10.1 64-bit
Platform: Darwin 21.2.0 x86_64
FFmpeg path: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/ffmpeg/Darwin/ffmpeg
FFmpeg version: dyld[9604]:
Auto-Editor version 21w51a
**What properties your input file(s)? (if applicable)**
You can use  `aeinfo ./path/to/video.mp4` or `ffmpeg -hide_banner -i ./path/to/video.mp4` to get standard info.

```
Paste output here.
```

**Comment by WyattBlue** [comment]
Run 

```
./Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/ffmpeg/Darwin/ffmpeg
```

and show the output

**Comment by medicrit** [comment]
iMac-de-Gamal:~ IMAC$ ./Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/ffmpeg/Darwin/ffmpeg
-bash: ./Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/ffmpeg/Darwin/ffmpeg: No such file or directory

**Comment by WyattBlue** [comment]
ugh, run

```
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/ffmpeg/Darwin/ffmpeg
```

and show the output

**Comment by medicrit** [comment]
iMac-de-Gamal:~ IMAC$ /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/ffmpeg/Darwin/ffmpeg
dyld[10356]: Library not loaded: /usr/local/opt/libxcb/lib/libxcb.1.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/ffmpeg/Darwin/ffmpeg
  Reason: tried: '/usr/local/opt/libxcb/lib/libxcb.1.dylib' (no such file), '/usr/local/lib/libxcb.1.dylib' (no such file), '/usr/lib/libxcb.1.dylib' (no such file)
Abort trap: 6

**Comment by WyattBlue** [comment]
Hmm, it appears that the precompiled FFmpeg doesn't work on the new MacBooks.

Remove the binary and install ffmpeg if you haven't already
```
rm /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/ffmpeg/Darwin/ffmpeg

brew install ffmpeg
```

**Comment by medicrit** [comment]
iMac-de-Gamal:~ IMAC$ brew install ffmpeg
-bash: brew: command not found

**Comment by WyattBlue** [comment]
Go install homebrew here: https://brew.sh/

**Comment by medicrit** [comment]
installing homebrew

**Comment by medicrit** [comment]
installing homebrew done

**Comment by medicrit** [comment]
installing ffmpeg

**Comment by medicrit** [comment]
ffmpeg installed but ñook at this 

auto-editor /Users/IMAC/Movies/ScreenFlow2.mov
Error! No ffmpeg found, download via homebrew or restore the included binary.

**Comment by medicrit** [comment]
brew reinstall ffmpeg done but
 iMac-de-Gamal:~ IMAC$ auto-editor /Users/IMAC/Movies/ScreenFlow2.mov
Error! No ffmpeg found, download via homebrew or restore the included binary.

**Comment by medicrit** [comment]
I have macos monterey

**Comment by medicrit** [comment]
finally auto-editor running.

final solution:
As of March 25th, 2020, MacOS + homebrew install has disabled native dependencies support. If additional libraries are required for an FFMPEG build, installing all the extra configurations can be accomplished with this script:

brew uninstall --force --ignore-dependencies ffmpeg
brew install chromaprint amiaopensource/amiaos/decklinksdk
brew tap homebrew-ffmpeg/ffmpeg
brew install ffmpeg
brew upgrade homebrew-ffmpeg/ffmpeg/ffmpeg $(brew options homebrew-ffmpeg/ffmpeg/ffmpeg | grep -vE '\s' | grep -- '--with-' | grep -vi chromaprint | tr '\n' ' ')

then uninstall and reinstall auto-editor

pip3 uninstall auto-editor
pip3 install auto-editor

That's all

credits to JOHN RISELVATO. http://johnriselvato.com/how-to-install-ffmpeg-on-macos/

**Comment by tophee** [comment]
>brew upgrade homebrew-ffmpeg/ffmpeg/ffmpeg $(brew options homebrew-ffmpeg/ffmpeg/ffmpeg | grep -vE '\s' | grep -- '--with-' | grep -vi chromaprint | tr '\n' ' ')

This is where it fails for me:

~~~~
 % brew upgrade homebrew-ffmpeg/ffmpeg/ffmpeg $(brew options homebrew-ffmpeg/ffmpeg/ffmpeg | grep -vE '\s' | grep -- '--with-' | grep -vi chromaprint | tr '\n' ' ')
==> Upgrading 1 outdated package:
homebrew-ffmpeg/ffmpeg/ffmpeg 4.4.1_5 -> 5.0-with-options
==> Downloading https://ffmpeg.org/releases/ffmpeg-5.0.tar.xz
Already downloaded: /Users/christoph/Library/Caches/Homebrew/downloads/ca7feb8ffc2f64941a9c9099ede3d74293119b7d8eed5772e7024fc1cebc250e--ffmpeg-5.0.tar.xz
==> Upgrading homebrew-ffmpeg/ffmpeg/ffmpeg
  4.4.1_5 -> 5.0-with-opti
==> ./configure --prefix=/opt/homebrew/Cellar/ffmpeg/5.0-with-options --enable-s
==> make install
Last 15 lines from /Users/christoph/Library/Logs/Homebrew/ffmpeg/02.make:
                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/atomic:1860:21: error: unknown type name 'ptrdiff_t'
    _Tp* operator+=(ptrdiff_t __op) _NOEXCEPT          {return fetch_add(__op) + __op;}
                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/atomic:1862:21: error: unknown type name 'ptrdiff_t'
    _Tp* operator-=(ptrdiff_t __op) volatile _NOEXCEPT {return fetch_sub(__op) - __op;}
                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/atomic:1864:21: error: unknown type name 'ptrdiff_t'
    _Tp* operator-=(ptrdiff_t __op) _NOEXCEPT          {return fetch_sub(__op) - __op;}
                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [libavdevice/decklink_enc.o] Error 1
20 errors generated.
make: *** [libavdevice/decklink_dec.o] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues

These open issues may also help:
FFmpeg with decklink support installation failure https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/92
Brewing custom ffmpeg but failure at metal execution https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/96
opencv not working after homebrew-ffmpeg installation https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/93

 ~ % 
~~~~

I have looked at the other github issues that are mentioned but none of them helped me fix this. Is this just me being stupid or does this solution no longer work?

**Comment by WyattBlue** [comment]
> > brew upgrade homebrew-ffmpeg/ffmpeg/ffmpeg $(brew options homebrew-ffmpeg/ffmpeg/ffmpeg | grep -vE '\s' | grep -- '--with-' | grep -vi chromaprint | tr '\n' ' ')
> 
> This is where it fails for me:
> 
> ```
>  % brew upgrade homebrew-ffmpeg/ffmpeg/ffmpeg $(brew options homebrew-ffmpeg/ffmpeg/ffmpeg | grep -vE '\s' | grep -- '--with-' | grep -vi chromaprint | tr '\n' ' ')
> ==> Upgrading 1 outdated package:
> homebrew-ffmpeg/ffmpeg/ffmpeg 4.4.1_5 -> 5.0-with-options
> ==> Downloading https://ffmpeg.org/releases/ffmpeg-5.0.tar.xz
> Already downloaded: /Users/christoph/Library/Caches/Homebrew/downloads/ca7feb8ffc2f64941a9c9099ede3d74293119b7d8eed5772e7024fc1cebc250e--ffmpeg-5.0.tar.xz
> ==> Upgrading homebrew-ffmpeg/ffmpeg/ffmpeg
>   4.4.1_5 -> 5.0-with-opti
> ==> ./configure --prefix=/opt/homebrew/Cellar/ffmpeg/5.0-with-options --enable-s
> ==> make install
> Last 15 lines from /Users/christoph/Library/Logs/Homebrew/ffmpeg/02.make:
>                     ^
> /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/atomic:1860:21: error: unknown type name 'ptrdiff_t'
>     _Tp* operator+=(ptrdiff_t __op) _NOEXCEPT          {return fetch_add(__op) + __op;}
>                     ^
> /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/atomic:1862:21: error: unknown type name 'ptrdiff_t'
>     _Tp* operator-=(ptrdiff_t __op) volatile _NOEXCEPT {return fetch_sub(__op) - __op;}
>                     ^
> /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/atomic:1864:21: error: unknown type name 'ptrdiff_t'
>     _Tp* operator-=(ptrdiff_t __op) _NOEXCEPT          {return fetch_sub(__op) - __op;}
>                     ^
> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 20 errors generated.
> make: *** [libavdevice/decklink_enc.o] Error 1
> 20 errors generated.
> make: *** [libavdevice/decklink_dec.o] Error 1
> 
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
>   https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues
> 
> These open issues may also help:
> FFmpeg with decklink support installation failure https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/92
> Brewing custom ffmpeg but failure at metal execution https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/96
> opencv not working after homebrew-ffmpeg installation https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/93
> 
>  ~ % 
> ```
> 
> I have looked at the other github issues that are mentioned but none of them helped me fix this. Is this just me being stupid or does this solution no longer work?

This hack is unnecessary since auto-editor now ships with the proper FFmpeg.

**Comment by tophee** [comment]
OK, good to know. The reason  I thought this is still relevant is that when I try to run `auto-editor /some/mp4/file --export_to_final_cut_pro` it complains that `ffmpeg` could not be found (even though it is installed). I can run it from the same command prompt without problems. What's going wrong?
