### ISSUE TITLE
DLL amfrt64.dll failed to open

### ISSUE THREAD

**Issue by doggy516** [WyattBlue/auto-editor#228]
**What version are you running?** 
21w51a

**What went wrong**
i tried to do auto-editor and it didnt work
```
Paste the command you've tried. 
auto-editor C:\Users\fleur\Videos\mad.mov
```

**Describe what went wrong**
it gave me an error
```
Paste the terminal output here.
stderr: Input #0, rawvideo, from 'pipe:':
  Duration: N/A, bitrate: 1492992 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1920x1080, 1492992 kb/s, 60 tbr, 60 tbn, 60 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (h264_amf))
[h264_amf @ 000001ce0c5e2e40] DLL amfrt64.dll failed to open
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

stdout:
Error! FFmpeg Error!
```

**What conditions must be met for it to be wrong** 

**Does the example video work? (if applicable)**

**What's your platform? (if applicable)**
Run: `auto-editor --debug`
windows 10
```
Paste output here.
Python Version: 3.9.2 64-bit
Platform: Windows 10 amd64
FFmpeg path: C:\Users\fleur\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
FFmpeg version: 4.3
Auto-Editor version 21w51a
```

**What properties your input file(s)? (if applicable)**
You can use  `aeinfo ./path/to/video.mp4` or `ffmpeg -hide_banner -i ./path/to/video.mp4` to get standard info.

```
Paste output here.
- video tracks: 1
   - Track #0
     - codec: h264
     - fps: 60
     - resolution: 1920x1080 (16:9)
     - bitrate: 11524 kb/s
 - audio tracks: 1
   - Track #0
     - codec: aac
     - samplerate: 48000
     - bitrate: 195 kb/s
 - container:
   - duration: 00:09:36.12
   - bitrate: 11723 kb/s

```

**Comment by WyattBlue** [comment]
Are you using a headless version of Windows? I've seen that exact error message before in GitHub Actions running Windows.

**Comment by doggy516** [comment]
> How do i see if i am?

**Comment by WyattBlue** [comment]
headless means there's no GUI or any graphics capabilities. Headless versions are often used in servers and in CI/CL systems. You probably have the regular version of Windows.

I would recommend installing FFmpeg then using the `--my-ffmpeg` flag with the auto-editor command.

**Comment by doggy516** [comment]
Thanks it worked

**Comment by Sosokiller12** [comment]
i cant edit my videos type in ever and it gave me that errorstderr: Input #0, rawvideo, from 'pipe:':
  Duration: N/A, bitrate: 1492992 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1920x1080, 1492992 kb/s, 60 tbr, 60 tbn, 60 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (h264_amf))
[h264_amf @ 000001ce0c5e2e40] DLL amfrt64.dll failed to open
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

stdout:
Error! FFmpeg Error! and idk what to do to fix it

**Comment by Sosokiller12** [comment]
im confuse

**Comment by Sosokiller12** [comment]
if i download that dll where do i put it

**Comment by igavronski** [comment]
You might find this link helpful:

https://github.com/obsproject/obs-amd-encoder/issues/91

**Comment by Mipsters** [comment]
> Are you using a headless version of Windows? I've seen that exact error message before in GitHub Actions running Windows.

I don't think that's the issue, I had the same problem in my regular windows installation
it may be because of the h264

It was fixed for me when i copied my installation of ffmpeg instead of the one from auto-editor

this is a comparison of my installation of ffmpeg and the one bundled with auto-editor
[ffmpeg-compare.txt](https://github.com/WyattBlue/auto-editor/files/7834151/ffmpeg-compare.txt)

and a comparison of `ffmpeg.exe -encoders | find "264"`
[ffmpeg-encoders-compare.txt](https://github.com/WyattBlue/auto-editor/files/7834190/ffmpeg-encoders-compare.txt)

this is probably the same issue described in here:
https://johnnn.tech/q/ffmpeg-dll-amfrt64-dll-failed-to-open-on-windows-solved/

**Comment by WyattBlue** [comment]
I fixed this in 22w03a creating an FFmpeg that is static.

**Comment by allenpzx** [comment]
> headless means there's no GUI or any graphics capabilities. Headless versions are often used in servers and in CI/CL systems. You probably have the regular version of Windows.
> 
> I would recommend installing FFmpeg then using the `--my-ffmpeg` flag with the auto-editor command.

bro you save my time, thanks
