### ISSUE TITLE
Conversion failed

### ISSUE THREAD

**Issue by mlinaje** [WyattBlue/auto-editor#232]
### What's your platform?

```shell
Platform: Windows 10 amd64
FFmpeg path: C:\Users\usuario2\AppData\Local\Programs\Python\Python310\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
FFmpeg version: 4.3
Auto-Editor version 22w01a
```

### What did you try?

```shell
auto-editor '.\2022-01-28 12-24-42.mp4' -s 2 -v 1.1 -t 0.05
```

### Bug description

It seems that the bitrate and the resolution are detected according to auto-editor output, but the following error appears:

stderr: Input #0, rawvideo, from 'pipe:':
  Duration: N/A, bitrate: 622080 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1920x1080, 622080 kb/s, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (h264_amf))
[h264_amf @ 00000242c4dc2340] DLL amfrt64.dll failed to open
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

Error! FFmpeg Error!

### Comments

It's an OBS video I uploaded the original video (unedited) to https://www.youtube.com/watch?v=u2gerG2aDJs

**Comment by WyattBlue** [comment]
Your version of auto-editor is old. Upgrade auto-editor.

```
pip install auto-editor -U
```

**Comment by mlinaje** [comment]
Working like a charm ;-)
Excuse me @WyattBlue I didn't check the version, I just installed it from the PIP public repository after reinstalling my whole system, not form github.
Best!

**Comment by FlashlightET** [comment]
i have the latest version and im getting the same rror
