### ISSUE TITLE
Wrong cuts in latest version when exporting to premiere xml

### ISSUE THREAD

**Issue by BigB00st** [WyattBlue/auto-editor#234]
### What's your platform?

```shell

Python Version: 3.8.5 64-bit
Platform: Windows 10 amd64
FFmpeg path: D:\Libs\auto-editor-env\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
FFmpeg version: N-105325-g7512293cf9
Auto-Editor version 22w07a
```

### What did you try?

Load an exported premire xml, which resulted in cuts in wrong places.

### Bug description

I have used an old version of auto-editor (**21.40.1**) for a while. I always export to **premire** and then load the xml in sony vegas 17 (which works fine).
After upgrading to the latest version (**22.7.1**) the offset were bugged: I loaded it into vegas from the xml and the a audio tracks were cut in wrong places.
So I tried to use auto-editor to export as **mp4** in the same version (**22.7.1**), and the offsets were fine, the video was cut properly.
Then I downgraded to **21.40.1**, exported to **premire**, and it was cut exactly like it was cut for the **mp4** export in **22.7.1**.
So the bug is in exporting to **premire xml** in new versions.

[The good xml](https://ghostbin.com/DEEUW) (which resulted in valid cuts - version **21.40.1**).
[The bad xml](https://ghostbin.com/bRzrk) (which resulted in wrong cuts - version **22.7.1**).

Also, here is an [image](https://imgur.com/a/fjvvku0) of a wrong cut, above you can see the audio track of the **premire xml** exported veresion, below you can see the audio track from the **mp4** exported version. There is an unneccesary cut above.

### What properties your input file(s)? (if applicable)

```shell
auto-editor video.mp4 --cut_by_all_tracks --keep_tracks_seperate --margin 7 --no_open --export_to_premiere -o out.xml --silent_threshold 2%
```

**Comment by WyattBlue** [comment]
> 
> [The good xml](https://ghostbin.com/DEEUW) (which resulted in valid cuts - version **21.40.1**). 
> [The bad xml](https://ghostbin.com/rJ78H) (which resulted in wrong cuts - version **22.7.1**).
> 

I checked both of those files manually and with the diff tool and there is no difference. Perhaps one got duplicated by mistake?

**Comment by BigB00st** [comment]
My mistake, [here](https://ghostbin.com/bRzrk) is the one with the wrong cuts.

**Comment by shrikant2002** [comment]
Same for me when exporting to final cut any solution?

**Comment by WyattBlue** [comment]
See if the latest from `master` fixes it.

```
pip install git+https://github.com/WyattBlue/auto-editor.git
```

**Comment by BigB00st** [comment]
The cuts are now synced, thank you very much! Closing the issue.
