### ISSUE TITLE
Outputs video upside down

### ISSUE THREAD

**Issue by Aelerity** [WyattBlue/auto-editor#235]
### What's your platform?

```shell
Python Version: 3.10.2 64-bit
Platform: Windows 10 amd64
FFmpeg path: C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
FFmpeg version: N-105325-g7512293cf9
Auto-Editor version 22w07a
```

### What did you try?

```shell
auto-editor C:\Users\user\Downloads\video.MP4 -v 1.25
```

### Bug description

Video was cut as intended, but the video was upside down. Input video was right side up.

### What properties your input file(s)? (if applicable)

```shell
Finished. took 353.98 seconds (0:05:54)
```

**Comment by WyattBlue** [comment]
This should be fixed in the latest version. The latest copies the input video's metadata to the output, which should solve the problem.
