### ISSUE TITLE
"Something went wrong" when exporting file to -excs 

### ISSUE THREAD

**Issue by merakilia** [WyattBlue/auto-editor#237]
### What's your platform?

```shell
C:\Users\Billy_isbp>auto-editor --debug
Python Version: 3.10.2 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-105325-g7512293cf9
FFmpeg Path: C:\Users\Billy_isbp\AppData\Local\Programs\Python\Python310\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 22w09a
```

### What did you try?

```shell
C:\Users\Billy_isbp>auto-editor C:\Users\Billy_isbp\Videos\mobile_legend3.mp4 -excs
Error! The file C:\Users\Billy_isbp\Videos\mobile_legend3_ALTERED-0.mp4 was not created.

Something went wrong!
Create a bug report at:
  https://github.com/WyattBlue/auto-editor/issues/
```

### Bug description

So i want to export the file to filmora, hence i need to export with -excs. but when i tried it saids something went wrong.

### What properties your input file(s)? (if applicable)

```shell
C:\Users\Billy_isbp>auto-editor C:\Users\Billy_isbp\Videos\mobile_legend3.mp4 -excs
```

**Comment by WyattBlue** [comment]
Can you share the output of:

```
auto-editor C:\Users\Billy_isbp\Videos\mobile_legend3.mp4 --preview
```

**Comment by merakilia** [comment]
> Can you share the output of:
> 
> ```
> auto-editor C:\Users\Billy_isbp\Videos\mobile_legend3.mp4 --preview
> ```

C:\Users\Billy_isbp>auto-editor C:\Users\Billy_isbp\Videos\kimak\kimak.mp4 --preview

length:
 - change: (0:40:54) 100% -> (0:11:07) 27.19%
 - diff: (-0:29:47) -72.81%
clips: 711
 - smallest: 0.2 secs (0:00:00)
 - largest: 4.7 secs (0:00:05)
 - average: 0.9 secs (0:00:01)
cuts: 712
 - smallest: 0.1 secs (0:00:00)
 - largest: 26.9 secs (0:00:27)
 - average: 2.5 secs (0:00:02)

**Comment by WyattBlue** [comment]
Does `22w11a` work?
