### ISSUE TITLE
When inputting a folder full of videos it will convert every video file in that video

### ISSUE THREAD

**Issue by Aelerity** [WyattBlue/auto-editor#238]
Descript what feature/improvement you would like here.
-When inputting a folder full of videos it will convert every video file in that video

Descript how you would use it.
instead of saying "auto-editor C:\Users\user\Videos\1.mp4", "auto-editor C:\Users\user\Videos\2.mp4", ","auto-editor C:\Users\user\Videos\3.mp4" you could just say "auto-editor C:\Users\user\Videos" and it would convert every video file in that folder one after another. Adding a setting like -v 1.25 would apply to every converted video in the folder.

Make sure that it is something that YOU need, not that just seems useful.

(Make sure you're using the latest version)

**Comment by WyattBlue** [comment]
This was supported in older versions of auto-editor, but I deliberately removed it in version 21w49a because you can easily use shell syntax. 

From the release notes:

> You can no longer use folders as inputs. Supporting this type of input was the cause of a lot of complexity and can easily be substituted with the more powerful. GLOB patterns. With glob patterns, you can select files that only end in .mp4 or start with a certain word. The best part about glob patterns is you can use them with any program instead of just auto-editor.

```shell
# Not Supported
auto-editor my_videos

# Do this instead
auto-editor my_videos/*

# Or
auto-editor my_video/*.mp4
```
