### ISSUE TITLE
Allow multiple tracks when using `--combine-files`

### ISSUE THREAD

**Issue by yigexuezha** [WyattBlue/auto-editor#241]
When the video has more than one track, `--combine-files` output only the first, which causes this error as displayed below.

```
auto-editor example.mp4 example2.mp4 --combine-files --keep-tracks-separate --edit audio:stream=1

Error! Audio stream '1' does not exist.
```

**Comment by WyattBlue** [comment]
This is now fixed in master. Will eventually put into release.
