### ISSUE TITLE
How to use the better audio encoder ?

### ISSUE THREAD

**Issue by yigexuezha** [WyattBlue/auto-editor#242]
How to use the better audio encoder ?
In the same audio bitrate , I can hear the altered audio loss of sound quality.(more harsh)
So , I think the encoder is not good . ( I used ACC)

**Comment by WyattBlue** [comment]
You can use the `--audio-codec` option or its alias `-c:a` to set a different audio encoder.

AAC is an excellent audio codec, it should not be the cause of the issue, although you can try using the opus codec.
