### ISSUE TITLE
Option to set minimum clip size when cut is applied

### ISSUE THREAD

**Issue by shrikant2002** [WyattBlue/auto-editor#243]
This is really a great program and I enjoy using it. Many of the times when I apply cuts on my clip the program will keep a small duration of clips when exporting the project in fcpxml like this
![Screen Shot 2022-03-13 at 5 17 02 PM](https://user-images.githubusercontent.com/1228193/158058052-182a5384-3ba6-480b-b7e4-7b674b0b35b6.png)

deleting this clips is a tedious task again I wonder if we can set the minimum clip size to include in the final project and that would be again an awesome feature for people in need.

**Comment by WyattBlue** [comment]
There's already an option for this:

```
auto-editor --min-clip-length -h 
  --min-clip-length, -mclip
    Set the minimum length a clip can be. If a clip is too short, cut it.

    type: frame_type
    nargs: 1
    default: 3
    range: 0 to Infinity
```

**Comment by shrikant2002** [comment]
Thanks where can I see all the options available in this program?

**Comment by WyattBlue** [comment]
You can just run:
```
auto-editor --help
```

**Comment by shrikant2002** [comment]
I tried this -mcut option but it does not work for manual cuts

**Comment by WyattBlue** [comment]
> I tried this -mcut option but it does not work for manual cuts

Yeah, if it's manual, you can adjust the cut.
