### ISSUE TITLE
Process silent_cut after processing manual_cut while exporting fcpxml

### ISSUE THREAD

**Issue by shrikant2002** [WyattBlue/auto-editor#244]
How can I process my manual cuts first and then remove silence and export the file as fcpxml while maintaining all the edit points movable in final cut?

I tried using --cut-out 15s,20s & --silent-threshold 3% at the same time
but the auto-editor will always perform silent_cut first then manual cut thus moving my cut position to a different location.

**Comment by WyattBlue** [comment]
1. The export mode doesn't change how cutting works.
1. It doesn't matter what order the cuts are applied in. It's just settings some ones to zeroes.
