### ISSUE TITLE
Desync in FinalCut Pro with VFR

### ISSUE THREAD

**Issue by kedar264** [WyattBlue/auto-editor#245]
### What's your platform?

```shell
Python Version: 3.9.7 64-bit
Platform: Darwin 21.2.0 x86_64
FFmpeg path: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/auto_editor/ffmpeg/Darwin/ffmpeg
FFmpeg version: 6dc3e86-5.0
Auto-Editor version 22w06a
```

### Bug description

i'm working with longer (90+)minutes video, and i am getting unnecessary silence gap at the start of each clip ,interestingly  duration of each gap is linearly increasing for each clip as the timestamp progresses

i also tried just the  --export-to-final-cut-pro
![Screenshot 2022-03-16 at 7 45 22 PM](https://user-images.githubusercontent.com/10330492/158610635-109c3c78-ee68-49f1-9c50-59e5d81baa40.png)
![Screenshot 2022-03-16 at 7 55 42 PM](https://user-images.githubusercontent.com/10330492/158612599-26bd61fe-d292-4ad7-a154-ab44e7b15536.png)

additionally i have tried following--frame-margin 1,-12 
 --frame-margin 8
--silent-threshold 4%

but still getting unnecessary silence gap at the start of each clip

### What command did you use

```shell
auto-editor /Volumes/BX500/OBS\ 2TB/Playstation\ phone/psphone\ ae.mp4 --export-to-final-cut-pro
```

### What properties does your input video have?

```shell
file: /Volumes/BX500/OBS 2TB/Playstation phone/psphone ae.mp4
 - video tracks: 1
   - Track #0
     - codec: h264
     - pix_fmt: yuv420p
     - time_base: 1/15360
     - fps: 60
     - resolution: 1920x1080 (16:9)
     - bitrate: 2445 kb/s
 - audio tracks: 1
   - Track #0
     - codec: aac
     - samplerate: 48000
     - bitrate: 159 kb/s
 - container:
   - duration: 01:34:15.28
   - bitrate: 2618 kb/s
```

**Comment by WyattBlue** [comment]
See if this is fixed in the latest version, 22w12a

**Comment by kedar264** [comment]
Just checked it ,same problems is there in your new version 22w12a
as per my judgements i found that this issue is related to the video having VFR property looks like VFR causes that desync  ,but when i converted that same VFR video to CFR using handbrake and then put it into auto-editor it clearly worked and desync is gone.

**Comment by petermg** [comment]
> Just checked it ,same problems is there in your new version 22w12a as per my judgements i found that this issue is related to the video having VFR property ,looks like VFR causes that desync ,but when i converted that same VFR video to CFR using handbrake and then put it into auto-editor it clearly worked and desync is gone. if the video is CFR it works with all versions of auto-editor without any issues
> 
> handbrake only worked with slow cpu rendering which takes couple of hours ,i hope you can come up with gpu rendering solutions,Thanks

I've got a GPU encoding version here:
https://github.com/petermg/auto-editor
It's very fast. By default it requires a compatible Nvidia GPU encoder.

**Comment by WyattBlue** [comment]
exporting VFR videos to editors is not supported so I don't care if de-syncing is happening.
