### ISSUE TITLE
Several bugs

### ISSUE THREAD

**Issue by totallyprinx** [WyattBlue/auto-editor#246]
### What's your platform?

```shell
Python Version: 3.10.2 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-105325-g7512293cf9
FFmpeg Path: D:\Python3\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 22w09a
```

### Bug description

[auto_aresample_0 @ 00000286f61460c0] [SWR @ 00000286f61d7180] Input channel layout '10 channels (FL+FR+FC+LFE+BL+BR+FLC+FRC+BC+SL)' is not supported
[auto_aresample_0 @ 00000286f61460c0] Failed to configure output pad on auto_aresample_0
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #4:0
Error! The file D:\OBSrecord\2022-03-16_17-16-24_ALTERED.mp4 was not created.

### What command did you use

```shell
C:\Users\phoen>auto-editor D:\OBSrecord\2022-03-16_17-16-24.mp4
```

### What properties does your input video have?

```shell
file: D:\OBSrecord\2022-03-16_17-16-24.mp4
 - video tracks: 1
   - Track #0
     - codec: h264
     - pix_fmt: yuv420p
     - time_base: 1/90000
     - fps: 29.97
     - resolution: 1280x720 (16:9)
     - bitrate: 5997 kb/s
     - lang: und
 - audio tracks: 5
   - Track #0
     - codec: aac
     - samplerate: 48000
     - bitrate: 134 kb/s
     - lang: und
   - Track #1
     - codec: aac
     - samplerate: 48000
     - bitrate: 2 kb/s
     - lang: und
   - Track #2
     - codec: aac
     - samplerate: 48000
     - bitrate: 134 kb/s
     - lang: und
   - Track #3
     - codec: aac
     - samplerate: 48000
     - bitrate: 134 kb/s
     - lang: und
   - Track #4
     - codec: aac
     - samplerate: 48000
     - bitrate: 134 kb/s
     - lang: und
 - container:
   - duration: 00:44:25.13
   - bitrate: 6569 kb/s
```

### Comments

Same error occurred when attempting to use auto-editor on the same video as a .mkv file

**Comment by WyattBlue** [comment]
Does adding `--keep-tracks-seperate` make a correct video?

**Comment by totallyprinx** [comment]
Yes it did, but this popped up as soon as it finished.

`Finished. took 680.77 seconds (0:11:21)
Traceback (most recent call last):
  File "D:\Python3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Python3\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
  File "D:\Python3\lib\site-packages\auto_editor\__main__.py", line 404, in main
    main_loop(input_list, ffmpeg, args, segments, log)
  File "D:\Python3\lib\site-packages\auto_editor\__main__.py", line 401, in main_loop
    usefulfunctions.open_with_system_default(output_path, log)
  File "D:\Python3\lib\site-packages\auto_editor\utils\func.py", line 61, in open_with_system_default
    startfile(path)
OSError: [WinError -2147221003] Application not found: 'D:\\OBSrecord\\2022-03-16_17-16-24_ALTERED.mkv'`

**Comment by igavronski** [comment]
@totallyprinx what happens if you use the ` --no-open` option?

**Comment by totallyprinx** [comment]
I used the --no-open option and it resulted in an error.

[auto_aresample_0 @ 000002691dc862c0] [SWR @ 000002691dd17180] Input channel layout '10 channels (FL+FR+FC+LFE+BL+BR+FLC+FRC+BC+SL)' is not supported
[auto_aresample_0 @ 000002691dc862c0] Failed to configure output pad on auto_aresample_0
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #4:0

In terms of using --keep-tracks-separate, it's been successful most of the time. The previous error code I received hasn't occurred again.
