### ISSUE TITLE
Progressbar for analysis

### ISSUE THREAD

**Issue by FlashlightET** [WyattBlue/auto-editor#247]
A simple progressbar for analysis.

it's hard to tell when it'll be done and it would be nice to have a progressbar for that. it's been analyzing for minutes and i don't even know if its even at 50% yet or not

**Comment by FlashlightET** [comment]
And then after all that waiting, there's an error.

**Comment by WyattBlue** [comment]
Auto-Editor already shows a progress bar during analysis for both audio and motion since `22w09a`
