### ISSUE TITLE
Ability to split files

### ISSUE THREAD

**Issue by wisdomtooth** [WyattBlue/auto-editor#249]
Can I use auto-editor to recreate the cuts (splits) in a video's source project? What I mean is: identify image discontinuities (not "motion" exactly), and split the video into segments there.

A lot of what I do is clipping primary work and assembling into secondary work, and often finding myself doing that manually. Auto-editor seems almost there in terms of what I need, but I'm just not sure how to make it do that (or whether it does at all).

Cheers.

**Comment by WyattBlue** [comment]
No.
