### ISSUE TITLE
Reintroduce `--force-fps-to` or add an option to change default fps

### ISSUE THREAD

**Issue by anosanstudio** [WyattBlue/auto-editor#250]
I use auto-editor to make my youtube video for a long time. I noticed auto-editor removed `--force-fps-to` recently. I hope that it can come back or there might be an alternative to do the same thing?

I make youtube video by using audio files and video files separately. I use auto-editor to edit my wav file first and then I import timeline, then import video and image media. But some Non-Linear Editors (like DaVinci Resolve) cannot change the project fps after you import your timeline or media files.

Auto-Editor's default fps setting is `30`. I didn't care in the past because I could change fps by using `--force-fps-to`. But after the update, I didn't have an easy solution. If I import timeline first, the video media fps will not be the same as project's fps. Same thing happened when I import video media first. This forces me to use video media that is 30 fps.

I hope that `--force-fps-to` can come back or maybe we could have an alternative option.

**Comment by WyattBlue** [comment]
22w22a release adds the `--frame-rate` option, which edits xml fps.

**Comment by anosanstudio** [comment]
Thanks! It works.
