### ISSUE TITLE
Error! The file output.mp4 was not created. Perhaps --extras is the source.

### ISSUE THREAD

**Issue by hunterhogan** [WyattBlue/auto-editor#251]
### What's your platform?

```shell
Python Version: 3.8.6 64-bit
Platform: Windows 7 amd64
FFmpeg Version: N-105325-g7512293cf9
FFmpeg Path: C:\apps\auto-editor\venv\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 22w12a
```

### Bug description

1. At a command prompt, activate the virtual environment for auto-editor.
2. Run the command below.
3. For me, auto-editor allows immediately displays in red, `At least one output file must be specified`, but always continues.
4. Auto-Editor analyzed the motion: I did not see an error or problem. 
5. After the analysis, auto-editor indicated it was creating the new file.

I happen to have two screenshots that _might_ be useful. Two days ago, I ran auto-editor on a different file that has the same properties as the current file, but I did not use the --extras option. Everything else was the same. Using [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer), I looked at the FFmpeg instance called by auto-editor. This is what I captured.

![auto-editor call to ffmpeg with all arguments 2022-3-23](https://user-images.githubusercontent.com/2958419/160199406-5ad678de-c62a-451e-a74d-57c75beb14d0.png)

Today, after auto-editor indicated it was creating the new file, I took a screenshot. 

![auto-editor call to ffmpeg with all arguments 2022-3-25](https://user-images.githubusercontent.com/2958419/160199566-f3a5c98f-53a4-4472-8c08-8554ae4048b6.png)

I was a little surprised that the only difference is the temp path, but I don't know Python, I barely understand FFmpeg, and auto-editor is still a magic box to me.

6. Auto-Editor progressed to at least 98% file creation without errors. My computer is horribly slow, so I don't watch the progress bar. (See, for example, this file)
![auto-editor 7 hours for 20 min video](https://user-images.githubusercontent.com/2958419/160200051-ccefd4da-ce5e-49d0-83d8-24974ae28c29.png)
7. When my CPU usage dropped, I went back to auto-editor expecting to see the completed file, but the only information was

>Error! The file booster1_motion_cut.mp4 was not created.
>
> Something went wrong!
> Create a bug report at:
>   https://github.com/WyattBlue/auto-editor/issues/  

8. If there is a log file or other additional information about the error, I don't know where it is. I looked for a log file in the local directory: none. I searched in C:\apps\auto-editor /s for any files modified today: none. 

### What command did you use

```shell
auto-editor booster1.mp4 --motion-threshold 0.03% --edit-based-on motion --no-open --frame-margin 8 --extras "-video_track_timescale 90k -filter_complex setpts=PTS-STARTPTS" --output-file booster1_motion_cut.mp4
```

### What properties does your input video have?

```shell
file: booster1.mp4
 - video tracks: 1
   - Track #0
     - codec: h264
     - pix_fmt: yuv420p
     - resolution: 1080x1920 (9:16)
     - bitrate: 1025 kb/s
     - lang: eng
 - container:
   - duration: 00:03:31.28
   - bitrate: 1040 kb/s
```

### Comments

Thanks!

**Comment by hunterhogan** [comment]
### Probably unrelated: progress-bar skipping during file-creation
For me, when auto-editor is using FFmpeg to create the new file, the progress bar will _sometimes_ skip back to a smaller percentage, then quickly count up to the current status. I was originally worried it was stuck in a loop, so I recorded the screen. I observed that the progress bar always went higher than the last round before it would skip back to a smaller number, so I assumed it was only a cosmetic issue. I made a 37-second GIF from the screen recording to show you, for example, the progress bar skipping from 31.2% back to 5.3%.

![auto-editor progress bar](https://user-images.githubusercontent.com/2958419/160207882-02c89054-b374-4c28-a104-a00a685ff110.gif)

### Without --extras, no errors
I ran auto-editor again, and the only change I made was removing the --extras option. No errors and the output file was created.

> (venv) C:\Users\Blaze-X120e\Videos\Two Dots>auto-editor booster1.mp4 --motion-threshold 0.03% --edit-based-on motion --no-open --frame-margin 8 --output-file booster1_motion_cut.mp4
> At least one output file must be specified
> Finished. took 1086.17 seconds (0:18:06)

### `-video_track_timescale 90k`
I was trying to use `-video_track_timescale 90k` because in later steps, if I use FFmpeg's concat demuxer and the "tbn" of the videos do not match, then I get many warnings of "Non-monotonous DTS in output stream" and the resulting file is unplayable. The other files have 90k tbn, so I tried to force the `--output-file` to match: it has worked for me in other situations.

The original file properties

> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'booster1.mp4':
>   Duration: 00:03:31.28, start: 0.000000, bitrate: 1040 kb/s
>   Stream #0:0\[0x1\](eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt470bg/smpte170m, progressive), 1080x1920, 1025 kb/s, SAR 1:1 DAR 9:16, 29.72 fps, 90k tbr, 90k tbn (default)

The `--output-file` properties

> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'booster1_motion_cut.mp4':
>   Duration: 00:01:22.67, start: 0.000000, bitrate: 1295 kb/s
>   Stream #0:0\[0x1\](eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(progressive), 1080x1920, 1294 kb/s, 30 fps, 30 tbr, 15360 tbn (default)

**Comment by WyattBlue** [comment]
You can't use "-filter_complex setpts=PTS-STARTPTS" in the `--extras` because the command is copying streams with `-map` or as ffmpeg explains it:

```
Streamcopy requested for output stream 0:0, which is fed from a complex filtergraph. Filtering and streamcopy cannot be used together.
```

It's better to fix video issues with a separate ffmpeg command and then use auto-editor on the fixed file instead.

Also, there will always be an `--extras` value that causes an ffmpeg error. Fixing that is out of scope for this project so I'm closing this issue.
