### ISSUE TITLE
Create analysis file for faster editing if not satisfied with the result

### ISSUE THREAD

**Issue by petermg** [WyattBlue/auto-editor#254]
Descript what feature/improvement you would like here.
Can you make it so that Auto-Editor creates an analysis or statics file when it analyzes the video file for audio volume threshold or motion so that if the user doesn't like the results of the set thresholds they can re-run Auto-Editor on the file using the analysis or stats file so that it doesn't have to analyze the video file again? It takes a long time to analyze a video for motion so I'm thinking only make an analysis or statistics file based on the edit method selected.  Maybe just make it so that Auto-Editor looks for an analysis or statistics file by default that's named after the video file "video.mp4.stats" or something like that and if it doesn't find one it analyzes the video file and creates the analysis or statistics file. This would be so useful for running additional passes on the video file without having to wait for the file to be analyzed again every time, especially with motion it would save a ton of time. Thanks!

**Comment by WyattBlue** [comment]
Done

**Comment by petermg** [comment]
Nice.
