### ISSUE TITLE
Discarded EDL export

### ISSUE THREAD

**Issue by chapmanjacobd** [WyattBlue/auto-editor#259]
**Descript what feature/improvement you would like here.**

If I used this in a professional context I would like to see the clips that were discarded (cut out) either to double check that nothing is missing or for getting known un-used shots for b-roll.

For example with `--export premiere` both a `video.xml` and a `video-discarded.xml` is created (or `video.b-roll.xml`)

**Descript how you would use it.**
This could be the default for non-video exports or it could be one of the following flags:  

- `--export premiere --b-roll` 
- `--export premiere --with-b-roll`
- `--export premiere --discarded` 
- `--export premiere --with-discarded`
- `--export premiere --with-discarded-edl`

**Comment by WyattBlue** [comment]
I'm going to reject this, because you can use `--video-speed 99999 --silent-speed 1` to get the unused shots.
