### ISSUE TITLE
The audio and video is not sync

### ISSUE THREAD

**Issue by flt6** [WyattBlue/auto-editor#261]
### What's your platform?

```shell
Platform:  Windows 10.
Version:   Release 22w16a.
```

### Bug description

When "-v" is used for my video, the output video will become audio and video not synchro. I also found if I cut it, the problem will disappear.
[20220424.7z](https://flt.lanzouh.com/ivbok03p3pda) includes an example video and its effect. (In Chinese)
[output file](https://flt.lanzouh.com/iQL3m03p5yve) when enabled "--debug".

### What command did you use

```shell
python -m auto_editor --debug math.mp4 -v 1.5 -o opt.mp4
```

### What properties does your input video have?

```shell
λ python -m auto_editor info math.mp4

file: math.mp4
 - video tracks: 1
   - Track #0
     - codec: h264
     - pix_fmt: yuv420p
     - fps: 20.0
     - resolution: 1280x720 (16:9)
     - bitrate: 49 kb/s
     - lang: und
 - audio tracks: 1
   - Track #0
     - codec: aac
     - samplerate: 44100
     - bitrate: 87 kb/s
     - lang: und
 - container:
   - duration: 00:42:53.30
   - bitrate: 144 kb/s
```

### Comments

The following is some in output of command.
Debug: Keyframe 12000 6144000
Debug: Skipped **-126** frames
Debug: Keyframe 12250 6272000

At first I think this is the reason and I tried to fix it, but I found as long as I execute the command without "-v 1.5", it also print data like that, but the output is OK.

**Comment by flt6** [comment]
I found It may be the same problem as [#256](https://github.com/WyattBlue/auto-editor/issues/256)

**Comment by flt6** [comment]
After more tests, I found "-v" is not need for the desync, and even if I exported the data to Premiere, it is also desync.

**Comment by WyattBlue** [comment]
Try using `--no-seek` in the latest release.

**Comment by flt6** [comment]
I've tested it, but it doesn't work in the latest version([22w18a](https://github.com/WyattBlue/auto-editor/commit/709881e18b9f0dab3a975ab32229e114dac2d6e3))
