### ISSUE TITLE
This edit SIGNIFICANTLY increases GPU encoding performance!

### ISSUE THREAD

**Issue by petermg** [WyattBlue/auto-editor#262]
I found a way to SIGNIFICANTLY improve encoding while using the GPU, and I do NOT mean just by using the GPU. I mean including the GPU codecs in the ALLOWED codecs in utils/encoder.py

auto-editor testing.mp4
CPU time
0:02:03

auto-editor -c:v hevc_nvenc testing.mp4
GPU time with unmodified encoder.py
0:01:32

auto-editor -c:v hevc_nvenc testing.mp4
GPU time with updated encoder.py
0:00:58

modified encoder.py increases GPU encoding performance by 37%

I added the following into encoder.py after line 76 to achieve this, and also used a version of ffmpeg with GPU encoding enabled. Overall more than doubling my encoding speed when compared to CPU encoding on default settings.

```
    "hevc_nvenc": {
        "pix_fmt": {
            "yuv420p",
            "nv12",
            "p010le",
            "yuv444p",
            "p016le",
            "yuv444p16le",
            "bgr0",
            "rgb0",
            "gbrp",
            "gbrp16le",
            "cuda",
            "d3d11",
        },
    },
    "hevc_amf": {
        "pix_fmt": {
            "nv12",
            "yuv420p",
            "d3d11",
            "dxva2_vld",
        },
    },
    "h264_nvenc": {
        "pix_fmt": {"yuv420p", "nv12", "p010le", "yuv444p", "p016le", "yuv444p16le", "bgr0", "rgb0", "gbrp", "gbrp16le", "cuda", "d3d11",},
    },
    "h264_amf": {
        "pix_fmt": {"nv12", "yuv420p", "d3d11", "dxva2_vld",},
    },
```

I have attached the modified encoder.py file.
[encoder.zip](https://github.com/WyattBlue/auto-editor/files/8550144/encoder.zip)

**Comment by WyattBlue** [comment]
I have added those encoders in the encoder.py file.
