### ISSUE TITLE
On M1: Can't find ffmpeg

### ISSUE THREAD

**Issue by lxyer** [WyattBlue/auto-editor#263]
### What's your platform?

```shell
auto-editor --debug
Error! No ffmpeg found, download via homebrew or restore the included binary.
```

### Bug description

Error! No ffmpeg found, download via homebrew or restore the included binary.

### What command did you use

```shell
auto-editor /Users/lxyer/Desktop/test.mp4
```

### Comments

python3
Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
<img width="586" alt="image" src="https://user-images.githubusercontent.com/17336748/165049179-33ccae6c-2b2e-4859-a7ec-0b4ca1caedd7.png">

**Comment by lxyer** [comment]
ffmpeg -version
ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
built with Apple clang version 13.1.6 (clang-1316.0.21.2.3)
configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.0.1-with-options_1 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --enable-opencl --enable-audiotoolbox --enable-videotoolbox --enable-neon --disable-htmlpages --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfdk-aac --enable-libgme --enable-libgsm --enable-libmodplug --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librist --enable-librsvg --enable-librtmp --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtesseract --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libwebp --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-openssl --enable-nonfree --enable-decklink --extra-cflags=-I/opt/homebrew/include --extra-ldflags=-L/opt/homebrew/include --enable-libjack --enable-indev=jack --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb
libavutil      57. 17.100 / 57. 17.100
libavcodec     59. 18.100 / 59. 18.100
libavformat    59. 16.100 / 59. 16.100
libavdevice    59.  4.100 / 59.  4.100
libavfilter     8. 24.100 /  8. 24.100
libswscale      6.  4.100 /  6.  4.100
libswresample   4.  3.100 /  4.  3.100
libpostproc    56.  3.100 / 56.  3.100

**Comment by WyattBlue** [comment]
What's in `/usr/local/lib/python3.10/site-packages/auto_editor/` and does `ffmpeg/Darwin/ffmpeg` exist in there?

**Comment by lxyer** [comment]
Add --ffmpeg-location '/opt/homebrew/Cellar/ffmpeg/5.0.1-with-options_1/bin/ffmpeg' ,auto-editor can work.

**Comment by lxyer** [comment]
> What's in `/usr/local/lib/python3.10/site-packages/auto_editor/` and does `ffmpeg/Darwin/ffmpeg` exist in there?

auto-editor /Users/lxyer/Desktop/test.mp4 --ffmpeg-location '/opt/homebrew/Cellar/ffmpeg/5.0.1-with-options_1/bin/ffmpeg' --edit 'audio:threshold=3% or motion:threshold=0.02%' 


Traceback (most recent call last):                                                                              |    0%  ETA 05:01 PM
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/auto-editor", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/__main__.py", line 473, in main
    main_loop(input_list, ffmpeg, args, log)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/__main__.py", line 453, in main_loop
    cuts, output_path = edit_media(i, inp, ffmpeg, args, progress, TEMP, log)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/edit.py", line 146, in edit_media
    chunks = get_chunks(inp, args, progress, temp, log)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/method.py", line 263, in get_chunks
    has_loud = get_has_loud(args.edit_based_on, inp, progress, temp, log, args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/method.py", line 209, in get_has_loud
    stream_data = get_stream_data(method, attrs, args, inp, progress, temp, log)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/method.py", line 103, in get_stream_data
    return get_audio_list(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/method.py", line 53, in get_audio_list
    audio_list = audio_detection(audio_samples, sample_rate, fps, progress)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/auto_editor/analyze/audio.py", line 38, in audio_detection
    threshold_list[i] = get_max_volume(audio_samples[start:end]) / max_volume
ZeroDivisionError: float division by zero

**Comment by lxyer** [comment]
I can not use audio and motion thresholds  toggled independently,

auto-editor /Users/lxyer/Desktop/test.mp4 --ffmpeg-location '/opt/homebrew/Cellar/ffmpeg/5.0.1-with-options_1/bin/ffmpeg' --edit 'audio:threshold=3% or motion:threshold=0.02%'  --export final-cut-pro

**Comment by WyattBlue** [comment]
Oh wait, you're using the m1 clip, so you wouldn't have an included binary. Is `ffmpeg` alone working on the PATH?

**Comment by lxyer** [comment]
### yes,I can use 'ffmpeg -version'
ffmpeg -version
ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
built with Apple clang version 13.1.6 (clang-1316.0.21.2.3)
configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.0.1-with-options_1 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --enable-opencl --enable-audiotoolbox --enable-videotoolbox --enable-neon --disable-htmlpages --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfdk-aac --enable-libgme --enable-libgsm --enable-libmodplug --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librist --enable-librsvg --enable-librtmp --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtesseract --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libwebp --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-openssl --enable-nonfree --enable-decklink --extra-cflags=-I/opt/homebrew/include --extra-ldflags=-L/opt/homebrew/include --enable-libjack --enable-indev=jack --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb
libavutil 57. 17.100 / 57. 17.100
libavcodec 59. 18.100 / 59. 18.100
libavformat 59. 16.100 / 59. 16.100
libavdevice 59. 4.100 / 59. 4.100
libavfilter 8. 24.100 / 8. 24.100
libswscale 6. 4.100 / 6. 4.100
libswresample 4. 3.100 / 4. 3.100
libpostproc 56. 3.100 / 56. 3.100

**Comment by WyattBlue** [comment]
Fixed in master brach.
