### ISSUE TITLE
[Windows] ffmpeg libopenh264.dll not found

### ISSUE THREAD

**Issue by idMysteries** [WyattBlue/auto-editor#265]
The "built-in" ffmpeg in auto-editor began to give this error after updating. The "--my-ffmpeg" command fixes the error.
```
\Python38\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
```

**Comment by WyattBlue** [comment]
Does `\Python38\Lib\site-packages\auto_editor\ffmpeg\Windows\libopenh264.dll` exist?

**Comment by idMysteries** [comment]
> Does `\Python38\Lib\site-packages\auto_editor\ffmpeg\Windows\libopenh264.dll` exist?

No

**Comment by WyattBlue** [comment]
Re-install auto-editor, check that windows defender isn't deleting that file.

**Comment by idMysteries** [comment]
I have already reinstalled it twice. I remember it seems there used to be this dll, and after the update it disappeared.
I don't have any "defenders"

**Comment by idMysteries** [comment]
Hmm
```
Collecting auto-editor
  Using cached auto_editor-22.16.1-py3-none-win_amd64.whl (10.1 MB)
```

**Comment by WyattBlue** [comment]
I forgot to include the ddl in the datafiles in setup, my bad. This will be fixed in the next release.

**Comment by idMysteries** [comment]
I used "pip download auto-editor" now.
auto_editor-22.16.1-py3-none-win_amd64.whl does not have this dll

**Comment by idMysteries** [comment]
Oh, thanks... OK

**Comment by idMysteries** [comment]
Here we go again...
