### ISSUE TITLE
I want to reduce the video with no sound and still picture, can I do it?

### ISSUE THREAD

**Issue by lxyer** [WyattBlue/auto-editor#266]
--edit 'audio:threshold=3% or motion:threshold=6%' 
### Can change 'or' to 'and'?does it work?
Our videos are sometimes being explained with voice and sometimes demonstrated on screen (when there is no sound), and we need to keep both types of videos.

**Comment by lxyer** [comment]
I find "and", "or", "xor" in code,It seems this is supported.

**Comment by WyattBlue** [comment]
Yes, auto-editor supports the `or`, `and` and `xor` logical operators.
