### ISSUE TITLE
Support for Intel Quicksync improve encoding by 33% (on supported hardware)

### ISSUE THREAD

**Issue by petermg** [WyattBlue/auto-editor#267]
When adding the Intel Quicksync encoders to 'encoder.py' (i.e. the list of allowed encoders), rendering was sped up by 33% according to a test done by a user in the discord server who asked for this and I added it to my fork. He processed a 5 minute video, without this code it took 300 seconds. With this code it took 200, as reported by him. I added the following lines to the 'encoder.py' file.
```
    "hevc_qsv": {
        "pix_fmt": {
            "nv12",
            "p010le",
            "yuyv422",
            "y210le",
            "qsv",
            "bgra",
            "x2rgb10le",
        },
    },
    "h264_qsv": {
        "pix_fmt": {
            "nv12",
            "p010le",
            "qsv",
        },
```

I have attached a copy of this updated file.
[encoder.zip](https://github.com/WyattBlue/auto-editor/files/8555092/encoder.zip)
.

**Comment by WyattBlue** [comment]
I have added those encoders. In the future, you should make a pull request so I can apply these changes with one click.
