### ISSUE TITLE
Feature Request: Save the "under-threshold" sections

### ISSUE THREAD

**Issue by hmijail** [WyattBlue/auto-editor#271]
This is another way to try to solve the same problem described in #270, and possibly easier.

I have long videos in which I want to remove silences but I don't know what silence threshold is adequate for them. If I could save the video that is cut because it's under the threshold, this resulting video should be relatively short and easy to check for sanity.

**Comment by WyattBlue** [comment]
You can see what auto-editor with this command:

```
auto-editor file.mp4 --video-speed 99999 --silent-speed 1
```
