### ISSUE TITLE
XML file Damage for Premiere

### ISSUE THREAD

**Issue by BenLorenzoDev** [WyattBlue/auto-editor#272]
### What's your platform?

```shell
Python Version: 3.10.4 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-105325-g7512293cf9
FFmpeg Path: C:\Users\User\AppData\Local\Programs\Python\Python310\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 22w17a
```

### Bug description

I used the command, auto-editor my_video.mp4 --export premiere, for me to get an XML file and it successfully went thru. But when I imported the XML file in Premiere Pro it shows an error that the file is damaged. Please see the screenshot attached.
![error import xml](https://user-images.githubusercontent.com/23088786/166151069-296c498c-d5c3-4410-b8f9-9d5f1e1eade5.png)

### What command did you use

```shell
auto-editor my_video.mp4 --export premiere
```

### What properties does your input video have?

```shell
- video:
   - track 0:
     - codec: h264
     - pix_fmt: yuvj420p
     - fps: 59.94
     - timebase: 1/180000
     - resolution: 1920x1080
     - aspect ratio: 16:9
     - bitrate: 30137 kb/s
     - lang: eng
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 48000
     - bitrate: 128 kb/s
     - lang: eng
 - container:
   - duration: 00:00:33.35
   - bitrate: 30513 kb/s
```

**Comment by WyattBlue** [comment]
Can you send the XML file?

**Comment by BenLorenzoDev** [comment]
> 

sure, 
[Damaged XML for Premiere.zip](https://github.com/WyattBlue/auto-editor/files/8599160/Damaged.XML.for.Premiere.zip)

**Comment by WyattBlue** [comment]
Nothing seems wrong, so uhh, don't care?

Sidenote: I hate these stupid vague Premiere Pro errors. the XML is structured correctly, it probably doesn't like how the file url is encoded, but it sure won't say that!
