### ISSUE TITLE
GUI Request

### ISSUE THREAD

**Issue by oc7opu5** [WyattBlue/auto-editor#273]
Hi, thank you for this awesome tool. It's really super powerful and fast. What I miss here is a GUI. is there any plan for a GUI for Windows? that would be great.
Thank you.

**Comment by petermg** [comment]
> Hi, thank you for this awesome tool. It's really super powerful and fast. What I miss here is a GUI. is there any plan for a GUI for Windows? that would be great. Thank you.

He already has a GUI version, here:
https://auto-editor.com/app/

**Comment by oc7opu5** [comment]
oh wow, I didn't know that.
Thank You
