### ISSUE TITLE
Desync problem wasn't solved use "--no-seek"

### ISSUE THREAD

**Issue by flt6** [WyattBlue/auto-editor#276]
# You're Exporting to:
 - [x] Media File (Video or Audio)
 - [x] Premiere Pro
 - [ ] DaVinci Resolve
Both two has the same problem.

# What is the frame rate and length of your video? (use `auto-editor info`)

 - video:
   - track 0:
     - codec: h264
     - pix_fmt: yuv420p
     - fps: 25
     - resolution: 1280x720
     - aspect ratio: 16:9
     - timebase: 1/12800
     - cc timebase: 1/50
     - bitrate: 695 kb/s
     - lang: und
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 48000
     - bitrate: 76 kb/s
     - lang: und
 - container:
   - duration: 00:48:36.12
   - bitrate: 781 kb/s
 
# What is desyncing and how bad is it? (exp. every 30 minutes, the audio is one second behind of video)
Not regular.

# Command (use "--no-seek" because #261):
python -m auto_editor --debug --no-seek phy.mp4
# version
[Commit ca10b372ec96a13205712e6dc370d6c0e6ba16f0](https://github.com/WyattBlue/auto-editor/commit/ca10b372ec96a13205712e6dc370d6c0e6ba16f0)
# debug info:
Debug: Temp Directory: C:\Users\****\AppData\Local\Temp\tmpxws7lj2q
Debug: phy.mp4 -> phy_ALTERED.mp4
Debug: apply video quality settings now: False
Debug: Tou: 512
Debug: Keyframe 0 0
Debug: Keyframe 250 128000
Debug: Keyframe 500 256000
Debug: Keyframe 750 384000
Debug: Keyframe 1000 512000
........
Debug: Keyframe 72149 36940288
Debug: Keyframe 72382 37059584
Debug: Keyframe 72632 37187584
Debug: Keyframe 72882 37315584
Debug: Total frames saved seeking: 0
Debug: Removed Temp Directory.

**Comment by WyattBlue** [comment]
I don't care. Maybe the encoded timestamps is damaged or too obscure.

Re-encoding with ffmpeg might help.

```
ffmpeg -i FILE -c:v h264 -c:a aac out.mp4

# or
ffmpeg -i FILE -r 30 -ar 48000 -c:v h264 -c:a aac out.mp4
```
