### ISSUE TITLE
Compatibility issue with Python 3.10

### ISSUE THREAD

**Issue by Valentin-Metz** [WyattBlue/auto-editor#279]
### What's your platform?

```shell
Manjaro Linux
Python 3.10
```

### Bug description

auto-editor (installed with pip) does not seem to recognize python3.10.
`exec: Failed to execute process '/usr/local/bin/auto-editor': The file specified the interpreter '/usr/local/bin/python3.9', which is not an executable command.`
More specifically it searches directly for python3.9 instead of using the installed (and probably compatible) python3.10.

`which python
/usr/bin/python`
`which python3.9
which: no python3.9 in (/home/feuermagier/.local/share/gem/ruby/3.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/var/lib/snapd/snap/bin:/home/feuermagier/.local/bin`
`which python3.10
/usr/bin/python3.10`
`which python3
/usr/bin/python3`

### What command did you use

```shell
auto-editor --version
```

### Comments

How to fix:
Either use raw `python` or `python3` and check the version of that, or let pip select for you on install.

**Comment by WyattBlue** [comment]
That is not ideal behavior.

I don't think the error is on our end though, but rather your pip making a shebang to a python that doesn't exist.

**Comment by Valentin-Metz** [comment]
Interesting. I specifically tried with
`python3.10 -m pip install --upgrade auto-editor`,
but the error persists.
auto-editor appears to be the only package affected.
I'll look into it.

**Comment by Valentin-Metz** [comment]
You are correct about the shebang:
`cat /usr/local/bin/auto-editor


#!/usr/local/bin/python3.9
# -*- coding: utf-8 -*-
import re
import sys
from auto_editor.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
`
I'm not sure how this got set though and whether pip / the auto-editor upgrade process is responsible for changing this to the new python version on upgrade.

**Comment by WyattBlue** [comment]
`pip uninstall auto-editor` should also delete that file. 

I'll close this issue since it's resolved.
