### ISSUE TITLE
Video shows static frame when jumping back and forth after removing the silence

### ISSUE THREAD

**Issue by mannarmani** [WyattBlue/auto-editor#281]
### What's your platform?

```shell
Python Version: 3.10.2 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-105325-g7512293cf9
FFmpeg Path: C:\Program Files\Python310\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 22w18a
```

### Bug description

1. To remove silence from video, run the command `auto-editor "Intro.mp4" --frame-margin 8`
2. After a while the video get shorten
3. Open the Intro_ALTERED.mp4 in VLC/any other video player
4. Move back and forth
5. Notice the video is frozen jittery /frozen 
[Intro.zip](https://github.com/WyattBlue/auto-editor/files/8689044/Intro.zip)
and displays only the frame that was showing before moving back and forth

Please note that it was working flawless when I checked about 6 weeks back (I'm sure which version I used)

### What command did you use

```shell
auto-editor "Intro.mp4" --frame-margin 8
```

### What properties does your input video have?

```shell
intro.mp4:
 - video:
   - track 0:
     - codec: h264
     - pix_fmt: yuv420p
     - fps: 30
     - resolution: 640x360
     - aspect ratio: 16:9
     - timebase: 1/15360
     - cc timebase: 1/60
     - bitrate: 33 kb/s
     - lang: und
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 44100
     - bitrate: 128 kb/s
     - lang: eng
 - container:
   - duration: 00:04:47.42
   - bitrate: 169 kb/s
   
   
   
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'intro.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Learn PMP concepts in MindMap way | Project Management Professional (PMP)┬«
    artist          : pmpexam guru
    date            : 2020
    encoder         : Lavf58.39.101
    comment         : https://www.youtube.com/watch?v=tJWp7FGH7fo
  Duration: 00:04:47.42, start: 0.000000, bitrate: 169 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9], 33 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
```

**Comment by WyattBlue** [comment]
Your ALTERED video has only 1 keyframe which explains the difficulty when jumping back and forth.

What's strange is when running your input video on my computer, the output does have steady stream of keyframes.

**Comment by mannarmani** [comment]
Thank you for the quick reply. Not only for this video, but in any video, I face this issue. Also, tried in an another computer and the issue remains the same.

**Comment by WyattBlue** [comment]
Even example.mp4, the canonical video used for testing?

**Comment by mannarmani** [comment]
> Even example.mp4, the canonical video used for testing?

I'm sorry, I couldn't understand what you are asking. I meant to say that I have used the same intro.mp4 for testing in an another computer. Also, tested few other videos (both in my machine and in an another machine) and the result is same.

**Comment by zonkedzoey** [comment]
I experienced the same issue, I found re-encoding the video in handbrake fixed it

**Comment by WyattBlue** [comment]
Is this still a problem in 22w32a?

**Comment by mannarmani** [comment]
Hi WyattBlue, 
Yes, the problem still exist.

**Comment by WyattBlue** [comment]
> Hi WyattBlue, Yes, the problem still exist.

Can you send the affected video?

**Comment by mannarmani** [comment]
Hi WyattBlue,

Uploaded a sample here.
https://drive.google.com/drive/folders/1EuncSVEqfI9C-_WhZ9KiDDoanlksWhV-?usp=sharing

SampleVid.mp4 is the original one.
SampleVid_ALTERED is the generated by auto-editor with silence removed.

Now, unlike in the past, the video screen doesn't free and shows the old
one, but now there is lag.

In the 2nd file, move between 1st slide screen and 2nd slide screen and 3rd
slide.
The screen freezes and then video gets played.
In a 30 minutes videos the screen freezes sometimes even 3 to 5 seconds.

I hope this helps.

Best regards,
Mani.

--------------------------------------------

**Comment by mannarmani** [comment]
Hi WyattBlue/auto-editor,
Are you able to reproduce the issue?

Regards,
Mani

**Comment by WyattBlue** [comment]
@mannarmani Nope
