### ISSUE TITLE
feat: support colorSpace for exporting fcpxml

### ISSUE THREAD

**Issue by hnlq715** [WyattBlue/auto-editor#283]
Currently iPhone 12 or above support Dobly video capture, which is not supported by `1-1-1 (Rec. 709)`.

So we should support to define colorSpace when do exporting, such as `9-18-9 (Rec. 2020 HLG)` from below link.

https://developer.apple.com/documentation/professional_video_applications/fcpxml_reference/asset#3686496

With this change, I can preview the Dobly video normally.

**Comment by WyattBlue** [comment]
Commit e24a60fb6900f56f38879ab82be267039b53c7d5 should implement this issue. Will release the patch soon.
