### ISSUE TITLE
Unknown Encoder Vp9

### ISSUE THREAD

**Issue by aeseok** [WyattBlue/auto-editor#286]
**What went wrong**

Tried to run this command on a downloaded Youtube video and it crashes outputting 

"Error! Unknown encoder 'vp9'"

**Paste your command and it's output here.**

PS C:\Users\user\Downloads\jumpcutter-master\new> auto-editor output000.mp4 -o output000-1.mp4 --silent-threshold 4% --video-speed 1 --silent-speed 3 --frame-margin 4
Error! Unknown encoder 'vp9'

**Comment by WyattBlue** [comment]
New release adds vp9 encoder to default ffmpegs
