### ISSUE TITLE
"Error! DLL amfrt64.dll failed to open"

### ISSUE THREAD

**Issue by petermg** [WyattBlue/auto-editor#287]
### What's your platform?

```shell
D:\OBSCaptures>auto-editor --debug
Python Version: 3.9.6 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-107035-gd42b410e05
FFmpeg Path: C:\Users\pgomb\AppData\Local\Programs\Python\Python39\Lib\site-packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 22w22a
```

### Bug description

When running:
D:\OBSCaptures>auto-editor OW.mkv --edit audio:stream=1 --keep-tracks-seperate
It failed with the following message:
```
D:\OBSCaptures>auto-editor OW.mkv --edit audio:stream=1 --keep-tracks-seperate
[h264 @ 0000024727aa01c0] co located POCs unavailable
    Last message repeated 1 times
Error! DLL amfrt64.dll failed to open
```

### What command did you use

```shell
D:\OBSCaptures>auto-editor OW.mkv --edit audio:stream=1 --keep-tracks-seperate
```

### What properties does your input video have?

```shell
D:\OBSCaptures>auto-editor info OW.mkv
OW.mkv:
 - video:
   - track 0:
     - codec: h264
     - pix_fmt: yuv420p
     - fps: 60
     - resolution: 1920x1080
     - aspect ratio: 16:9
     - timebase: 1/1000
     - cc timebase: 1/120
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 48000
   - track 1:
     - codec: aac
     - samplerate: 48000
 - container:
   - duration: 00:19:46.434
   - bitrate: 75448980
```

**Comment by WyattBlue** [comment]
You don't have hardware support "h264", use the "hevc" codec.

**Comment by sasa** [comment]
I seem to have the same problem.

C:\tools\python\Scripts\auto-editor
C:\home\Videos\obs\archiv\2022-06-03_04-01-40.mkv -s 99999 -o
'2022-06-03_04-01-40-0.mkv' --audio_codec copy -m 5 --no_open
Error! DLL amfrt64.dll failed to open
Failure...

What do you mean by 'You don't have hardware support "h264", use the "hevc"
codec.'


hevc as a recording format? Or as a parameter?

Greetings
Saša


Am Fr., 3. Juni 2022 um 03:05 Uhr schrieb WyattBlue <
***@***.***>:

**Comment by WyattBlue** [comment]
I reverted the Windows ffmpeg, so this should be fixed.
