### ISSUE TITLE
Don't want finished video opening up automatically. 

### ISSUE THREAD

**Issue by tys203831** [WyattBlue/auto-editor#290]
Great library. Thanks for your effort. I wish to request a simple feature.  

## Descript what feature/improvement you would like here.
I don't like the finished video automatically opening itself. It's because I wish to script the process to move the finished video to another folders. With the video opens, I cannot move the finished videos programmatically to another folder. 

## Descript how you would use it.
I wish to script this process using subprocess. So, I could MASS process the video(s) with this library.

**Comment by WyattBlue** [comment]
`--no-open` exists
