### ISSUE TITLE
Question about these Global Editing options

### ISSUE THREAD

**Issue by rexelbartolome** [WyattBlue/auto-editor#296]
![image](https://user-images.githubusercontent.com/88552647/186974001-285311e3-385e-4af3-a445-f1a09290943f.png)

What number do I put? Number of frames or seconds? Sorry I'm not too familiar with command line editing 😅

**Comment by WyattBlue** [comment]
The units are "frames" by default, (really ticks, as defined by timbase) you can also put it in by seconds using any second unit. `--minclip 0.3sec`
