### ISSUE TITLE
Latest version does not work

### ISSUE THREAD

**Issue by lxyer** [WyattBlue/auto-editor#299]
auto-editor /Users/lxyer/Desktop/ai1.mp4  --edit 'audio:threshold=2% or motion:threshold=0.02%'  --export final-cut-pro

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fcpxml>

<fcpxml version="1.9">
	<resources>
		<format id="r1" name="FFVideoFormat2160p30.0" frameDuration="100/3000s" width="3840" height="2160" colorSpace="1-1-1 (Rec. 709)"/>
		<asset id="r2" name="ai1.mp4" start="0s" hasVideo="1" format="r1" hasAudio="1" audioSources="1" audioChannels="2" duration="3390100/3000s">
			<media-rep kind="original-media" src="file:///Users/lxyer/Desktop/ai1.mp4"></media-rep>
		</asset>
	</resources>
	<library>
		<event name="Auto-Editor Video Group">
			<project name="ai1.mp4">
				<sequence format="r1" tcStart="0s" tcFormat="NDF" audioLayout="stereo" audioRate="48k">
					<spine>
						<asset-clip name="ai1.mp4" offset="0s" ref="r2" duration="16100/3000s" tcFormat="NDF"/>
						<asset-clip name="ai1.mp4" offset="16100/3000s" ref="r2" duration="284500/3000s" start="51500/3000s" tcFormat="NDF"/>
						<asset-clip name="ai1.mp4" offset="300600/3000s" ref="r2" duration="3051700/3000s" start="338500/3000s" tcFormat="NDF"/>
					</spine>
				</sequence>
			</project>
		</event>
	</library>
</fcpxml>

**Comment by lxyer** [comment]
Very long video, only one cut, there are many positions are not cuted

**Comment by lxyer** [comment]
This video is in HEVC format

**Comment by WyattBlue** [comment]
Low quality, closing
