### ISSUE TITLE
Question: why not combine videos with -codec copy, which is more efficient?

### ISSUE THREAD

**Issue by hnlq715** [WyattBlue/auto-editor#301]
https://github.com/WyattBlue/auto-editor/blob/b110748939fed1b9f8dfb1c1d47d4434f0c8ff90/auto_editor/__main__.py#L399-L411

**Comment by WyattBlue** [comment]
Because the input video's codec or pix_fmt might not be supported in editor to the exported.

The most efficient solution would be to delete this entire code block and instead, implement exporting v2 timelines to editors, but that's very time intensive on my end.
