### ISSUE TITLE
feat: use vad to detect human speech only

### ISSUE THREAD

**Issue by hnlq715** [WyattBlue/auto-editor#303]
AFAIK, we can use https://github.com/wiseman/py-webrtcvad to do this stuff :-)

**Comment by prime-optimal** [comment]
oh wow that would be really cool!  I'm currently testing ae on a video from a convention and it's noisy, so I feel like this would help a lot

**Comment by WyattBlue** [comment]
I have no plans on adding this feature in the near future, so i'm closing this issue.
