### ISSUE TITLE
.mp4 with multiple audio tracks to .mp3 output help

### ISSUE THREAD

**Issue by yigexuezha** [WyattBlue/auto-editor#304]
My .mp4 have multiple audio tracks.
I want to cut audio track 1 and output this track audio(.mp3)
I use:
--export audio --edit audio:stream=0,threshold=0.03 --frame-margin 15,20  --audio-codec mp3 --audio-bitrate 320k --keep-tracks-seperate --no-open 

But auto editor said: Warning! 'mp3' container doesn't support multiple audio tracks.
And output a combine audio.
How can I write is right?
Help me please ! Thank you very much!

**Comment by WyattBlue** [comment]
```
ffmpeg -i video.mp4 -map 0 -map -0:a:1 -c copy video_one_track.mp4
auto-editor video_one_track.mp4 -o out.mp3
```
