### ISSUE TITLE
Is it possible to support AutoFlip (An Open Source Framework for Intelligent Video Reframing)

### ISSUE THREAD

**Issue by photkey** [WyattBlue/auto-editor#306]
https://ai.googleblog.com/2020/02/autoflip-open-source-framework-for.html
https://google.github.io/mediapipe/solutions/autoflip

**Comment by WyattBlue** [comment]
No
 - Auto-Editor already has a robust video renderer and duplicating another one is wasteful
 - Adding another dependency is something I don't want to do
