### ISSUE TITLE
With mov extension, QuickTime says the converted file has some incompatible media

### ISSUE THREAD

**Issue by paulobr01** [WyattBlue/auto-editor#307]
Hello.  I tried converting a video file on Mac, a .mov extension, about 8 minutes long, and QuickTime says the converted file has some incompatible media and the video opens with audio only.  Why does it happen?  How do I solve the problem?  The video was recorded in the iPhone Camera APP.

**Comment by WyattBlue** [comment]
Check to make sure your video and audio codec are compatible with QuickTime

**Comment by gsparx** [comment]
For future reference if anyone else runs into this, I believe you need to tell `ffmpeg` to add an additional tag (`hvc1`) to the video track.

Mentioned [here](https://brandur.org/fragments/ffmpeg-h265)

To accomplish this with auto-editor, use the `--extras` flag to add extra flags to the `ffmpeg` call. E.g.

```
auto-editor <input>.MOV -o <output>.MOV --extras '-tag:v hvc1' <...etc>
```
