### ISSUE TITLE
Is there an ability to only slice but not delete?

### ISSUE THREAD

**Issue by domingasp** [WyattBlue/auto-editor#310]
Hi, great software which saves a lot of time. There are times when I would rather have it do the slices but not delete those 'silent' sections and leave that up to me to do. I could use the options to increase minimum clip time, however, it would make it easier for me to just scrub through and delete the silences I do not want and keep those which add to the video.

The command could look something like: `auto-editor my-vid.mp4 --export premiere --slice-only`.

I couldn't find a flag for this, so am not sure this functionality exists.

Many thanks!

**Comment by WyattBlue** [comment]
Auto-Editor does have this. Use `--silent-speed 1` and the program will add the slices.
