### ISSUE TITLE
Docs for --edit

### ISSUE THREAD

**Issue by JC3** [WyattBlue/auto-editor#312]
Would it be possible to add documentation for `--edit` to the `--help` output? 

I usually forget and have to dig up the readme to look at some of the examples, and I'm not really sure what other parameters it can take besides the ones in those examples.

Right now it says:

```
   --edit, --edit-based-on [METHOD:[ATTRS?] OPERAND? ...]
                                                      Decide which method to use when making edits
```

But it doesn't include info about what `METHOD`, `ATTRS` and `OPERAND` are.

Thanks! :)

**Comment by JC3** [comment]
So, just for reference, since I'm not actually sure... what *are* `METHOD`, `ATTRS`, and `OPERAND`?

**Comment by DJTacki** [comment]
"Use --help with a specific option for more information:"

c:\auto-editor-master>auto-editor --edit --help
  --edit-based-on, --edit [METHOD:[ATTRS?] OPERAND? ...]

    default: audio
    --------------

    Editing Methods:
     - audio: General audio detection
     - motion: Motion detection specialized for real life noisy video
     - pixeldiff: Detect when a certain amount of pixels have changed between frames
     - random: Set silent/loud randomly based on a random or preset seed
     - none: Do not modify the media in anyway (Mark all sections as "loud")
     - all: Cut out everything out (Mark all sections as "silent")

    Attribute Defaults:
     - audio
        - threshold: 4% (number)
        - stream: 0 (natural | "all")
     - motion
        - threshold: 2% (number)
        - stream: 0 (natural | "all")
        - blur: 9 (natural)
        - width: 400 (natural)
     - pixeldiff
        - threshold: 1 (natural)
        - stream: 0 (natural | "all")
     - random
        - threshold: 0.5 (number)
        - seed: RANDOMLY-GENERATED (int)

    Operators:
     - and
       - usage: $METHOD and $METHOD
     - or
       - usage: $METHOD or $METHOD
     - xor
       - usage: $METHOD xor $METHOD
     - not
       - usage: not $METHOD
    Examples:
      --edit audio
      --edit audio:stream=1
      --edit audio:threshold=4%
      --edit audio:threshold=0.03
      --edit motion
      --edit motion:threshold=2%,blur=3
      --edit audio:threshold=4% or motion:threshold=2%,blur=3
      --edit none
      --edit all

**Comment by JC3** [comment]
Sweet! Thanks!
