### ISSUE TITLE
What the "--silent-speed" argument, and how to use it to accelerate silence part to 4 times speed?

### ISSUE THREAD

**Issue by rsyqvthv** [WyattBlue/auto-editor#314]
I would like to make the silence part of video be accelerated to 4 times, instead of just cut off. 

the helping shows

```
    default: 99999.0
    ----------------

    99999 is the 'cut speed' and values over that or <=0 are considered 'cut speeds' as well
```

I tried use `-s 4`, seems it longer the silence part, and lost of the loud part has been removed as well.

please help. Thanks.

**Comment by WyattBlue** [comment]
`-s 4` is the correct option. 

I'm not sure why say silence is longer or that parts of loudness is being removed. I'm not getting this at all.
