### ISSUE TITLE
Android support instalation

### ISSUE THREAD

**Issue by areen-c** [WyattBlue/auto-editor#315]
Any idea to use auto-editor on termux? I've tried install it via pip unfortunately i got errors while building it
`Fatal error from pip prevented installation. Full pip output in file:
    /data/data/com.termux/files/home/.local/pipx/logs/cmd_2022-11-02_02.00.23_pip_errors.log

pip seemed to fail to build package:
    av==10.0.0

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    Package libavformat was not found in the pkg-config search path.
    Package libavcodec was not found in the pkg-config search path.
    Package libavdevice was not found in the pkg-config search path.
    Package libavutil was not found in the pkg-config search path.
    Package libavfilter was not found in the pkg-config search path.
    Package libswscale was not found in the pkg-config search path.
    Package libswresample was not found in the pkg-config search path.

Error installing auto-editor.`

Additional info:
OS: Android 11
Rooted: yes
Terminal: termux 0.118.0

**Comment by WyattBlue** [comment]
Auto-Editor doesn't support Android as a platform, so any errors using/installing auto-editor on that platform are up to the user to solve, not the upstream devs.
