### ISSUE TITLE
--min-clip-length not working

### ISSUE THREAD

**Issue by NotJoeyBlack** [WyattBlue/auto-editor#324]
### What's your platform?

```shell
Python Version: 3.10.9 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-105325-g7512293cf9
FFmpeg Path: C:\Python310\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 23w04a
```

### Bug description

When I use --min-clip-length it says Error! Unknown option: --min-clip-length

### What command did you use

```shell
--min-clip-length, --min-clip, -mclip
```

**Comment by WyattBlue** [comment]
I replaced that option intentionally, in 23w04a because globally applying min-clip/min-cut created worse edits for `motion` and `subtitle`, so instead, you can apply mincut/minclip directly to audio. `--edit audio:mincut=4,minclip=6`
