### ISSUE TITLE
it has 1 audio channel(s) and the clip was created with 2 audio channel(s)

### ISSUE THREAD

**Issue by jadsonconsolini** [WyattBlue/auto-editor#325]
### Bug description

I'm new to all this, I'm trying to make cuts and upload the xml to Premiere, but whenever I do that, this error appears "The selected file cannot be linked because it has 1 audio channel(s) and the clip was created with 2 audio channel(s) with a different channel type.", how can I solve it?

### What command did you use

```shell
auto-editor namefile --export premiere
```

**Comment by WyattBlue** [comment]
I've tested premiere import with mono inputs, and premiere imports them just fine.

Can you run `auto-editor info` on your file?

**Comment by WyattBlue** [comment]
Closing because OP has not followed up
