### ISSUE TITLE
Error! DLL amfrt64.dll failed to open (Intel CPU & NVIDIA GPU)

### ISSUE THREAD

**Issue by slagjaw** [WyattBlue/auto-editor#328]
### What's your platform?

```shell
Python Version: 3.10.6 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-105325-g7512293cf9
FFmpeg Path: C:\Users\skril\AppData\Local\Programs\Python\Python310\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 23w04a
```

### Bug description

After using auto-editor for months (using mp4) I had mkv files laying around. I tried a few and oddly each gave me an AMD GPU hardware encoder error. I thought it was an incompatibility issue, so then I attempted to force other well-known encoders and it didn't understand. I also converted the files to mp4 if it helped and that didn't work either. I am very confused. Thanks.

### What command did you use

```shell
(Tried both mkv and mp4)
auto-editor --margin 0.2sec "example.mkv"
Error! DLL amfrt64.dll failed to open

auto-editor --margin 0.2sec "example.mp4"
Error! DLL amfrt64.dll failed to open

(Forcing encoder)
auto-editor -vcodec h264_nvenc --margin 0.2sec "example.mkv"
Error! Unknown encoder 'h264_nvenc'

auto-editor -vcodec libx264 --margin 0.2sec "example.mp4"
Error! Unknown encoder 'libx264'
```

### Comments

- I want to clarify that I am NOT a code expert.

**Comment by slagjaw** [comment]
UPDATE: So, up until now I figured out that when looking more closely at files which had 'hevc' aka h.265 transcoding, auto-editor will _always_ produce the aforementioned .dll error; yet still does not recognize common codecs like libx264 etc. Why is this happening?

**Comment by WyattBlue** [comment]
"libx264", isn't an common codec, it's a specific h264 implementation under GPLv3. If you want to use it, install ffmpeg then run auto-editor with the `--my-ffmpeg` flag. h.265 should be supported, the codec is called `hevc`

**Comment by WyattBlue** [comment]
If you're getting this error, [download FFmpeg](https://ffmpeg.org/download.html) and then add the `--my-ffmpeg` flag when using auto-editor.

---
Note: I'm not sure if it's possible to compile the default ffmpeg that can work on all common hardware. If you know, please make a pull request.
