### ISSUE TITLE
FFmpeg error for iPhone 4K 60fps videos

### ISSUE THREAD

**Issue by MichaelBaiJie** [WyattBlue/auto-editor#330]
auto-editor versions attempted: 
`22w52a (22.52.1)' AND '23w04a (23.4.1)`

Error received:
```
stderr: Input #0, rawvideo, from 'pipe:':
  Duration: N/A, bitrate: 5971968 kb/s
  Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 3840x2160, 5971968 kb/s, 60 tbr, 60 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> hevc (hevc_videotoolbox))
[hevc_videotoolbox @ 0x7fc3c8707300] Error encoding frame: -12905
[hevc_videotoolbox @ 0x7fc3c8707300] popping: -542398533
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

Error! FFmpeg Error!
```

Command Used:
`auto-editor {FileName}`

This has only happened when trying to edit iPhone videos shot with 4k 60fps

**Comment by MichaelBaiJie** [comment]
Update: I installed ffmpeg and used `--my-ffmpeg`, and everything seems to be working. Might be a H.265 encoding issue based on built-in ffmpeg tags.

**Comment by WyattBlue** [comment]
Since it's working for you when you're using your ffmpeg, I'll close this issue. At some point, I will update the built-in ffmpeg binaries and so it works by default, but this is a urgent task.
