### ISSUE TITLE
What is the working logic of audio:threshold

### ISSUE THREAD

**Issue by FurkanGozukara** [WyattBlue/auto-editor#332]
First of all thank you so much for this amazing tool

Since I discovered it, I have greatly improved my videos quality

Such as my previously done video : https://youtu.be/mnCY8uM7E50

My newest video : https://youtu.be/QN1vdGhjcRc

What is the working logic of audio:threshold=0.1 vs audio:threshold=0.01

I used so far default audio:threshold=0.04

**Comment by WyattBlue** [comment]
The `audio:threshold` parameter is used to determine the minimum volume level at which audio is detected by the automatic silence recognition system. The value of the threshold determines how sensitive the system is to detecting audio.

A higher threshold value, such as `audio:threshold=0.1`, means that the system will only transcribe audio that is louder than 0.1 (10%) of the maximum audio volume. This is useful for filtering out background noise or detecting speech in environments with a high level of ambient noise.

A lower threshold value, such as `audio:threshold=0.01`, means that the system will transcribe audio that is much quieter. This can be useful for detecting and transcribing low volume speech or speech that is far away from the recording device.

The default value of `audio:threshold=0.04` is a moderate sensitivity level that can work well for most situations. However, you can adjust the threshold value to suit your specific needs and the characteristics of your audio recordings.

**Comment by FurkanGozukara** [comment]
> 

thanks for answer. so pre processing audio with removing noise, fixing sound levels, then using auto editor would yield better results i presume
