### ISSUE TITLE
What does --yt-dlp-location command do?

### ISSUE THREAD

**Issue by DeysonOrtiz** [WyattBlue/auto-editor#333]
Hello, 

I am curious to know what the --yt-dlp-location command does.
Is it a way to download Youtube videos?

Thank you and have a Fantastic Day! 🙂

**Comment by WyattBlue** [comment]
The `--yt-dlp-location` command allows you to specify the location of the yt-dlp executable on your system.

yt-dlp is a command-line program that can download videos from various websites, including YouTube. Auto-Editor already looks for yt-dlp if it's on the PATH, but the option always you to make auto-editor look somewhere else.

For example, if you have yt-dlp installed on your system in the directory /usr/local/bin, you would use the following command in auto-editor:

```
auto-editor input.mp4 --yt-dlp-location /usr/local/bin/yt-dlp
```

---
You can install yt-dlp with:

```
pip install yt-dlp
```

and with this installation method, you won't need to specify the `--yt-dlp-location`, auto-editor will automatically find it.
