### ISSUE TITLE
Extend pauses/silence to slow down an audio track.

### ISSUE THREAD

**Issue by DeysonOrtiz** [WyattBlue/auto-editor#335]
Is there a way to extend silences on our audio tracks?

I have Podcasts that are too rushed, as they were edited by someone else with no breathing room. 
The way I see it work is to take a pause and multiply the pause by a factor of what we set.

We can then go into our NLE editor, such as Logic, and clean up the pauses as the room tone and extended silence might not match. 

Please let me know what you think.

**Comment by WyattBlue** [comment]
You can use `--silent-speed` to extend audio silences using time stretching. 

For example:
```
auto-editor your-podcast.mp3 --silent-speed 0.85
```

**Comment by DeysonOrtiz** [comment]
Awesome!  Thank you! 🙂
