### ISSUE TITLE
Possible to edit out silences except when there is Motion on screen.

### ISSUE THREAD

**Issue by DeysonOrtiz** [WyattBlue/auto-editor#338]
Hello and good day.

When I edit tutorial videos I would like to edit out the silences except when there is motion on the screen.
If I am demonstrating an example on-screen or moving the mouse (cursor) around I would like to keep that part in. 

Please let me know what you think. 🤔
Thank you and have a Fantastic Day! 🙂

**Comment by WyattBlue** [comment]
```
auto-editor --edit '(or audio motion:threshold=0.3%)'
```

**Comment by DeysonOrtiz** [comment]
Thank you 🙂
