### ISSUE TITLE
Mark silent tracks for premiere or directly pull "silent-audio" to seperate second track

### ISSUE THREAD

**Issue by miriambrueckner** [WyattBlue/auto-editor#339]
I would like to be able to mark silent parts with a separate color (as I do not cut them out but speed them up x2) for Premiere Pro so I could **grab them all at once and pull the audio to a separate track for further editing** on track level // alternatively it would be great if it was possible to pull the "silent audio" to a separate track directly (without color coding for Premiere Pro)

 I would use this for my instructional videos where I usually speed up all parts of the video in which I am not speaking

 Yes I really need it, because otherwise I still would have to grab every silent-audio piece by hand and put it to a separate track. As silent in my case does not mean complete silence but you here some sounds of me working I usually reduce the volume to have these parts at least nearly silent but still present in the video.

 as I just installed the program today I sure I am using the latest version

**Comment by WyattBlue** [comment]
You can already do:

```
auto-editor input.mp4 --silent-speed 1 --export premiere
```
and that should do 90% of what you want (create splits between "silent" and "loud", but no editing)
I don't think there's much value in adding anything else.

**Comment by miriambrueckner** [comment]
Thanks for your reply. Unfortunately it does not nearly 90% as I have to click and track every silent piece to another audio track to be able to use global sound settings for these silent ones / make sure that my audio adjustments for the loud layer are not applied to the silent one. I think there would be real value in having this cutting into 2 tracks been done by your very smart app :)
