### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u23f3' in position 2: character maps to <undefined>

### ISSUE THREAD

**Issue by sasa** [WyattBlue/auto-editor#34]
```
Traceback (most recent call last):
  File "..\..\auto-editor.py", line 271, in <module>
    outFile = fastVideo(INPUT_FILE, newOutput, args.silent_threshold,
  File "C:\home\Videos\obs\archiv\scripts\fastVideo.py", line 105, in fastVideo
    progressBar(cframe, totalFrames, beginTime)
  File "C:\home\Videos\obs\archiv\scripts\usefulFunctions.py", line 122, in progressBar
    print(bar, end='\r', flush=True)
  File "C:\Program Files\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u23f3' in position 2: character maps to <undefined>
Running from fastVideo.py
Failure...
```

Windows 10 from Windows Terminal using Powershell

When I remove the unicode chars in these three lines it works again

```
doneStr = 'o' * done
togoStr = ' ' * int(barLen - done)
...
bar = f'  {title}: [{doneStr}{togoStr}] {percentDone}% done ETA {newTime}'
```

**Comment by WyattBlue** [comment]
I think the best way to deal with this is to back up to regular characters if a unicode error occurs.

```python
    try:
        doneStr = '█' * done
        togoStr = '░' * int(barLen - done)
    except UnicodeEncodeError:
        doneStr = 'O' * done
        togoStr = ' ' * int(barLen - done)
```

Thanks for the report.

**Comment by sasa** [comment]
That would be an option. 

Another thing that doesn't work is the \r. So it prints a whole lot of lines.

I will try to find out why that is. This should work with the brand new Windows Terminal app. Maybe I should go and post a bug report over there. I also like my nice characters :-)

**Comment by WyattBlue** [comment]
That sounds like a good idea. I'll still implement that check so that the program doesn't crash though.

**Comment by WyattBlue** [comment]
I think I solved it crashing on you so I'll close this issue.

**Comment by sasa** [comment]
this line also needs a try catch clause:

`bar = f'  ⏳{title}: [{doneStr}{togoStr}] {percentDone}% done ETA {newTime}'`

**Comment by sasa** [comment]
No, that is not it. Essentially Python on Windows seems to be the problem. I need to remove these characters. Otherwise the script breaks.

`
PS C:\home\Videos\obs\archiv> py .\auto-editor.py --debug
Python Version: 3.8.2 64-bit
Platform: Windows
Auto-Editor Version: 20w27b hotfix
`

**Comment by WyattBlue** [comment]
@sasa See if the new version fixed this problem.
