### ISSUE TITLE
Feat: Split instead of Delete (Selective Delete)

### ISSUE THREAD

**Issue by MilkAndBanana01** [WyattBlue/auto-editor#340]
From using it to speed up my editing, I have found that removing all silent parts in the video can make the base edit more difficult to work with especially if the cuts are too small (default behaviour can be improved when using `audio:threshold`, but only to an extent). 

A solution to this could be if the clip's duration is below a certain length, that it can split the start and end of the clip but not delete it, allowing the editor to remove manually when exported as an XML.

Adding a parameter named `selective_delete` can provide this functionality. There can also be additional parameters to change the behaviour of this parameter:

```
# An example prompt using the proposed feature:
stable-ts input.mp4 --selective_delete=true --export resolve

# This exports an XML file that can be used, in which some clips are split instead of cut to be manually removed by 
the editor.
```

`--selective_delete_threshold FLOAT` : (default = 0.1) can determine the maximum duration of a non-removable clip.
`--selective_delete_random BOOL`: (default = false) *Experimental Feature**: Will randomly keep or remove clips that meets the --selective_delete_threshold FLOAT

`selective_delete` can also be potentially used with `start` and `end` markers, allowing it to work at specific ranges of the video.
```
#Applies selective delete to the first 30 seconds of the video, cuts the video like normal afterwards.
stable-ts input.mp4 --selective_delete true start,30sec
```
```
#Applies selective delete to the last 30 seconds of the video, cuts the video before like normal.
stable-ts input.mp4 --selective_delete true -30sec,end
```

**Comment by WyattBlue** [comment]
You can already do this for resolve.
```
auto-editor input.mp4 --silent-speed 1 --export resolve
```

**Comment by MilkAndBanana01** [comment]
> You can already do this for resolve.
> 
> ```
> auto-editor input.mp4 --silent-speed 1 --export resolve
> ```

The issue with this is that it keeps all the silent clips in regardless of length. This could be a solution where if you want certain length clips to only be split and not cut. Unless there's a way to determine if a clip can be split instead of cut by duration already.

**Comment by MilkAndBanana01** [comment]
Quick Update: I found out that increasing the parameter `mincut` does this feature. We probably need more documentation on how mincut and minclip works because it took me a while to realize that it's there and what it does.
