### ISSUE TITLE
Is that possible to mute taking a breath parts of an audio?

### ISSUE THREAD

**Issue by FurkanGozukara** [WyattBlue/auto-editor#341]
First of all thank you so so much for this amazing tool

I am using it on my all new videos

Here my newest one

26.) Automatic1111 Web UI - PC - Free
[Video To Anime - Generate An EPIC Animation From Your Phone Recording By Using Stable Diffusion AI](https://youtu.be/kmT-z2lqEPQ)
[
![image](https://user-images.githubusercontent.com/19240467/228096548-5f6add70-ca04-4bec-8c33-24d243227532.png)
](https://youtu.be/kmT-z2lqEPQ)

In the first 5 minutes I have manually edited and muted the breath taking parts

They are extremely easy to notice and mute for a person

![image](https://user-images.githubusercontent.com/19240467/228101306-8e60e391-ca04-4679-aafe-06dfcd24b78e.png)

But I wonder can we do that with auto editor?

For example in minute 11:00 I have a breath taking sound

https://youtu.be/kmT-z2lqEPQ?t=659

Can we mute such sounds?

Here how they are seen in Davinci Resolve

**Comment by WyattBlue** [comment]
No, and I don't plan on adding it.
