### ISSUE TITLE
DaVinci Resolve sometimes can't import input file

### ISSUE THREAD

**Issue by WyattBlue** [WyattBlue/auto-editor#344]
### What's your platform?

```shell
Windows
```

### Bug description

DaVinci Resolve sometimes can't import the file correctly when importing an XML file. This is probably because auto-editor isn't escaping the filename in a way resolve can understand.

### What command did you use

```shell
auto-editor INPUT --export resolve
```

### What properties does your input video have?

```
N/A (It's about the input name)
```

**Comment by gignupg** [comment]
I'm also using Windows (11) and DaVinci Resolve and I always get the error message "The clip "my clip" failed to link because the timecode extents do not match any clip in the Media Pool."

**Comment by gignupg** [comment]
In case anyone wants to know the workaround I ended up using, I'm simply exporting the video using CapCut before I create the XML file. Then I import the video I exported with CapCut to Resolve as well as the XML file and everything works like a charm

**Comment by WyattBlue** [comment]
I think I fixed this in master. If you still have this, make a new issue and provide your platform and the full path.
