### ISSUE TITLE
Setting a custom -s parameter causes the resulting video to freeze

### ISSUE THREAD

**Issue by ErikVogelLUH** [WyattBlue/auto-editor#345]
### Bug description

When I provide a custom parameter for how much sped up the silent sections should be, the result seems to randomly freeze. This means there is no sound and the image does not change, but the video keeps playing. This doesn't seem like video and sound are missing, but are this static image with no sound. The freeze stays for a few seconds. Video and sound continue like there was no freeze, meaning big chunks of information in the result are missing.

The amount freezes and the length of the freezes grow with a higher values for -s. This does not happen when choosing a custom value for -v. This relationship was only tested for one video. Freezes were observed in every video with a custom value for -s.

### What's your platform?

```shell
Python Version: 3.11.2 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-105325-g7512293cf9
FFmpeg Path: C:\Users\Erik\AppData\Roaming\Python\Python311\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 23w12a
```
```


### What command did you use

```shell
`auto-editor ./test.mkv -s 10`
```

### What properties does your input video have?

`auto-editor info ./test.mkv`
```
.\test.mkv:
 - video:
   - track 0:
     - codec: h264
     - fps: 30000/1001
     - resolution: 1920x1080
     - aspect ratio: 16:9
     - pixel aspect ratio: 1:1
     - pix fmt: yuv420p
     - color range: tv
     - color space: bt709
     - color primaries: bt709
     - color transfer: bt709
     - timebase: 1/1000
     - lang: eng
 - audio:
   - track 0:
     - codec: vorbis
     - samplerate: 48000
     - channels: 2
     - lang: eng
 - container:
   - duration: 300.001000
   - bitrate: 2116000
```
`ffmpeg -hide_banner -i ./test.mkv`
```
Input #0, matroska,webm, from '.\test.mkv':
  Metadata:
    ENCODER         : Lavf59.24.100
  Duration: 00:05:00.00, start: 0.000000, bitrate: 2116 kb/s
  Stream #0:0(eng): Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc59.33.100 h264_nvenc
      DURATION        : 00:04:59.999000000
  Stream #0:1(eng): Audio: vorbis, 48000 Hz, stereo, fltp (default)
    Metadata:
      ENCODER         : Lavc59.33.100 libvorbis
      DURATION        : 00:05:00.001000000
```

**Comment by WyattBlue** [comment]
I, nor anyone else, has bee able to replicate this.
