### ISSUE TITLE
Can auto editor use GPU rendering instead of CPU?

### ISSUE THREAD

**Issue by FurkanGozukara** [WyattBlue/auto-editor#346]
I have downloaded and installed CUDA support having FFMPEG

It is also set as default

This is my command how can i make it use CUDA?

```powershell
auto-editor "{lstAudioFiles[0]}" --edit audio:threshold=0.04 -c:v libx264 --video-bitrate {bitrate} --show-ffmpeg-commands""```

**Comment by WyattBlue** [comment]
You need to use a different h264 encoder. It will likely be the one with `cuda` as it's prefix or suffix. 
You can look at all the encoders with `ffmpeg -hide_banner --codecs | grep h264`

See also https://auto-editor.com/docs/gpu
