### ISSUE TITLE
Allow to choose on which audio track should Auto-Editor base

### ISSUE THREAD

**Issue by Androl404** [WyattBlue/auto-editor#347]
Hi,

I configured my OBS Studio to make files with multiple audio tracks (one for my microphone, an other for the computer sound, etc.). But when I give my *.mp4* fille with multiple audio tracks to Auto-Editor, it only bases on the first which isn't useful in my case (bacause it's the computer sound).

I think it will be good to add an option to set the number of the track we want Auto-Editor to work on it. With *auto-editor info file*, we can see all video and audio tracks but we can't choose (as far as I know) on which audio track work.

Thanks.

**Comment by WyattBlue** [comment]
[You can already do this](https://github.com/WyattBlue/auto-editor#working-with-multiple-audio-tracks)
