### ISSUE TITLE
TypeError: list indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by firelightning13** [WyattBlue/auto-editor#35]
```
Traceback (most recent call last):
  File "auto-editor.py", line 277, in <module>
    outFile = fastVideoPlus(INPUT_FILE, newOutput, args.silent_threshold,
  File "C:\auto-editor\scripts\fastVideoPlus.py", line 141, in fastVideoPlus
    mySpeed = NEW_SPEED[state]
TypeError: list indices must be integers or slices, not NoneType
```
Tested fine when not using any optional argument, but when I tried to speed up the video to 1.25 by putting `-v 1.25`, this error came up. Using the latest version 20w27b.

**Comment by WyattBlue** [comment]
This fix should be simple. Just avoid executing that line when the state is  `None` . 

```python
        if(state is not None):
            mySpeed = NEW_SPEED[state]
```

I'll make a hotfix for this very soon. Thank you for your report.

**Comment by WyattBlue** [comment]
I implemented the fix. Try redownloading the code to see if you still have issues.

**Comment by firelightning13** [comment]
I redownload the code.  The issue is gone now. Thanks
