### ISSUE TITLE
auto-editor outputs unknown ffmpeg error

### ISSUE THREAD

**Issue by slagjaw** [WyattBlue/auto-editor#350]
### Bug description

This error _could_ be remedied by removing the ``--my-ffmpeg`` argument but without it, auto-editor creates another error "Error! DLL amfrt64.dll failed to open" that I've brought up before, which, A. doesn't make any sense since I don't own any amd hardware, and, B. I haven't ran auto-editor without the argument since that discovery you and I found. 

More importantly, the error message lacks description and there's nothing I can do to troubleshoot unless - and this is from a reddit post - "enable more verbose logging" or "step through it with a debugger" that neither of which I'm familiar with, so, I'm hoping you can understand this mess and come up with a fix. Thanks!

### What's your platform?

```shell
Python Version: 3.10.6 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-105325-g7512293cf9
FFmpeg Path: C:\Users\skril\AppData\Local\Programs\Python\Python310\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 23w10c
```

### What command did you use

```shell
C:\Users\skril>auto-editor --margin 0.2sec --my-ffmpeg "F:\STREAM\2023-05-14 07-57-47-00.00.00.000-06.27.13.687-seg1.mkv"
stderr: Input #0, rawvideo, from 'fd:':
  Duration: N/A, bitrate: 663552 kb/s
  Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720, 663552 kb/s, 60 tbr, 60 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> hevc (libx265))
x265 [info]: HEVC encoder version 3.5+86-6da609e41
x265 [info]: build info [Windows][GCC 12.2.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 12 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 3 / wpp(12 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : hex / 57 / 2 / 3
x265 [info]: Keyframe min / max / scenecut / bias  : 25 / 250 / 40 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 20 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 3 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-28.0 / 0.60
x265 [info]: tools: rd=3 psy-rd=2.00 early-skip rskip mode=1 signhide tmvp
x265 [info]: tools: b-intra strong-intra-smoothing lslices=4 deblock sao
Output #0, mp4, to 'C:\Users\skril\AppData\Local\Temp\tmp2pfwd3kv\spedup0.mp4':
  Metadata:
    encoder         : Lavf60.2.100
  Stream #0:0: Video: hevc (hev1 / 0x31766568), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 15360 tbn
    Metadata:
      encoder         : Lavc60.2.100 libx265
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
[mp4 @ 000001e143272d00] Starting second pass: moving the moov atom to the beginning of the file
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=-577014:32:22.77 bitrate=N/A speed=N/A
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:2kB muxing overhead: unknown

encoded 0 frames

Error! FFmpeg Error!
```

**Comment by slagjaw** [comment]
UPDATE: using ``--debug`` and ``--show-ffmpeg-output`` and ``--show-ffmpeg-commands`` somehow fixed the error??? This is what it output for those wondering:

``ffmpeg -hide_banner -y -i F:\STREAM\2023-05-14 07-57-47-00.00.00.000-06.27.13.687-seg1.mkv -i C:\Users\skril\AppData\Local\Temp\tmpd4xez9vq\spedup0.mp4 -i C:\Users\skril\AppData\Local\Temp\tmpd4xez9vq\new0.wav -map 1:0 -map 2:0 -map_metadata 0 -c:v:0 copy -video_track_timescale 60 -c:a aac -color_range tv -colorspace bt709 -color_primaries bt709 -color_trc bt709 -strict -2 -map 0:t? F:\STREAM\2023-05-14 07-57-47-00.00.00.000-06.27.13.687-seg1_ALTERED.mkv``

``stderr: Input #0, matroska,webm, from 'F:\STREAM\2023-05-14 07-57-47-00.00.00.000-06.27.13.687-seg1.mkv': Metadata: ENCODER : Lavf59.27.100 Duration: 06:27:13.71, start: 0.000000, bitrate: 15262 kb/s Stream #0:0: Video: hevc (Main), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 1k tbn (default) Metadata: DURATION : 06:27:13.699000000 Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default) Metadata: title : simple_aac_recording0 DURATION : 06:27:13.706000000Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\skril\AppData\Local\Temp\tmpd4xez9vq\spedup0.mp4': Metadata: major_brand : isom minor_version : 512 compatible_brands: isomiso2mp41 encoder : Lavf60.2.100 Duration: 04:51:28.93, start: 0.000000, bitrate: 1695 kb/s Stream #1:0[0x1](und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, progressive), 1280x720 [SAR 1:1 DAR 16:9], 1689 kb/s, 60 fps, 60 tbr, 15360 tbn (default) Metadata: handler_name : VideoHandler vendor_id : [0][0][0][0] encoder : Lavc60.2.100 libx265Guessed Channel Layout for Input Stream #2.0 : stereoInput #2, wav, from 'C:\Users\skril\AppData\Local\Temp\tmpd4xez9vq\new0.wav': Duration: 04:51:28.93, bitrate: 1536 kb/s Stream #2:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 2 channels, s16, 1536 kb/sStream mapping: Stream #1:0 -> #0:0 (copy) Stream #2:0 -> #0:1 (pcm_s16le (native) -> aac (native))Press [q] to stop, [?] for helpOutput #0, matroska, to 'F:\STREAM\2023-05-14 07-57-47-00.00.00.000-06.27.13.687-seg1_ALTERED.mkv': Metadata: encoder : Lavf60.2.100 Stream #0:0(und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 1689 kb/s, 60 fps, 60 tbr, 1k tbn (default) Metadata: handler_name : VideoHandler vendor_id : [0][0][0][0] encoder : Lavc60.2.100 libx265 Stream #0:1: Audio: aac (LC) ([255][0][0][0] / 0x00FF), 48000 Hz, stereo, fltp, 128 kb/s Metadata: encoder : Lavc60.2.100 aacframe=1049336 fps=1711 q=-1.0 Lsize= 3901295kB time=04:51:28.91 bitrate=1827.4kbits/s speed=28.5xvideo:3607212kB audio:281338kB subtitle:0kB other streams:0kB global headers:2kB muxing overhead: 0.327767%[aac @ 0000022d11557740] Qavg: 633.254Finished. took 28096.57 seconds (7:48:17)Debug: Removed Temp Directory.``

In the meantime, I'm going to try re-producing this on other files to confirm it wasn't by coincidence.

**Comment by WyattBlue** [comment]
You'll running old versions of auto-editor and ffmpeg.
Run:
```
pip install -U auto-editor ae-ffmpeg
```
to upgrade
