### ISSUE TITLE
Want to add determine the duration of silence function

### ISSUE THREAD

**Issue by yigexuezha** [WyattBlue/auto-editor#354]
Determine whether to delete based on the duration of silence

Example:
If duration of silence is 1-3 second, we do not cut it.
If duration of silence is 4-5 second, we subtract 2s then cut it.(4-2=2, 5-2=3)
If duration of silence is 6-100 second, we all change duration of silence to 6s.

Thanks for your efforts!

**Comment by dariuscosden** [comment]
I would like this as well

**Comment by WyattBlue** [comment]
This is already possible with palet, auto-editor's scripting language. If you didin't already know, you can put arbitrary palet expressions in the `--edit` option. The last expression will be returned, and the expected type is a `bool-array?`

**Comment by dariuscosden** [comment]
@WyattBlue thanks for the reply, could you show an example of how to do it? I've been looking at the docs and I'm not sure what the expression should be
