### ISSUE TITLE
How can I use two versions at the same time on the same computer?

### ISSUE THREAD

**Issue by yigexuezha** [WyattBlue/auto-editor#355]
How can I use the two version in the same computer?
I think some old version is good,can you help me?

**Comment by WyattBlue** [comment]
You can either:
1. Run one or more versions from source
1.  Use pyinstaller to create a standalone executable

If you're not a Python programmer / Already familiar with Python packaging, don't do this, it's not worth your ROI. Instead use one version at a time.
