### ISSUE TITLE
use auto-editor as call a function

### ISSUE THREAD

**Issue by ThetaRgo** [WyattBlue/auto-editor#360]
hello,thanks for your good job! well done! 

 i want to use auto-editor as call a function like:

from auto-editor import edit
res = edit(xxxx)

but how can i write it,and is there any test samples for debuging?

**Comment by vnmodapk** [comment]
i am editing all types of video though [VN mod apk ](https://vnapkmod.net/)

**Comment by WyattBlue** [comment]
I'm not interested in supporting using auto-editor as a library.
