### ISSUE TITLE
Translate Readme into Spanish

### ISSUE THREAD

**Issue by srd4** [WyattBlue/auto-editor#363]
Hi, I've been using the program a little bit to help me edit out these long streams of ESL lessons I'm giving a friend of mine. I saw a commit from a guy translating the Readme into Chinese being included. I was wondering if could do the same but in my native tongue, Spanish, since this script has been both very useful and probably will be for the rest of the Spanish-speaking community as well. I'm also a programmer wanting to begin to contribute to open source a bit. Thought this was a good and simple way of starting to work on something!!

Let me know if I'm good to go!

**Comment by WyattBlue** [comment]
PR Requests are welcome
