### ISSUE TITLE
Desync

### ISSUE THREAD

**Issue by MonzterDev** [WyattBlue/auto-editor#364]
### Bug description

This was initially discussed in the Discord here: https://ptb.discord.com/channels/711767814821773372/711774410721198134/1129367312907112509

When my margin is at anything below 6, the beginning of cut audio clips will be too far into the audio. So if I say "Now...", the clip will start at "ow.." and miss a part of the first word, or skip the first 1-2 words entirely.
When my margin is at 6, to fix the first issue, I'm them left with many clips starting with no audio for a few secs / millisecs
![image](https://github.com/WyattBlue/auto-editor/assets/36930553/9cfb82bd-f36e-4ce1-b02c-c53af5c9b1b7)
![image](https://github.com/WyattBlue/auto-editor/assets/36930553/5dc953fa-505b-4674-bbd8-e5063ee3770b)

Gif example: https://media.discordapp.net/attachments/711774410721198134/1129378313601830922/Resolve_mtYriOSbxD.gif?width=177&height=270

Sometimes the last word or part of the last word will be cut off. (https://i.imgur.com/IddGaYh.gif)
Sometimes a word within the sentence will get cut off mid-way through. (https://i.imgur.com/h3znypK.gif)

### What's your platform?

```shell
Python Version: 3.11.4 64-bit                                                                                           Platform: Windows 10 amd64                                                                                              FFmpeg Version: N-110322-g0c25da5a28-g1440bf15e2+1                                                                      FFmpeg Path: C:\Users\Monzt\AppData\Local\Programs\Python\Python311\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe      Auto-Editor Version: 23w15a
```

### What command did you use

```shell
auto-editor "C:\Users\Monzt\Videos\x.mp4" --margin 0.02s,0.06s --edit audio:stream=3,threshold=4% --export resolve
```

### What properties does your input video have?

 - video:
   - track 0:
     - codec: h264
     - fps: 30
     - resolution: 1920x1080
     - aspect ratio: 16:9
     - pixel aspect ratio: 1:1
     - duration: 32.933000
     - pix fmt: yuv420p
     - color range: tv
     - color space: bt709
     - color primaries: bt709
     - color transfer: bt709
     - timebase: 1/90000
     - bitrate: 4813553
     - lang: und
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 32.874000
     - bitrate: 93352
     - lang: und
   - track 1:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 32.874000
     - bitrate: 2271
     - lang: und
   - track 2:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 32.874000
     - bitrate: 2271
     - lang: und
   - track 3:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 32.874000
     - bitrate: 93177
     - lang: und
   - track 4:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 32.874000
     - bitrate: 93177
     - lang: und
   - track 5:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 32.874000
     - bitrate: 2271
     - lang: und
 - container:
   - duration: 32.933000
   - bitrate: 5135085

**Comment by WyattBlue** [comment]
I fixed this in 23w32a. The fix for the app is coming soon.
