### ISSUE TITLE
Add parameters to change video speed processing preset

### ISSUE THREAD

**Issue by HaiziIzzudin** [WyattBlue/auto-editor#365]
It is good to have parameters that can change video speed processing preset, yk the one with (-preset veryslow, slow, medium, fast, faster, veryfast, ultrafast)

Maybe a `--speed` params would do it.

Yes, it is what I need!

Yes I'm using the latest version, I just installed it couple hours ago.

**Comment by WyattBlue** [comment]
You can already set the video preset.
```
auto-editor file --extras "-preset fast"
```
