### ISSUE TITLE
final-cut-pro XML no longer imports into Davinci Resolve (Error: DaVinci Resolve supports Final Cut Pro X XML....)

### ISSUE THREAD

**Issue by mckayc** [WyattBlue/auto-editor#367]
### Bug description

I updated auto-editor the other day and now I can't import final-cut-pro .fcpxml files. When I try to do this I get the error: "DaVinci Resolve supports Final Cut Pro X XML 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9 and 1.10." 

![image](https://github.com/WyattBlue/auto-editor/assets/3774563/64b0b3bf-6260-4683-9910-7e9d9ce79d57)

(Note; I am running version 18.5 Build 41 of DaVinci resolve)

### What's your platform?

```shell
Python Version: 3.11.4 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-110322-g0c25da5a28-g1440bf15e2+1
FFmpeg Path: C:\Python311\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 23w32a
```

### What command did you use

```shell
auto-editor C:\filepath.mp4 --margin .05 'sec' --export final-cut-pro --edit audio:threshold=4%
```

### What properties does your input video have?

 - video:
   - track 0:
     - codec: h264
     - fps: 30
     - resolution: 1920x1080
     - aspect ratio: 16:9
     - pixel aspect ratio: 1:1
     - duration: 625.800000
     - pix fmt: yuv420p
     - color range: tv
     - color space: bt709
     - color primaries: reserved
     - color transfer: bt709
     - timebase: 1/15360
     - bitrate: 2632008
     - lang: und
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 625.801333
     - bitrate: 147267
     - lang: und
 - container:
   - duration: 625.801333
   - bitrate: 2786191

### Comments

I should note that the reason I am not exporting as "resolve" is because when I do that the audio and video is not linked as mentioned in #188 

Thanks!

**Comment by WyattBlue** [comment]
At the end of the day, `final-cut-pro` ***is for*** the Final Cut Pro application on MacOS and not any other.
Even if I did spend time making a patch to downgrade to 1.10, how would I know if final-cut-pro has a version of #188 also?
