### ISSUE TITLE
Add additional video on 

### ISSUE THREAD

**Issue by Justity** [WyattBlue/auto-editor#369]
Ability to add a second video to be added as another track on top of the first video

The video that will be on top must be cut in the same way as the main video

How does this come in handy, I am using your program to cut a video from twitch, I have two videos
1. Recording my screen
2. Recording only my chat
I want to be able to type in a title command before recording with the chat and get a fully synchronized version on the following track

**Comment by Justity** [comment]
![image](https://github.com/WyattBlue/auto-editor/assets/47537974/19850269-b737-4772-93dc-2f87bb4a0e74)
with new func 
![image](https://github.com/WyattBlue/auto-editor/assets/47537974/9d9ea341-69dc-46e8-8be9-5d91f9a9c181)

**Comment by WyattBlue** [comment]
I'm going to say no to this for now, because DaVinci Resolve always seems to implement 3rd party timeline imports in the laziest, half-assed way possible and I wouldn't be surprised if Resolve can't handle stacked multiple video streams like that in the picture.
