### ISSUE TITLE
Better --help

### ISSUE THREAD

**Issue by BroBryce64** [WyattBlue/auto-editor#372]
I would like better --help in the command line.  There is some basic help but it doesn't really explain the syntax of the values you'd give the various options (like 10sec, 110ms, -35dB etc).  Several examples per option should be provided so that people understand the usage, but no examples are provided.  

Couldn't this be done with something like "--help edit" or "--help progress" or something like that?

**Comment by WyattBlue** [comment]
You can already do `--edit --help` and `--progress --help`.
