### ISSUE TITLE
Command Line Preview in App?

### ISSUE THREAD

**Issue by BroBryce64** [WyattBlue/auto-editor#373]
The Windows APP is pretty intuitive, especially since you get to see very instant results of what your settings are right in the timeline preview.  It would be really nice, after you have all the settings tweaked JUST SO, if it would show a live status bar somewhere that included what the command line equivalent to these settings would be.

As I'm changing my settings in the Windows APP, a segment of the screen has a text box that shows what the command line would be if I were typing all this configuration into the command line.  Best case, there would also be a COPY button that would be clickable so that you could copy the text, maybe to put into a batch file or programmable macro (like Tourbox console or TypeItIn).  This would help the usability of the Windows App as well as give better context to the use of the command line options.

**Comment by WyattBlue** [comment]
I'm trying to make the app work less like the cli (more app like), so no, I'm not going to do this.
