### ISSUE TITLE
Save Default Settings

### ISSUE THREAD

**Issue by BroBryce64** [WyattBlue/auto-editor#375]
I'd love to see the program save default settings, or have the option to save different presets of settings.

Some of my videos are recorded using a teleprompter, and others are more naturally speaking.  Both environments would have dramatically different settings to achieve the desired result, but it would be challenging to remember what those settings were.  

For the command line, there could be a --savesettings PATHFILENAME and --settings PATHFILENAME and for the Windows app, those could maybe appear in a dropdown gadget or menu?   

Maybe it could just be a defaults.cfg file or something that sits in the program folder, and a user could edit it or swap them with a batch file or something, even if you didn't want to implement it as an option at the command line.

Either way, the cfg file could have comments in it to clarify what the settings mean, too.

**Comment by WyattBlue** [comment]
The nice thing about `cli`s is that they don't need all need to build this feature. You can create this yourself using aliases. In MacOS, you can just edit your `~/.zshrc` file and add something like `export ae='auto-editor --margin 3,3`

I don't remember what's the `zshrc` file equivalent for Windows off the top of my head but you can easily find it if you look it up.
