### ISSUE TITLE
Batch Video Processing

### ISSUE THREAD

**Issue by DrRedstoneYT** [WyattBlue/auto-editor#376]
I would like to be able to setup a bat file, or py file, in a specific folder, and be able to run that one file, and it can run (X) auto-editor command to all video files inside that folder. 

Setting up presets for certain video edits, where margins are bigger and smaller, and would be able to do all videos in a batch.  

This don't seem like something I need, more like something that is useful, sorry if it seems like a waste of time. 

Already up today! Loving this so far!! Also, sorry in advance, new here and couldn't find where I might be able to leave a comment/question, or a simple suggestion box! :)

**Comment by Cpyrighted** [comment]
You can already do this with auto-editor.

Here is code from a shell script I use on Pop-OS (Linux) to auto-batch edit a video folder similar can be acheived in windows using .bat and a for loop as this.

`for i in *.mp4; do auto-editor "${i%.*}.mp4" -b:v 4000K --margin 0.1sec; done`

**Comment by WyattBlue** [comment]
You can do this with a scripting language. This doesn't need to be built in to auto-editor
