### ISSUE TITLE
videospeed parameter desynch output

### ISSUE THREAD

**Issue by mlinaje** [WyattBlue/auto-editor#38]
First, thanks for your work.

I have tested it with some own videos and I get audio and video desynchronized output. As I was using many parameters to test, I isolated the parameter and it is -v, that desync output even when it is the only parameter used.
In my tests is nearly unnoticeable during the first seconds of the video, but it gets unusable video later.

As the desynch is gradual and as many people have this issue while accelerating videos with ffmpeg. This is the ffmpeg command I use to do it right:
ffmpeg -i name.mp4 -filter_complex "[0:v]setpts=0.8*PTS[v];[0:a]atempo=1.25[a]" -map "[v]" -map "[a]" name_accelerated.mp4
For sure it depends on the number of audio channels the video container has.

The main problem for most people is that 0.8 value as parameter, that it is not 0.75 (when you plan to accelerate to 125%). As 0.8*125%=1.

Best and keep working in this nice project!

**Comment by WyattBlue** [comment]
Thanks for report, I was able to reproduce your issue. I'll see if I can do something about this.

**Comment by WyattBlue** [comment]
I fixed this issue on 20w29a. The problem was that the audio was going too fast and misaligning with the video.

**Comment by mlinaje** [comment]
After this patch, when testing I get the following error:

> Traceback (most recent call last):
>   File "D:\workspace\videoIA\auto-editor\auto-editor.py", line 246, in <module>
>     process = subprocess.Popen([ffmpeg, '-i', path],
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1307, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

I tested path / INPUT_FILE variables and they contain the name and the extension as expected. 
I tested the problem also with example.mp4 in the same directory as autor-editor.py .

**Comment by WyattBlue** [comment]
That means you don't have ffmpeg installed, or it can't find the ffmpeg binary provided.

Try adding `--my_ffmpeg` to your command.
