### ISSUE TITLE
Make the user able to choose output file name when using export to XML

### ISSUE THREAD

**Issue by MythMega** [WyattBlue/auto-editor#383]
When you export to XML (to Premiere Pro, in my case), the names of all videos prepared for rendering will be "AUTO-EDITOR MEDIA GROUP." Something that can be very useful is a way to use the name that we want directly from the command line with arguments.

There are many ways and options to do that:
- Set a name by default from the original file's name (for example, `<filename>-auto-edited`).
- Allow the user to set an output name with arguments from the command line (for example, `auto-editor example.mp4 --export premiere --output cut.mp4`).

I'm processing videos in groups of 40 with script automation, but in the end, all files have the same filename. So, it's a bit frustrating to check each video just to rename it. So yeah, it would be something that I'll use, not something that can just be usefull sometime ahah.

**Comment by WyattBlue** [comment]
You can already do this.

```
auto-editor file.mp4 '--export premiere:name="Hello"'
```

**Comment by MythMega** [comment]
is there a problem with that syntax ?

![image](https://github.com/WyattBlue/auto-editor/assets/45936113/914b7182-c448-4aa7-96ef-bf2fb475994d)

**Comment by MythMega** [comment]
seems that premiere cannot be 'premiere'

![image](https://github.com/WyattBlue/auto-editor/assets/45936113/8d13df25-3b41-495d-824a-0dab5aed3bbe)
