### ISSUE TITLE
ModuleNotFoundError: No module named 'auto_editor'

### ISSUE THREAD

**Issue by gihanakalanka** [WyattBlue/auto-editor#384]
### Bug description

I got "zsh: command not found: auto-editor" on my mac and then I followed "manually adding the path" (I got "No such file or directory" error when try to run ls /usr/local/lib/python3.12/site-packages/ | grep auto )

Then I got this error when trying to run auto-editor

Traceback (most recent call last):
  File "/usr/local/bin/auto-editor", line 5, in <module>
    from auto_editor.__main__ import main
ModuleNotFoundError: No module named 'auto_editor' 

### What's your platform?

```shell
Traceback (most recent call last):
  File "/usr/local/bin/auto-editor", line 5, in <module>
    from auto_editor.__main__ import main
ModuleNotFoundError: No module named 'auto_editor'
```

### What command did you use

```shell
auto-editor
```

### What properties does your input video have?

auto-editor video_name.mp4 --export final-cut-pro

**Comment by WyattBlue** [comment]
auto-editor with Python3.12 is not ready yet. Trying using 3.11

**Comment by gihanakalanka** [comment]
Nice, It worked. thank you! 

By the way, when I use "--export final-cut-pro" and try to import the XML file to Final Cut Pro. I got error 

'The XML document sent from application “Final Cut Pro” could not be imported. DTD version is not recognized.'

But it work well when I just try to export as a new video.

**Comment by jurassicjordan** [comment]
I'm still having this issue even in python 3.10.14
