### ISSUE TITLE
mp3 output broken after Python 3.12

### ISSUE THREAD

**Issue by elgab** [WyattBlue/auto-editor#385]
## standard YT podcast cleaning ##

auto-editor input.m4a -o output.mp3
Error! Unknown encoder 'mp3'

### What's your platform?

```shell
Python Version: 3.12.0 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-110322-g0c25da5a28-g1440bf15e2+1
FFmpeg Path: C:\Users\johndoe\AppData\Local\Programs\Python\Python312\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 23w40a
```

### What command did you use

```shell
auto-editor input.m4a -o output.mp3
```

### What properties does your input video have?

standard youtube audio only. m4a,  format "140"

### Comments

auto-editor input.m4a    returns desired expected result.
with ffmpeg binary latest git works fine. the ffmpeg.exe shipped by python is not:

auto-editor --debug
Python Version: 3.12.0 64-bit
Platform: Windows 10 amd64
FFmpeg Version: 2023-10-09-git-37b5f4a1f6-full_build-www.gyan.dev
FFmpeg Path: C:\Users\johndoe\AppData\Local\Programs\Python\Python312\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 23w40a

**Comment by WyattBlue** [comment]
You can use the `--my-ffmpeg` flag to point to your ffmpeg with the `mp3` encoder compiled.
