### ISSUE TITLE
Timeline export to resove on mac work not correctly

### ISSUE THREAD

**Issue by antedoro** [WyattBlue/auto-editor#388]
### Bug description

`auto-editor example.mp4 --export resolve`

generates an xml that that it's possible to import on Davinci Resolve(Mac) but Davinci can't find the example.mp4 file.
May be xml don't link correctly to example.mp4 file

### What's your platform?

```shell
Python Version: 3.11.0 64-bit
Platform: Darwin 23.0.0 arm64
FFmpeg Version: N-110228-g4dffa564d1-6.0
FFmpeg Path: /Users/antedoro/Library/Python/3.11/lib/python/site-packages/ae_ffmpeg/Darwin-arm64/ffmpeg
Auto-Editor Version: 23w40a
```

### What command did you use

```shell
auto-editor example.mp4 --export resolve
```

### What properties does your input video have?

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'example.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.3.100
  Duration: 00:11:58.90, start: 0.000000, bitrate: 394 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 2560x1440 [SAR 1:1 DAR 16:9], 190 kb/s, 30 fps, 30 tbr, 90k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 191 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
At least one output file must be specified

**Comment by WyattBlue** [comment]
When I try to replicate this on my Mac, resolve finds the "example.mp4" file just fine.

I would make sure that you:
 * Using a recent version of auto-editor
 * Using a recent version of DaVinci Resolve
 * You are importing the fcpxml by going to "File > Import > Timeline"
