### ISSUE TITLE
WavError("Data exceeds wave file size limit") with 8 hour video

### ISSUE THREAD

**Issue by mWozDev** [WyattBlue/auto-editor#389]
(Make sure you're using the latest version)

Ran auto-editor against an 8 hour video. Usually it has no issues but today I received the following error:

`WavError("Data exceeds wave file size limit")`

From my research it looks like if the audio size is >4GB this comes up.

Is there any workaround known?

Here's the command I run usually:

```
        f'auto-editor "{full_path}"'
        f' --edit "audio:threshold=0.05"'
        f" --margin 0.2sec"
        f" --silent-speed 15"
        f" --video-speed 1.25"
        f' --output-file "{edited_path}"'
        f" --no-open"
```

on version: `23w38a (23.38.1)`

Apologies if I'm missing something obvious, I looked over the [supported media](https://auto-editor.com/docs/supported_media) link and it seems like this is supported.

Also a big thank you for this library, it's been able to help me tremendously.

**Comment by WyattBlue** [comment]
Fixed in 23w46a.
