### ISSUE TITLE
Small mismatch in the docummentation for zoom capabilities

### ISSUE THREAD

**Issue by mlinaje** [WyattBlue/auto-editor#39]
I don't plan to use zoom capabilities, but in the documentation seems to be a mismatch:

Command | --zoom_threshold
type | float_type
range | 0 to 1, 0% to 100%
default | 2, 200%

where values go from 0 to 1 (0% to 100%) and default is 2 (200%)

**Comment by WyattBlue** [comment]
I changed the documentation so that zoom range is 0-1.01 and zoom is defaulted to 1.01. Thanks :)
