### ISSUE TITLE
Error! Unknown encoder 'hevc'

### ISSUE THREAD

**Issue by Godor** [WyattBlue/auto-editor#391]
### Bug description

bug :
Error! Unknown encoder 'hevc'

Microsoft.HEVCVideoExtension_1.0.33242.0_x64__8wekyb3d8bbwe.Appx  is  installed

### What's your platform?

```shell
windows  10
```

### What command did you use

```shell
auto-editor  I:\xiaomi_camera\tang\2023093020.mp4
```

**Comment by WyattBlue** [comment]
For legal reasons we do not ship the `hevc` codec by default but you can still use it installing ffmpeg and then using auto-editor with the `--my-ffmpeg` flag.
