### ISSUE TITLE
Suggestion: API For this Library

### ISSUE THREAD

**Issue by jennsun** [WyattBlue/auto-editor#396]
It would be very helpful to be able to create an interface/API to use this library's features in addition to some existing code. Thank you!

**Comment by WyattBlue** [comment]
The v1 and v3 file formats are enough to enable advanced scripting. (auto-editor can read and write both of them)

**Comment by jennsun** [comment]
Could you elaborate on what you mean by this? Currently I have to specify a file from my local computer to edit, and the auto-editor will write to a new file with "_ALTERED" appended to the filename. There is a lack of flexibility for different input types (for example, via URL like other libraries support) and currently I am using a subprocess command to achieve this. Are there any resources you can point to regarding the v1/v3 file formats? Thank you so much!
