### ISSUE TITLE
Dosen't work for me when I use the --export option

### ISSUE THREAD

**Issue by touseef306** [WyattBlue/auto-editor#405]
### Bug description

auto-editor Untitled.mp4 --export resolve --margin 0.1sec
Error! Unknown option: --export

    Did you mean:
        -exp, --export_as_json, --export_as_audio

### What's your platform?

```shell
Python Version: 3.7.6 64-bit
Platform: Windows 10 amd64
FFmpeg path: c:\......packages\auto_editor\ffmpeg\Windows\ffmpeg.exe
FFmpeg version: 4.3
Auto-Editor version 22w02a
```

### What command did you use

```shell
auto-editor Untitled.mp4 --export resolve --margin 0.1sec
```

### What properties does your input video have?

'`auto-editor' is not recognized as an internal or external command,
operable program or batch file.

file: Untitled.mp4
 - video tracks: 1
   - Track #0
     - codec: h264
     - pix_fmt: yuv420p
     - time_base: 1/30000
     - fps: 30
     - resolution: 1920x1080 (16:9)
     - bitrate: 159 kb/s
     - lang: und
 - audio tracks: 1
   - Track #0
     - codec: aac
     - samplerate: 44100
     - bitrate: 160 kb/s
     - lang: und
 - container:
   - duration: 00:17:25.71
   - bitrate: 321 kb/s

**Comment by WyattBlue** [comment]
You're using an older version of auto-editor that does not have the `resolve` option.

To upgrade, first install Python 3.12 from [python.org](https://python.org), then run `pip install auto-editor==23.46.1`
Python 3.7 is "end of life", so I would just uninstall it first to avoid confusion.
