### ISSUE TITLE
Output Fİle Size

### ISSUE THREAD

**Issue by sbayrakli** [WyattBlue/auto-editor#415]
My input file size is 254MB (Vİdeo bitrate: 910 kbps)
I run auto editor with the default settings as "auto-editor file.mp4"
the output image quality is the same but the file size is approx. 5 times bigger than the input size!
when I manually set the output bit rate same as the inputs', image quality decreases a lot.

how can I solve this problem?

**Comment by WyattBlue** [comment]
See https://auto-editor.com/docs/file-size
