### ISSUE TITLE
Error! Unable to parse option value "bt470bg"

### ISSUE THREAD

**Issue by tchansun** [WyattBlue/auto-editor#417]
### Bug description

This is the error I get with a simple auto-editor filename.mp4 command

### What's your platform?

```shell
Python Version: 3.12.1 64-bit
Platform: Windows 11 amd64
FFmpeg Version: N-110322-g0c25da5a28-g1440bf15e2+1
FFmpeg Path: C:\Users\fred\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 23w51a
```

### What command did you use

```shell
auto-editor filename.mp4
```

### What properties does your input video have?

.\Short1.mp4:
 - video:
   - track 0:
     - codec: h264
     - fps: 25
     - resolution: 1920x1080
     - aspect ratio: 16:9
     - pixel aspect ratio: 1
     - duration: 69.44
     - pix fmt: yuv420p
     - color range: tv
     - color space: smpte170m
     - color primaries: bt709
     - color transfer: bt470bg
     - timebase: 1/12800
     - bitrate: 4996338
     - lang: und
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 48000
     - channels: 1
     - duration: 69.354
     - bitrate: 179993
     - lang: und
 - container:
   - duration: 69.44
   - bitrate: 5182477

.\Short1.mp4:
 - video:
   - track 0:
     - codec: h264
     - fps: 25
     - resolution: 1920x1080
     - aspect ratio: 16:9
     - pixel aspect ratio: 1
     - duration: 69.44
     - pix fmt: yuv420p
     - color range: tv
     - color space: smpte170m
     - color primaries: bt709
     - color transfer: bt470bg
     - timebase: 1/12800
     - bitrate: 4996338
     - lang: und
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 48000
     - channels: 1
     - duration: 69.354
     - bitrate: 179993
     - lang: und
 - container:
   - duration: 69.44
   - bitrate: 5182477

### Comments

I tried with another ffmpeg (--ffmpeg-location) but same error.

with --show-ffmpeg-output :

[NULL @ 00000170a7a4ad80] [Eval @ 00000023a5ffe218] Undefined constant or missing '(' in 'bt470bg'
[NULL @ 00000170a7a4ad80] Unable to parse option value "bt470bg"
[NULL @ 00000170a7a4ad80] Error setting option color_trc to value bt470bg.
[vost#0:0/copy @ 00000170a7a4aa80] Error setting up codec context options.

Thank you!

**Comment by Drive4Code** [comment]
I've found a workaround that helped me:

Add --extras "-color_primaries bt470bg -color_trc gamma28 -colorspace bt470bg" to to the auto-editor command

**Comment by tchansun** [comment]
Thank you, it works !

**Comment by Drive4Code** [comment]
No problem. I still think its an issue worth leaving open and investigating though because it shouldn't happen in the first place
