### ISSUE TITLE
Better detection of s - sound.

### ISSUE THREAD

**Issue by MilkAndBanana1** [WyattBlue/auto-editor#419]
Have been using this heavily with my projects and have noticed that the audio cuts off too early in cases where a word ends with an S at the end of the phrase. 

It could be a parameter where it has a threshold of how likely the end timestamp of loud has an S sound or not and if there is, lower the loud threshold until a certain point so the s sound passes through before adding the timestamp.

**Comment by ErikVogelLUH** [comment]
Isn't that what the margin keyword ist for?

**Comment by MilkAndBanana1** [comment]
> Isn't that what the margin keyword ist for?

I do have the margin fairly low so and I believe I was most likely just pushing this to a point where it's not really designed for it since this is made with manual editing still in mind. If one day I have enough knowledge to do this I have an idea of potentially having a toggle for adding some sort of phoneme detection specifically before the beginning of silences and then cross referencing it with just the regular silence trim parameters.

I believe this is probably not something the program should have since I think its best to make this a fork rather than an actual feature in this project.

**Comment by R4GN3R0** [comment]
Hello, is there any guidance to deliberatly not cut s sounds that aggresive?
In my videos I cut I have problems with words like "process" .
