### ISSUE TITLE
Issue with Missing First Segment when Exporting to Final Cut Pro XML

### ISSUE THREAD

**Issue by richylimyy** [WyattBlue/auto-editor#420]
### Summary:
I've recently started using auto-editor and have found it to be extremely handy, so first of all, thank you for developing this tool. However, I've encountered an issue when exporting projects to Final Cut Pro XML format.

### Details:
- When exporting the edited video as an FCPXML file for use in Final Cut Pro, the first non-silent segment of the video is consistently missing. This seems to occur regardless of the video file or settings used.
- Interestingly, when exporting the same project as a video file (e.g., MP4), everything works perfectly fine, and the first segment is included as expected.
- Upon inspecting the generated FCPXML file, I noticed that the first segment does not have a 'start' tag, which might be contributing to the issue.

### What's your platform?

```shell
Python Version: 3.12.0 64-bit
Platform: Darwin 23.2.0 arm64
FFmpeg Version: N-110228-g4dffa564d1-6.0
FFmpeg Path: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ae_ffmpeg/Darwin-arm64/ffmpeg
Auto-Editor Version: 24w03a
```

### What command did you use

```shell
auto-editor "{mp4 file}" --margin 0.03s,0.3s --export final-cut-pro --edit audio:-19dB"
```

### What properties does your input video have?

auto-editor info "video.mp4"
video.mp4:
 - video:
   - track 0:
     - codec: h264
     - fps: 60
     - resolution: 1920x1080
     - aspect ratio: 16:9
     - pixel aspect ratio: 1
     - duration: 20.033984375
     - pix fmt: yuv420p
     - color range: tv
     - color space: bt709
     - color primaries: bt709
     - color transfer: bt709
     - timebase: 1/15360
     - bitrate: 3289415
     - lang: und
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 44100
     - channels: 2
     - duration: 20.003990929705214
     - bitrate: 128013
     - lang: eng
 - container:
   - duration: 20.033984
   - bitrate: 4213254

ffmpeg -hide_banner -i "video.mp4"
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.3.100
  Duration: 00:00:20.03, start: 0.000000, bitrate: 4213 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 3289 kb/s, 60 fps, 60 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]

### Comments

I appreciate any guidance or fixes you can provide for this issue. Thank you for your support and for the great work on this tool!

**Comment by WyattBlue** [comment]
This sounds like #425 (DaVinci Resolve and FCP use the same backend). Try what I recommend there and see if it works.
