### ISSUE TITLE
Cannot edit video by motion

### ISSUE THREAD

**Issue by ErikVogelLUH** [WyattBlue/auto-editor#421]
### Bug description

I wanted to try editing by motion and used a command from the README:

`auto-editor .\test.mkv --edit motion:-19dB --no-open`

After some time I get this line in the console

`Error! Trying to render empty audio timeline`

### What's your platform?

```shell
`Python Version: 3.11.5 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-110322-g0c25da5a28-g1440bf15e2+1
FFmpeg Path: C:\Users\<MyName>\AppData\Local\Programs\Python\Python311\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 24w03a`
```

### What command did you use

```shell
`auto-editor .\test.mkv --edit motion:-19dB --no-open`
```

### What properties does your input video have?

`Input #0, matroska,webm, from '.\test.mkv':
  Metadata:
    ENCODER         : Lavf60.6.100
  Duration: 00:10:00.01, start: 0.000000, bitrate: 6430 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 3840x2160, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 00:09:59.999000000
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 00:10:00.008000000`

**Comment by WyattBlue** [comment]
You're getting this error message because auto-editor doesn't see any motion that's above your threshold. When you try to render, it stops because otherwise it would make an empty file.

Try lowering your motion threshold. You can also use `--preview` to see a breakout of the cuts.
