### ISSUE TITLE
Resolve Export Start Not Synced

### ISSUE THREAD

**Issue by wudanbal** [WyattBlue/auto-editor#425]
https://github.com/WyattBlue/auto-editor/blob/70f2109774e84fcc36ec75e38d09e827f56710e7/auto_editor/formats/fcp11.py#L146C1-L147C41

Hey Team -- First off, immensely grateful for you work. But can your team take a look at the line referenced. All of my resolve imports has been out of sync on the first cut. I believe the line referenced is the culprit. I'm sure there could be some reason for this that I'm missing, but when I pulled down the project and fixed that line, my imports to Resolve worked correctly. Can you team take a look. Thanks in advance.

**Comment by WyattBlue** [comment]
I don't see any reason for that line to be there, so I removed it. You can try the new version by running:
```
pip uninstall auto-editor
pip install git+https://github.com/WyattBlue/auto-editor.git
```

**Comment by wudanbal** [comment]
Thank you sir, you rock!
