### ISSUE TITLE
Adobe premiere cuts -Special Gurk

### ISSUE THREAD

**Issue by GurksGithub** [WyattBlue/auto-editor#431]
### Bug description

When auto editor cuts the video *which is 3 hours long* the cuts are inbetween the audio and not properly cut when exporting to Adobe Premiere. When I render the video in the auto editor app it works well.. but i need this exported to premiere but anytime i do that it cuts at random areas 
![image](https://github.com/WyattBlue/auto-editor/assets/107278166/5ef0cff6-bb55-4906-9d23-cd1d2026d118)

### What's your platform?

```shell
Im using the application
```

### What command did you use

```shell
https://prnt.sc/i5vu_Ka8UdPu
```

**Comment by WyattBlue** [comment]
What's the framerate and samplerate of your video?
One way to get this is to install the auto-editor cli then run `auto-editor info your-vid.mp4`

**Comment by GurksGithub** [comment]
so i cut the file down to 40 minutes and ran it thru with the same settings and now it works i wonder why if its very very long like 3 hours it messes up

**Comment by WyattBlue** [comment]
> so i cut the file down to 40 minutes and ran it thru with the same settings and now it works i wonder why if its very very long like 3 hours it messes up

Maybe the desync is only noticeable when a large stretch of time has passed and 40 minutes isn't enough time.
If there was a desync before 40mins before but not for the shorter vid, then maybe the re-encoding fixed something.
