### ISSUE TITLE
scale down not faster?

### ISSUE THREAD

**Issue by aaaboypop** [WyattBlue/auto-editor#433]
### Bug description

i have video is large than i want
i'm try to use -scale but it's not effect much, -res is slower
if i resize down before use, it's significant faster.

### What's your platform?

```shell
Python Version: 3.11.5 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-110322-g0c25da5a28-g1440bf15e2+1
FFmpeg Path: C:\Users\PONDX\anaconda3\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 24w03a
```

### What command did you use

```shell
auto-editor vid_1080p60.mp4
Finished. took 128.18 seconds (0:02:08)

auto-editor vid_540p60.mp4
Finished. took 30.8 seconds (0:00:31)

auto-editor vid_1080p60.mp4 --scale 0.5
Finished. took 110.5 seconds (0:01:50)

auto-editor vid_1080p60.mp4 -res 960,540
Finished. took 237.5 seconds (0:03:58)
```

**Comment by WyattBlue** [comment]
I don't think scaling down not being faster is an issue. Auto-Editor still have to decode a big input video then apply some resizing algorithm so I don't think this is an unexpected result.
