### ISSUE TITLE
Premiere: voice channels are disabled

### ISSUE THREAD

**Issue by a0m0rajab** [WyattBlue/auto-editor#439]
### Bug description
 I have tried to export it to premiere and using the XML file in premiere pro, premiere pro accepts the file but it disables ones of the audio channel, when I try to enable all of the audio channels in premiere it crashes. 

### What's your platform?
```shell
Python Version: 3.11.0 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-110322-g0c25da5a28-g1440bf15e2+1
FFmpeg Path: \Windows\ffmpeg.exe
Auto-Editor Version: 24w07a
```

### What command did you use

```shell
--export premiere
```

**Comment by WyattBlue** [comment]
Are you using the latest version of premiere?

**Comment by a0m0rajab** [comment]
yes,

**Comment by WyattBlue** [comment]
I think I've solved this. You can wait for the release or use master:
```
pip uninstall auto-editor
pip install git+https://github.com/WyattBlue/auto-editor.git
```

**Comment by a0m0rajab** [comment]
Thanks will check this out when I can, 

Just for reference I am adding the related commit: 
https://github.com/WyattBlue/auto-editor/commit/f585e292d2570d106d040e4b717aa5ef84a8706b
