### ISSUE TITLE
Premiere: lagging when using the exported file

### ISSUE THREAD

**Issue by a0m0rajab** [WyattBlue/auto-editor#440]
### Bug description

After having [the audio channel issue](https://github.com/WyattBlue/auto-editor/issues/439) I thought to export the video file from auto editor and use it in premiere pro. This method provided me the correct voice channels working yet when I imported the file to premiere pro it started to lag and have issues and close the program. 

I think it's related to the output file from autoeditor since I am not facing any issues when I use the original video file.  

### What's your platform?

```shell
NA
```

### What command did you use

```shell
NA
```

**Comment by a0m0rajab** [comment]
@WyattBlue sorry, but what makes this closed? is there a solution for this or am I missing something in the docs?

**Comment by WyattBlue** [comment]
I closed it because I think solving #439 would solve this.

**Comment by a0m0rajab** [comment]
@WyattBlue here I exported the file into an .MP4 instead of XML, using the mp4 file was laggy on premiere pro and even on normal video softwares like windows media player 😅
