### ISSUE TITLE
Soft Cut Option

### ISSUE THREAD

**Issue by DeysonOrtiz** [WyattBlue/auto-editor#443]
Hello and good day!🙂

Question, would it be possible to add the option of adding a soft cut between edit.
A dissolve of 3-5 frames would help soften the cuts and not be as jarring on some edits. 

Please let me know what you think. 🤔
Thank you and have an Incredible Day. 🙂

**Comment by petermg** [comment]
I think something like that is well beyond the scope of this application. However what you could do is just increase the frames between cuts, then just take the output video into a video editor and snip between the cuts and manually do the transition effect. Again, I think this feature is very outside the scope of this application.

**Comment by DeysonOrtiz** [comment]
I completely, understand.  
I wonder if this is something we could do automatically with FFMPEG, take the XML and turn it into an EDL for FFMPEG. 
Time to do some testing.  🙂

Thank you and have an Outstanding Day. 🙂

**Comment by WyattBlue** [comment]
Adding dissolves is not a priority at this time.

**Comment by WyattBlue** [comment]
Auto-Editor 31.3.0 now supports dissolve transitions via the `--transition` option.
