### ISSUE TITLE
24w07a breaks VEGAS Pro support

### ISSUE THREAD

**Issue by MrRockis** [WyattBlue/auto-editor#445]
### Bug description

When using 24w07a the editor does not create the "filename_tracks" folder and the xml import does not work on vegas pro 20. 

Error:
[2024-03-04 15-54-05_ALTERED.xml_5-3-2024_23-37-36.log](https://github.com/WyattBlue/auto-editor/files/14501798/2024-03-04.15-54-05_ALTERED.xml_5-3-2024_23-37-36.log)

When downgrading to version 24w03a everything works perfectly and the filename_tracks folder is created as well.

### What's your platform?

```shell
Python Version: 3.12.2 64-bit
Platform: Windows 11 amd64
FFmpeg Version: N-110322-g0c25da5a28-g1440bf15e2+1
FFmpeg Path: C:\Users\MrRockis\AppData\Local\Programs\Python\Python312\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 24w07a
```

### What command did you use

```shell
auto-editor "2024-03-04 15-54-05.mp4" --edit audio:stream=1 --margin 0.1s --export premiere
```

## auto-editor info "2024-03-04 15-54-05.mp4"
2024-03-04 15-54-05.mp4:
 - video:
   - track 0:
     - codec: h264
     - fps: 60
     - resolution: 2560x1440
     - aspect ratio: 16:9
     - pixel aspect ratio: 1
     - duration: 4594.0
     - pix fmt: yuv420p
     - color range: tv
     - color space: bt709
     - color primaries: bt709
     - color transfer: bt709
     - timebase: 1/15360
     - bitrate: 25000191
     - lang: und
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 4593.984
     - bitrate: 131855
     - lang: und
   - track 1:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 4593.984
     - bitrate: 117771
     - lang: und
   - track 2:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 4593.984
     - bitrate: 2271
     - lang: und
 - container:
   - duration: 4594.0
   - bitrate: 25275523
   
## ffmpeg -hide_banner -i "2024-03-04 15-54-05.mp4"
   Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '2024-03-04 15-54-05.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.3.100
  Duration: 01:16:34.00, start: 0.000000, bitrate: 25275 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 2560x1440 [SAR 1:1 DAR 16:9], 25000 kb/s, 60 fps, 60 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 131 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 117 kb/s
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:3[0x4](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]

**Comment by WyattBlue** [comment]
I don't want to support Sony Vegas separately. If it's not not compatible with the way Premiere Pro reads fcpxml7, I don't want to support it. I've changed the readme so that it's no longer implied that Sony Vegas will understand the Premiere Pro Export.

**Comment by WyattBlue** [comment]
Auto-Editor supports VEGAS Pro via `--export resolve-fcp7` now.
