### ISSUE TITLE
Sequence naming inside Premiere Pro

### ISSUE THREAD

**Issue by unsky559** [WyattBlue/auto-editor#446]
Hello! I really enjoy using your montage app, thank you for developing it.
Currently, importing to premiere from the command line my `.xml` files creates a sequence called "Auto-Editor Media" (see screenshot what I mean)

![image](https://github.com/WyattBlue/auto-editor/assets/33353900/219be8c3-fce0-4857-829c-0707569cee2d)

I would like to be able to specify this name from the command line. 
Or it would be better if this name in the premiere corresponds to the name of the input file. 
![image](https://github.com/WyattBlue/auto-editor/assets/33353900/282a9dae-d7ab-4b1b-b613-6239fb1fb107)
It would be more convenient to see such a name when I have hundreds of such compositions in my project.

**Comment by WyattBlue** [comment]
You can rename sequences with `--edit 'premiere:name="My Name"'`

**Comment by unsky559** [comment]
Hello! Unfortunately, it doesn't work. I also tried the --edit option, and as stated in your readme file, none of that helped.

```cmd
>> auto-editor "Record5\2024-03-09 19-50-39.mp4" --margin 0.1s --export 'premiere:name="2024-03-09 19-50-39.mp4"' --edit 'audio:stream=1'
<< Error! ''premiere': Export must be [default, premiere, resolve, final-cut-pro, shotcut, json, timeline, audio, clip-sequence]
```

**Comment by WyattBlue** [comment]
If you have this error, you are experiencing a skill issue. Learn the escape sequences for  `premiere:name="Your name here"` in your shell.
