### ISSUE TITLE
My Premiere don't show the Cuts in the OG video

### ISSUE THREAD

**Issue by Zhanyee** [WyattBlue/auto-editor#449]
### Bug description

When I say to export to premiere, it creates an XML file, but when I import it to premiere, the video is just one big file, without the small cuts that some youtubers shown on their videos, now I don't know if that is a feature or not.
![image](https://github.com/WyattBlue/auto-editor/assets/127443718/30969041-66ea-4bb4-bd8d-fb35b35d6dbe)

### What's your platform?

```shell
Python Version: 3.11.8 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-110322-g0c25da5a28-g1440bf15e2+1
FFmpeg Path: C:\Users\aquel\AppData\Local\Programs\Python\Python311\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 24w09a
```

### What command did you use

```shell
auto-editor "video.mp4" --export premiere
```

**Comment by WyattBlue** [comment]
I think you need to double click the track to see the clips. Obviously, if there still aren't cuts, something isn't working right. You should media export and make sure auto-editor is applying cuts. If not, you should try changing the thresholds.
