### ISSUE TITLE
'hevc_nvenc' codec is not supported in 'MP4' container.

### ISSUE THREAD

**Issue by petermg** [WyattBlue/auto-editor#451]
### Bug description

This used to work but now it gives me this error when trying to output an mp4 using the GPU codec hevc_nvenc. It still works for mkv however.

### What's your platform?

```shell
Python Version: 3.9.8 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-110322-g0c25da5a28-g1440bf15e2+1
FFmpeg Path: C:\Users\pgomb\AppData\Local\Programs\Python\Python39\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 23w32a
```

### What command did you use

```shell
from a bat file:

auto-editor %1 --edit audio:stream=0,threshold=0.03 --my-ffmpeg --debug -c:v hevc_nvenc -m 5,30
```

### What properties does your input video have?

[aist#0:1/pcm_s16be @ 000001e158368080] Guessed Channel Layout: stereo
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\videos\AutoEditor\C0245.MP4':
  Metadata:
    major_brand     : XAVC
    minor_version   : 16785407
    compatible_brands: XAVCmp42iso2
    creation_time   : 2022-06-14T03:33:15.000000Z
  Duration: 00:05:11.81, start: 0.000000, bitrate: 51989 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 49960 kb/s, 59.94 fps, 59.94 tbr, 60k tbn (default)
    Metadata:
      creation_time   : 2022-06-14T03:33:15.000000Z
      handler_name    : Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1[0x2](und): Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, 2 channels, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2022-06-14T03:33:15.000000Z
      handler_name    : Sound Media Handler
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (rtmd / 0x646D7472), 491 kb/s (default)
    Metadata:
      creation_time   : 2022-06-14T03:33:15.000000Z
      handler_name    : Timed Metadata Media Handler
      timecode        : 00:05:14:50

**Comment by WyattBlue** [comment]
I think you've accidentally used an old version of auto-editor. The codec works fine in the latest release.

**Comment by petermg** [comment]
> I have the same problem using 24w13a (24.13.1) version and hevc codec (no external GPU in my case).
> 
> Error: "Error! Unknown encoder 'hevc' "

Without a supported Nvidia GPU this result is EXPECTED. So in your case this is NOT a bug.
