### ISSUE TITLE
Cut without motion only but keep the silence

### ISSUE THREAD

**Issue by mauamolat** [WyattBlue/auto-editor#456]
I'm not sure if it already supports this but I would like to request for a feature to cut without motion only but keep the silence.

I make videos without voice over or audio, so I only want to cut the motionless portions if possible. I know you already support it but to my knowledge it is only an additional feature where silence and the motionless portions are removed. I do not want to remove the silence while there are motion.

Thank you.

**Comment by WyattBlue** [comment]
You can already do this. I think you either want:
`--edit "(or motion:0.05 audio:0.04)"`
or
`--edit "(or motion:0.05 (not audio:0.04))"`
