### ISSUE TITLE
Applying changes to nested sequence in XML

### ISSUE THREAD

**Issue by TCNOco** [WyattBlue/auto-editor#457]
This software is fantastic and saves me a lot of time.

I export as XML to use in Premiere Pro. Works fantastically.

My request: A toggle when exporting to XML to apply changes to a sequence containing the video, instead of the video itself. A nested sequence.

Why? Working with other video tracks (webcam, other cameras/angles) and multiple audio tracks, or applying changes to the entire video is difficult if not impossible. There are so many cuts in a video, syncing an entire new track over it is very difficult.

As in:
Instead of the main video/audio track being split into sections, the main video/audio track is in a sequence, and the splits applied to the sequence. Applying a LUT, pre-rendering, adding an overlay, timer, other camera angles, audio tracks, or even using an entirely different sequence in a videos place for multiple camera angles and more would be incredibly powerful.

I'm looking at the output XML, as well as exporting XML from Premiere (File > Export > Final Cut Pro XML...), but haven't figured it all out or I would create another simple script to help

**Comment by WyattBlue** [comment]
I don't have any immediate plans for this feature.
