### ISSUE TITLE
Audio Extraction takes extraordinarily long to extract audio from multi audio track video (1hour in length)

### ISSUE THREAD

**Issue by jurassicjordan** [WyattBlue/auto-editor#461]
### Bug description

AutoEditor seems to get stuck or freezes when extracting audio, taking about an hour just for one track.

### What's your platform?

```shell
Python Version: 3.11.9 64-bit
Platform: Linux 6.8.5-zen1-1-zen x86_64
FFmpeg Version: 4.2.2
FFmpeg Path: /home/jordancruz/anaconda3/envs/AutoEditor/bin/ffmpeg
Auto-Editor Version: 24w13a

running under conda because my primary install of python is 3.12, which is too new.
```

### What command did you use

```shell
auto-editor /run/media/jordancruz/WorkDrive/Video Workspace/Footage/2023-01-26_22-44-33.mov --edit audio:stream=all --export resolve

and

auto-editor /run/media/jordancruz/WorkDrive/Video Workspace/Footage/2023-01-26_22-44-33.mov --edit audio:stream=all --export premiere
```

### What properties does your input video have?

auto-editor info
 - video:
   - track 0:
     - codec: mjpeg
     - fps: 60
     - resolution: 1920x1080
     - aspect ratio: 16:9
     - pixel aspect ratio: 1
     - duration: 3349.7
     - pix fmt: yuvj420p
     - color range: 2 (pc)
     - color space: 5
     - color primaries: 1 (bt709)
     - color transfer: 1 (bt709)
     - timebase: 1/15360
     - bitrate: 115668739
 - audio:
   - track 0:
     - codec: pcm_s16be
     - samplerate: 44100
     - channels: 2
     - duration: 3349.664217687075
     - bitrate: 1411200
   - track 1:
     - codec: pcm_s16be
     - samplerate: 44100
     - channels: 2
     - duration: 3349.664217687075
     - bitrate: 1411200
   - track 2:
     - codec: pcm_s16be
     - samplerate: 44100
     - channels: 2
     - duration: 3349.664217687075
     - bitrate: 1411200
 - container:
   - duration: 3349.7
   - bitrate: 119918495

ffmpeg

  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    encoder         : Lavf60.16.100
  Duration: 00:55:49.70, start: 0.000000, bitrate: 119918 kb/s
    Stream #0:0: Video: mjpeg (Baseline) (jpeg / 0x6765706A), yuvj420p(pc, bt470bg/bt709/bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 115668 kb/s, 60 fps, 60 tbr, 15360 tbn, 15360 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc60.31.102 mjpeg
    Stream #0:1: Audio: pcm_s16be (twos / 0x736F7774), 44100 Hz, stereo, s16, 1411 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2: Audio: pcm_s16be (twos / 0x736F7774), 44100 Hz, stereo, s16, 1411 kb/s
    Metadata:
      handler_name    : SoundHandler
    Stream #0:3: Audio: pcm_s16be (twos / 0x736F7774), 44100 Hz, stereo, s16, 1411 kb/s
    Metadata:
      handler_name    : SoundHandler

### Comments

It has been a while since I've used auto editor, but I don't remember it being this long of a wait

**Comment by WyattBlue** [comment]
Your ffmpeg is too old. Use ffmpeg 6. We support Python3.12 now. I'm not suprised it's taking so long because of `codec: mjpeg` and `pix fmt: yuvj420p`. You should use more normal formats like h264 and aac and let your hardware accel do the rest, which should be used by default.
