### ISSUE TITLE
folder creating

### ISSUE THREAD

**Issue by d-s-t** [WyattBlue/auto-editor#47]
when running on the same folder twice, the software remove everything from the existing folder in the second run, even though there are no files with the same name.

**Comment by WyattBlue** [comment]
What commands are you using?

**Comment by d-s-t** [comment]
I use ```
python auto-editor.py "media_folder_path" 
```

**Comment by WyattBlue** [comment]
I tested running that command twice and I can't replicate that error. See if the error still is there on the latest version of auto-editor.

**Comment by WyattBlue** [comment]
I'll close this in a few days if no more context is provided. I can't recreate this bug, nor seeming anyone else.
