### ISSUE TITLE
Using audio threshold and custom silent speed together makes rendering super slow

### ISSUE THREAD

**Issue by ErikVogelLUH** [WyattBlue/auto-editor#470]
### Bug description

When you define a custom audio threshold and a custom silent speed, exporting the video becomes super slow. I always use h264_nvenc together with --my-ffmpeg, because else it is even slower. The ETA goes way up during the encoding process. In the task manager I can see that my GPU only has small spikes of video encoding. With default option auto-editor fully utilizes my GPU. Over the process of the rendering I can see that the spikes become less frequent and more spaced out. At the same time the ETA goes up

### What's your platform?

```shell
Python Version: 3.11.4 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-110322-g0c25da5a28-g1440bf15e2+1
FFmpeg Path: C:\Program Files\Python311\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 24w19a
```

### What command did you use

```shell
auto-editor '.\video.webm' -c:v h264_nvenc --no-open --my-ffmpeg -s 5 --edit "audio:threshold=7%" -o video_out.mkv
```

### What properties does your input video have?

 - video:
   - track 0:
     - codec: vp9
     - fps: 24000/1001
     - resolution: 1920x1080
     - aspect ratio: 16:9
     - pixel aspect ratio: 1
     - pix fmt: yuv420p
     - color range: 1 (tv)
     - color space: 1 (bt709)
     - color primaries: 1 (bt709)
     - color transfer: 1 (bt709)
     - timebase: 1/1000
     - lang: eng
 - audio:
   - track 0:
     - codec: opus
     - samplerate: 48000
     - channels: 2
     - lang: eng
 - container:
   - duration: 1545.988
   - bitrate: 261192
   - 
Input #0, matroska,webm, from '.\video.webm':
  Metadata:
    ENCODER         : Lavf60.6.100
  Duration: 00:25:45.99, start: 0.000000, bitrate: 261 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      DURATION        : 00:25:45.961000000
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 00:25:45.988000000

**Comment by WyattBlue** [comment]
I can replicate this, will figure out a fix soon.

**Comment by WyattBlue** [comment]
2612980838ca3495b0845274177a3ff57e679e5c fixes this.
