### ISSUE TITLE
Importing to Resolve Error

### ISSUE THREAD

**Issue by MonzterDev** [WyattBlue/auto-editor#472]
### Bug description

When importing into Resolve the timeline is very...odd. I believe the image does a better job of explaining it than words. 

I've tried a few ways of importing into Resolve, but my primary way is:
- Right click the Media Pool
- Hover over Timelines
- Hover over Import
- Select the AAF / EDL / XML / etc option
- Select the `.fcpxml` file

Once the Load XML... screen pops up, I do not adjust any of the [settings](https://imgur.com/oJH3h55).

![DaVinci_Resolve_Studio_-_Obby_Ep_19-06-13-24_18-14-24](https://github.com/WyattBlue/auto-editor/assets/36930553/c06c467e-4715-44d9-950f-d8feeb669bae)

### What's your platform?

```shell
Python Version: 3.11.5 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-110322-g0c25da5a28-g1440bf15e2+1
FFmpeg Path: C:\Users\X\AppData\Local\Programs\Python\Python311\Lib\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 24w03a
```

### What command did you use

```shell
"C:\Users\X.mp4" --margin 0.05s,0.15s --edit audio:stream=0,threshold=-40dB,mincut=7,minclip=1 --export resolve
```

### What properties does your input video have?

 - video:
   - track 0:
     - codec: h264
     - fps: 87169000/2905633
     - resolution: 1920x1080
     - aspect ratio: 16:9
     - pixel aspect ratio: 1
     - duration: 2905.633
     - pix fmt: yuv420p
     - color range: tv
     - color space: bt709
     - color primaries: bt709
     - color transfer: bt709
     - timebase: 1/90000
     - bitrate: 731771
     - lang: und
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 2905.578
     - bitrate: 106048
     - lang: und
   - track 1:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 2905.578
     - bitrate: 159882
     - lang: und
   - track 2:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 2905.578
     - bitrate: 2274
     - lang: und
   - track 3:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 2905.578
     - bitrate: 2277
     - lang: und
   - track 4:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 2905.578
     - bitrate: 2274
     - lang: und
   - track 5:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 2905.578
     - bitrate: 2274
     - lang: und
 - container:
   - duration: 2905.633
   - bitrate: 1041338

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\X.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.16.100
  Duration: 00:48:25.63, start: 0.000000, bitrate: 1041 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 731 kb/s, 30 fps, 30 tbr, 90k tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 106 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 159 kb/s
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
  Stream #0:3[0x4](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
  Stream #0:4[0x5](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
  Stream #0:5[0x6](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
  Stream #0:6[0x7](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
At least one output file must be specified

### Comments

This happens both with the CLI & GUI versions.

**Comment by WyattBlue** [comment]
Hello, sorry you're having problems.

For the CLI, try using the latest version. I've changed how the Resolve export works since then.

```
pip install -U auto-editor
```

**Comment by MonzterDev** [comment]
Hey, that did solve this thanks. Although, an issue I'm not encountering is that the video clips aren't linked with their audio tracks. Would that be something you'd consider looking into? If so, should I open a separate issue?

Also, unrelated to the issue... I am using the GUI with Mincut & Minclip set using decimals, so 0.7 / 0.4 in my case, but the CLI only seems to use whole numbers. I considered using 7 / 4 for the CLI would give me the same results, but they did not.

**Comment by WyattBlue** [comment]
Sure, you can make a separate issue.

For the CLI, mincut and minclip are in "timebase" units. If you wanted to set 0.7 seconds, the value in "timebase" units would multiply 0.7 by your video's fps.
```python
fps = 30
round(0.7 * fps)
>>> 21  # This is the number you would set
```
