### ISSUE TITLE
Naming Timelines

### ISSUE THREAD

**Issue by ostvk** [WyattBlue/auto-editor#473]
### Bug description

When i try to name the timeline for premiere, I get this error:
**Error! variable `test` not found. Did you mean a string literal.**

### What's your platform?

```shell
PS O:\oz\recordings\2024\trajectory\06-June> auto-editor.exe --debug
Python Version: 3.10.11 64-bit
Platform: Windows 10 amd64
FFmpeg Version: N-110322-g0c25da5a28-g1440bf15e2+1
FFmpeg Path: C:\Users\oleg\AppData\Roaming\Python\Python310\site-packages\ae_ffmpeg\Windows\ffmpeg.exe
Auto-Editor Version: 24w19a
```

### What command did you use

```shell
PS O:\oz\recordings\2024\trajectory\06-June> auto-editor 2024-06-09.18-36-55.mp4 --export 'premiere:name="2024-06-09.18-36-55.mp4"' --margin 0.1s,0.15sec

Error! variable `2024-06-09.18-36-55.mp4` not found. Did you mean a string literal.


PS O:\oz\recordings\2024\trajectory\06-June> auto-editor 2024-06-09.18-36-55.mp4  --margin 0.1s,0.15sec --export 'premiere:name="2024-06-09.18-36-55.mp4"'

Error! variable `2024-06-09.18-36-55.mp4` not found. Did you mean a string literal.
PS O:\oz\recordings\2024\trajectory\06-June> auto-editor 2024-06-09.18-36-55.mp4 --export 'premiere:name="2024-06-09.18-36-55.mp4"'


Error! variable `2024-06-09.18-36-55.mp4` not found. Did you mean a string literal.
PS O:\oz\recordings\2024\trajectory\06-June> auto-editor 2024-06-09.18-36-55.mp4 --export 'premiere:name="test"'

Error! variable `test` not found. Did you mean a string literal.
```

**Comment by WyattBlue** [comment]
Use powershell.

**Comment by ostvk** [comment]
<img width="1280" alt="Screenshot 2024-06-17 091429" src="https://github.com/WyattBlue/auto-editor/assets/168329474/93d75ca7-1d5a-4117-8d07-0b8c3a9cb64d">

I'm afraid it is PowerShell

**Comment by WyattBlue** [comment]
```
auto-editor example.mp4 --edit 'premiere:name=""Your name here""'
```
should work

**Comment by ostvk** [comment]
<img width="1280" alt="image" src="https://github.com/WyattBlue/auto-editor/assets/168329474/b325f181-382c-4fe8-a8c6-963c6057441e">

still the same for now

**Comment by WyattBlue** [comment]
That's because you have `-` in the name, in which case use can use
```
--export 'premiere:name=\"your-name-here\"'
```
However, if the name has spaces, you need `""your name here""`

If you have both spaces and hyphens, neither method works. You'll have to look up how with micro$oft's terrible parsing rules for Powershell. Also note that this is only for Powershell on Windows 10, newer Powershell has different syntax so you'll also have to look that up if you upgrade to Windows 11.

This is why I daily drive MacOS.

**Comment by ostvk** [comment]
Thanks for pointing out, it works.
