### ISSUE TITLE
Video & Audio unlinked when importing to Resolve

### ISSUE THREAD

**Issue by MonzterDev** [WyattBlue/auto-editor#475]
### Bug description

The video and audio tracks are not linked together. I'm skipping the other questions because they're less relevant to this issue, which stems from this issue: https://github.com/WyattBlue/auto-editor/issues/472.

### What's your platform?

```shell
-
```

### What command did you use

```shell
-
```

**Comment by WyattBlue** [comment]
Fixed a while ago?

**Comment by SchonKonnie** [comment]
I think he meant that not all audio tracks are linked if you have multiple streams.
Thats at least the case for me (version 25.0.1)

**Comment by WyattBlue** [comment]
> I think he meant that not all audio tracks are linked if you have multiple streams. Thats at least the case for me (version 25.0.1)

That is true
