### ISSUE TITLE
Unable to find the source file in the directory it exists

### ISSUE THREAD

**Issue by asifali22** [WyattBlue/auto-editor#476]
### Bug description

I was able to create the xml for davinci resolve using below:
```
auto-editor GX011998.MP4  --export 'resolve:name="asif ali"'
```
However when I import the file following the steps:

1. Timelines
2. <img width="926" alt="Screenshot 2024-06-18 at 12 04 13 PM" src="https://github.com/WyattBlue/auto-editor/assets/19748337/5990caee-6faf-4212-b9dc-8ce6246ff1b6">
3. <img width="746" alt="Screenshot 2024-06-18 at 12 05 40 PM" src="https://github.com/WyattBlue/auto-editor/assets/19748337/62e22a00-e809-45f3-a04a-4583af35898f">
4. However file exists in the same folder where `fcpxml` is present.
5. I have tried setting the folder manually as well - no success.

### What's your platform?

```shell
Python Version: 3.10.9
Platform: Darwin 23.4.0 x86_64
FFmpeg Version: N-110230-g1179bb703e-6.0
FFmpeg Path: /Users/asifali/anaconda3/lib/python3.10/site-packages/ae_ffmpeg/Darwin-x86_64/ffmpeg
Auto-Editor Version: 24w24a
```

### What command did you use

```shell
auto-editor GX011998.MP4  --export 'resolve:name="asif ali"'
```

### What properties does your input video have?

GX011998.MP4:
 - recommendedTimebase: 2997/50
 - video:
   - track 0:
     - codec: hevc
     - fps: 60000/1001
     - resolution: 3840x2160
     - aspect ratio: 16:9
     - pixel aspect ratio: 1
     - duration: 27.7277
     - pix fmt: yuvj420p
     - color range: 2 (pc)
     - color space: 1 (bt709)
     - color primaries: 1 (bt709)
     - color transfer: 1 (bt709)
     - timebase: 1/60000
     - bitrate: 59346294
     - lang: eng
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 27.712
     - bitrate: 189488
     - lang: eng
 - container:
   - duration: 27.7277
   - bitrate: 59625092

**Comment by WyattBlue** [comment]
What version of DaVinci Resolve are you using?

**Comment by asifali22** [comment]
> What version of DaVinci Resolve are you using?

Version 18.6.6 Build 7

**Comment by WyattBlue** [comment]
Try using the latest version of auto-editor, then export it without giving it a name.
