### ISSUE TITLE
Remove segments of duration less than a number of seconds

### ISSUE THREAD

**Issue by sharno** [WyattBlue/auto-editor#478]
Can you add a feature that removes segments that have a duration that's less than a number of seconds?

example command:
```sh
auto-editor video.mkv --edit audio:0.05 --drop-segment-dur 0.8sec
```
which would remove the segments that have the audio less than threshold of 5% and drop the segments that are less than 0.8 seconds in duration

If it's helpful the feature is here too: https://videosilenceremover.web.app/

**Comment by WyattBlue** [comment]
You can use:
```
auto-editor video.mkv --edit "(minclip audio:0.5 0.8sec)"
```

**Comment by sharno** [comment]
Thank you!

This is impressive, didn't think about using Palet at all for that!
Would be great if you can add some of these examples in the Readme

**Comment by sharno** [comment]
Does this work with exporting? seems that I get an empty Resolve timeline when I use minclip the way you mentioned

**Comment by WyattBlue** [comment]
The edits stay the same regardless of what export method you choose.

For DaVinci Resolve, you import with "File > Import > Timeline"

**Comment by sharno** [comment]
Yep, that's indeed how it works but trying out this exact command:

```sh
auto-editor.exe ".\2024-05-15 21-19-54.mkv" --edit "(minclip audio:0.5 0.8sec)" --export resolve
```
gave me a 1KB FCPXML file

while 
```sh
auto-editor.exe ".\2024-05-15 21-19-54.mkv" --edit audio:0.05 --export resolve
```
works (167KB FCPXML file)

**Comment by WyattBlue** [comment]
If you using Powershell, you need to use different escape sequences

```
auto-editor.exe ".\2024-05-15 21-19-54.mkv" --edit ""(minclip audio:0.5 0.8sec)"" --export resolve
```
Should work for Windows 10, I'm not sure if it works for Windows 11

**Comment by WyattBlue** [comment]
It looks like you accidentally typed 0.5 instead of 0.05.
