### ISSUE TITLE
Error setting option color_primaries to value 0

### ISSUE THREAD

**Issue by Hydr0o01** [WyattBlue/auto-editor#484]
### Bug description

Hi ! every time I want to use auto editor, I get the error "color_primaries to 0" and this is really very problematic for me because I use Auto Editor very often. This problem happens on all MP4 videos. I didn't find an option to modify the "color_primaries".

### What's your platform?

```shell
E:\Premiere pro\PROJETS\hbe>auto-editor --debug
OS: Windows 11 amd64
Python: 3.12.4
PyAV: 12.3.0
Auto-Editor: 24w30a
```

### What command did you use

```shell
E:\Premiere pro\PROJETS\hbe>auto-editor 1.mp4 --margin 0.0000001sec
Error! Error setting option color_primaries to value 0.
```

### What properties does your input video have?

1.mp4:
 - recommendedTimebase: 60/1
 - video:
   - track 0:
     - codec: h264
     - fps: 60
     - resolution: 1920x1080
     - aspect ratio: 16:9
     - pixel aspect ratio: 1
     - duration: 498.1666666666667
     - pix fmt: yuv420p
     - color range: 1 (tv)
     - color space: 1 (bt709)
     - color primaries: 0
     - color transfer: 0
     - timebase: 1/60000
     - bitrate: 11632595
     - lang: eng
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 48000
     - channels: 2
     - duration: 498.1666666666667
     - bitrate: 317372
     - lang: eng
 - container:
   - duration: 498.166667
   - bitrate: 11957649

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2024-07-17T19:01:27.000000Z
  Duration: 00:08:18.17, start: 0.000000, bitrate: 11957 kb/s
  Stream #0:0[0x1](eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709/reserved/reserved, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 11632 kb/s, 60 fps, 60 tbr, 60k tbn (default)
      Metadata:
        creation_time   : 2024-07-17T19:01:27.000000Z
        handler_name    : ?Mainconcept Video Media Handler
        vendor_id       : [0][0][0][0]
        encoder         : AVC Coding
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
      Metadata:
        creation_time   : 2024-07-17T19:01:27.000000Z
        handler_name    : #Mainconcept MP4 Sound Media Handler
        vendor_id       : [0][0][0][0]
At least one output file must be specified

**Comment by WyattBlue** [comment]
I released a new version that fixes this.
