### ISSUE TITLE
Option to disable the cache \ do not write to disk

### ISSUE THREAD

**Issue by idMysteries** [WyattBlue/auto-editor#487]
I would like the option to disable the cache so that nothing is written to the disk, at least if the export mode is timeline.

I use this program to skip silence in mpv. I get chunks through the timeline export.

Now the program creates 2 temporary folders in temp and one cache.npz file.

Of course, the cache size is small, but it seems like the program can work without it, at least I didn't see the importance of the cache in the code.

For one video I run auto-editor once and will not use the cache.

**Comment by WyattBlue** [comment]
Good idea. I've added the `--no-cache` option in master.
