### ISSUE TITLE
Subtitles are not included in the final video

### ISSUE THREAD

**Issue by Flopsey** [WyattBlue/auto-editor#493]
### Bug description

If the original video had a subtitle stream, it is not included in the edited video. I believe this should be the case, since there is the option `-sn` which should explicitly disable subtitle output. However, even with this flag there are no subtitles.

### What's your platform?

```shell
OS: Darwin 23.4.0 arm64
Python: 3.12.4
PyAV: 12.3.0
Auto-Editor: 24w30a
```

### What command did you use

```shell
auto-editor video.mp4 --no-open
```

### What properties does your input video have?

video.mp4:
 - recommendedTimebase: 25/1
 - video:
   - track 0:
     - codec: h264
     - fps: 25
     - resolution: 640x360
     - aspect ratio: 16:9
     - pixel aspect ratio: 1
     - duration: 5272.48
     - pix fmt: yuv420p
     - timebase: 1/12800
     - bitrate: 267032
     - lang: und
 - audio:
   - track 0:
     - codec: aac
     - samplerate: 48000
     - channels: 1
     - duration: 5272.405
     - bitrate: 64971
     - lang: und
 - subtitle:
   - track 0:
     - codec: mov_text
     - lang: eng
 - container:
   - duration: 5272.48
   - bitrate: 338162

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf61.1.100
  Duration: 01:27:52.48, start: 0.000000, bitrate: 338 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 640x360 [SAR 1:1 DAR 16:9], 267 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 64 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](eng): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s (default)
      Metadata:
        handler_name    : SubtitleHandler

**Comment by WyattBlue** [comment]
25.0.1 should fix this
