### ISSUE TITLE
export to davinci resolve

### ISSUE THREAD

**Issue by lijovklm** [WyattBlue/auto-editor#52]
hi,

Big thanks for making this.
Anyway to add a feature to export to davinci resolve similar to the export to premiere feature.

**Comment by WyattBlue** [comment]
Thanks, I'll download the free version to see if there's any way to give support.

**Comment by WyattBlue** [comment]
It's possible to import a xml file [generated by premiere pro](https://youtu.be/a4ictQOraGY?t=59). DaVinci Resolve does not accept the xml file generated by auto-editor but it seems it's possible to support if a few more attributes are specified, so I'll add `--export_to_resolve` eventually.

Right now I'm working on a major restructure of the code so don't hold your breath for this feature.

**Comment by lijovklm** [comment]
Sure. thanks for checking it out.

**Comment by WyattBlue** [comment]
Added in 20w32a.

**Comment by lijovklm** [comment]
@WyattBlue Thank you. I tried this option and exported to resolve. That worked well. But seems the frame margin is not included. Soft sounds at the beginning and end of every clip is missing while the output to file works as smooth.

**Comment by lijovklm** [comment]
Does video speed attribute work in this feature?

**Comment by WyattBlue** [comment]
@lijovklm Yes it does. You can set a different speed when exporting to resolve and DaVinci will speed up that clip.

**Comment by lijovklm** [comment]
for some reason this option is coming messed up for me. this time audio is coming first. while when I don't export, audio-editor makes the edited clip perfectly

**Comment by lijovklm** [comment]
Also, every single time this error comes up 
![image](https://user-images.githubusercontent.com/24433342/91259702-a0f3ee80-e78c-11ea-9b85-c1eb87ab30bc.png)
I have the xml and input file in the same directory
