### ISSUE TITLE
Export in another fcpxml version

### ISSUE THREAD

**Issue by evidhai** [WyattBlue/auto-editor#532]
### Discussed in https://github.com/WyattBlue/auto-editor/discussions/390

<div type='discussions-op-text'>

<sup>Originally posted by **patrickbolby** October 26, 2023</sup>
My Final Cut pro will not import the fcpxml file. It's using 1.10 xml version and my file is 1.11. How do i Export my Auto-editor file using 1.10 instead of 1.11?</div>

**Comment by WyattBlue** [comment]
You can change `<fcpxml version="1.11">` to `<fcpxml version="1.10">` in the .fcpxml file.

**Comment by WyattBlue** [comment]
I've added a new argument that can do this automatically. `--export final-cut-pro:version=10`
