### ISSUE TITLE
Ensure that cache refers to file by full pathname

### ISSUE THREAD

**Issue by michaelcadilhac** [WyattBlue/auto-editor#536]
Apologies if this has already been solved; I cannot find an issue with this, and git blame didn't point to a fix in the recent past.

I've had a few funky problems on 25.1.0 caused by the cache referring to files by their basenames rather than their full paths:

```
/tmp/ae-25.1.0$ 7z l cache.npz
[...]
   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
1980-01-01 00:00:00 .....        39140        39140  view_with_share.mp4:audio:25:stream=0.npy
------------------- ----- ------------ ------------  ------------------------
1980-01-01 00:00:00              39140        39140  1 files
```

I have many files with that name, and somehow, they got conflated, resulting in extraordinarily messy files (i.e., a file split according to the audio of another).

Is it possible that something needs to be fixed over there for instance?

https://github.com/WyattBlue/auto-editor/blob/6085aa1d7343e498a384e100585e588a2474f2dc/auto_editor/analyze.py#L216

**Comment by WyattBlue** [comment]
Thanks for reporting this.

There isn't a fix in master, but I actually like that changing the file location doesn't invalidate the cache. Using last modified time + path.basename seems a better aproach.

**Comment by michaelcadilhac** [comment]
Sounds good to me.  Another approach would be to use the MD5; it takes about a second to hash a 1GB file on modern computers (such as the ones likely to use `auto-editor`).

**Comment by WyattBlue** [comment]
Hashing the file is actually slower than just running audio analysis, so it's not worth it.
