### ISSUE TITLE
How to use Audio Options: --hardware_accel in Windows 10. It is not mentioned in the documentation. 

### ISSUE THREAD

**Issue by MikeChenX** [WyattBlue/auto-editor#56]
Hi，
How to use Audio Options: --hardware_accel in Windows 10. It is not mentioned in the documentation.

**Comment by WyattBlue** [comment]
Well `--hardware_accel` is not in Audio Options section and does nothing when processing audio files by themselves but is useful. Hardware_accel can make processing videos much faster though.

I'll put a guide in the docs eventually.

**Comment by WyattBlue** [comment]
nevermind. It's literally useless now. I might give it special attention if I figure out some use.
