### ISSUE TITLE
Describe "--audio-normalize" in documentation

### ISSUE THREAD

**Issue by Valentin-Metz** [WyattBlue/auto-editor#565]
I can't find an example or explanation in the documentation on how to use this feature.
It would be nice if this could be added.
Much appreciated!

**Comment by WyattBlue** [comment]
There are two modes
```
--audio-normalize peak
--audio-normalize ebu
```
they work by themselves but you can specify options too:
```
--audio-normalize peak:t=-3
```

You can see the docs for all the options by running:
```
auto-editor --audio-normalize --help
```
