### ISSUE TITLE
The DAR of the output video file is different from that of the source video file. How can the DAR of the output file and the source file be consistent？

### ISSUE THREAD

**Issue by MikeChenX** [WyattBlue/auto-editor#57]
Hi，
    The DAR of the output video file is different from that of the source video file. How can the DAR of the output file and the source file be consistent？

**Comment by WyattBlue** [comment]
By default auto-editor should output video files in the same resolution so there are no resolution controls. The fact that the output resolution is not the same as the input should be reported as a bug. Can you tell me you knew? Was it a small change or a big one, and what was the original video dimensions?

**Comment by MikeChenX** [comment]
Hi，My mistake, resolution is OK。
Source video file information:
- Metadata:
-     major_brand     : isom
-     minor_version   : 512
-     compatible_brands: isomiso2avc1mp41
-     encoder         : Lavf57.21.101
-   Duration: 03:16:28.45, start: 0.000000, bitrate: 622 kb/s
-     Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 471:820 DAR 628:615], 574 kb/s, 100 fps, 100 tbr, 12800 tbn, 200 tbc (default)
-     Metadata:
-       handler_name    : VideoHandler
-     Stream #0:1(und): Audio: mp3 (mp4a / 0x6134706D), 44100 Hz, stereo, s16p, 31 kb/s (default)
-     Metadata:
-       handler_name    : SoundHandler
-   10.96 A-V:  0.018 fd= 732 aq=    5KB vq=   17KB sq=    0B f=0/0

Output file information:
 

-  Metadata:
-     major_brand     : isom
-     minor_version   : 512
-     compatible_brands: isomiso2avc1mp41
-     encoder         : Lavf58.45.100
-   Duration: 01:41:01.89, start: 0.021333, bitrate: 14436 kb/s
-     Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 204958 kb/s, 100 fps, 100 tbr, 99998 tbn, 200 tbc (default)
-     Metadata:
-       handler_name    : VideoHandler
-     Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 130 kb/s (default)
-     Metadata:
-       handler_name    : SoundHandler
-    2.91 A-V: -0.000 fd= 137 aq=    9KB vq=15544KB sq=    0B f=0/0


**It may be caused by the inconsistency of SAR。The source video file is generated by ffmpeg, SAR is not common。how to fix it？**

**Comment by WyattBlue** [comment]
I think this problem is related to #58 in the fact that allowing the user to choice the video codec will solve it.

**Comment by WyattBlue** [comment]
Added the ability to choose video codec.
