### ISSUE TITLE
zoom threshold feature is missing 20w32a.

### ISSUE THREAD

**Issue by lijovklm** [WyattBlue/auto-editor#60]
I used to use this feature extensively. it does help to make a video interesting. I was thinking to request for a zoom level setting somewhere. Please bring it back if possible.

**Comment by WyattBlue** [comment]
If I find a convenient way to add zooms, I'll add that feature back in, but in a more expanded way.

**Comment by WyattBlue** [comment]
I never forgot about this. 

The move from primarily rendering with opencv to pyav made this feature harder to do and it will still have to be supported with premiere pro and resolve eventually. However, this is now the most priopized feature right now besides scale, so expect an update soon.


----

Also, before I forgot, here's how I plan to implement it. Zoom will use `--zoom` and it will take `(start point),(end point),(start zoom),(end zoom),(motion)` separated by commas.

Example:
```
auto-editor example.mp4 --zoom 0,10,100,120,linear
```

It may also take conditional values:
```
auto-edtior example.mp4 --zoom loudness>0.08,end_of_cut,100,150,quadratic
```

and could take multiple arguments (`nargs=*`)

```
auto-editor example.mp4 --zoom 0,20,100,120,linear 30,40,100,80,linear
```

**Comment by lijovklm** [comment]
@WyattBlue Thanks. I went through the zooming readme article. 
Does it have a capability to do zoom automatically when the loudness is detected, or a motion is present.
I am looking for things which we can do to make this process even less manual.

**Comment by WyattBlue** [comment]
@lijovklm You can use expressions like "audio>0.05" for example to automatically add zooms.

Full command:
```
auto-editor example.mp4 "audio>0.03,audio<0.03,1,1.2,centerX,centerY,sine"
```
