### ISSUE TITLE
The file won't created

### ISSUE THREAD

**Issue by benboss1** [WyattBlue/auto-editor#61]
**it say Error! The file example_ALTERED.mp4 was not created**

```
Tell us if you were able to run the example video
```
No
```
Paste the terminal output here
```
Error! The file example_ALTERED.mp4 was not created.
```
Run auto-editor.py --debug
```
output here:
Python Version: 3.8.5 64-bit
Platform: Windows
FFmpeg path: C:\Users\*****\AppData\Local\Programs\Python\Python38\Lib\site-packages\auto_editor-20.32.1.0-py3.8.egg\auto_editor\win-ffmpeg/bin/ffmpeg.exe
Auto-Editor version 20w32a

**Comment by WyattBlue** [comment]
Run `auto-editor example.mp4 --debug` and paste the results.
