### ISSUE TITLE
Video is not playable

### ISSUE THREAD

**Issue by syntacops** [WyattBlue/auto-editor#65]
The video is created but not playable (file damaged and has 0 kb). 

I tried it on the example video by using the command: auto-editor example.mp4

On debug:

```
[h264_amf @ 00000236e2754680] DLL amfrt64.dll failed to open
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
['c:\\program files\\python37\\lib\\site-packages\\auto_editor\\win-ffmpeg/bin/ffmpeg.exe', '-y', '-i', 'C:\\Users\\Jay\\AppData\\Local\\Temp\\tmpe8tpncex/newAudioFile.wav', '-i', 'C:\\Users\\Jay\\AppData\\Local\\Temp\\tmpe8tpncex/spedup.mp4', '-b:v', '241k', '-c:v', 'h264', '-movflags', '+faststart', 'example_ALTERED.mp4', '-hide_banner']
Finished. took 5.76 seconds (0:00:06)
Auto-Editor made 4 cuts, which would have taken about 8 seconds if edited manually.

```

**Comment by WyattBlue** [comment]
Add `--video_codec copy` this looks like a problem related to that code.

**Comment by syntacops** [comment]
> Add `--video_codec copy` this looks like a problem related to that code.
> 
> I want to see if that prevents you bug, or the problem is something related to the windows build of ffmpeg.

With this addition it works! Thank you very much!

**Comment by WyattBlue** [comment]
I pushed a new version to fix this issue (and fix some other pet peeves). Can you run 
```terminal
pip3 install auto-editor --upgrade
``` 
and share the results @syntacops?

**Comment by syntacops** [comment]
Done. Seems to work, although I get a warning:

```
Warning! The muxing/compression failed. This may be a problem with your ffmpeg, your codec, or your bitrate.
Trying, again but using the "copy" video codec.
Finished. took 6.39 seconds (0:00:06)
```

Video is playable though.
