### ISSUE TITLE
Output video size goes very higher

### ISSUE THREAD

**Issue by shojaeix** [WyattBlue/auto-editor#68]
I ran the `audo-editor ted2.mp4  --frame_margin 8` and the output video size is x6 bigger than input. 
Also the output video bitrate is 2000k, but the input bitrate is about 300k

The output of the example video (`auto-editor example.mp4 --frame_margin 8`) has 0 byte size! 

Terminal output: 
```
$ auto-editor example.mp4 --frame_margin 8
Finished.
took 11.28 seconds (0:00:11)

```

Debug: 
```
$ auto-editor --debug
Python Version: 3.8.2 64-bit
Platform: Windows
FFmpeg path: C:\Python38\Lib\site-packages\auto_editor\win-ffmpeg/bin/ffmpeg.exe
Auto-Editor version 20w33a
```

I tried to pass bitrate maually using `--video_bitrate 233k` arg, but it seems not to work! same result.

**Comment by WyattBlue** [comment]
Not a bug. Use `video_bitrate` to change the size.
