### ISSUE TITLE
Movement detection

### ISSUE THREAD

**Issue by syntacops** [WyattBlue/auto-editor#69]
I love this script, already used it for a video and it saved me so much time.

As I create programming tutorials it often occurs that I showcase something without explicitely saying anything, for example I'm typing some lines of code, scroll up and down or switch between different windows. 

So I thought it would be a great addition to have a feature that allows to differ between "silence + inactivity" and "silence + activity". Is there already any workaround?

That feature would make this tool even greater :)

**Comment by sasa** [comment]
I am doing something quite similar. I record a clip and then I have 3 options to process it. One is cutting out everything. The next one is speed through the silent sections with 10x and the third option is to show silent section as 1x. I have this configured as scripts and activate them through my Stream Deck. But I do have to think ahead about what I will record the next second or minutes and see what the clip is supposed to be like. I am still changing a lot with this setup. One day i need to do a Youtube video showing how I do this because this is quite a cool setup for creating tutorials. All thanks to auto-editor.

**Comment by syntacops** [comment]
> I am doing something quite similar. I record a clip and then I have 3 options to process it. One is cutting out everything. The next one is speed through the silent sections with 10x and the third option is to show silent section as 1x. I have this configured as scripts and activate them through my Stream Deck. But I do have to think ahead about what I will record the next second or minutes and see what the clip is supposed to be like. I am still changing a lot with this setup. One day i need to do a Youtube video showing how I do this because this is quite a cool setup for creating tutorials. All thanks to auto-editor.

I would be very interested in such a tutorial. I created a recording setup as well, which allows me to only save the flawless material. And with auto-editor I found the "missing piece" for my setup. The only problem is that I'm not a big fan of jump cuts when it comes to tutorials. At the moment I have to keep talking when I do things like "opening a new website", "typing some lines of code" to prevent some of the jump cuts. So that would be a great addition to the auto-editor.

**Comment by sasa** [comment]
auto-editor will not be able to do this unless there is some kind of signal generated that can be removed later. 

Just a silly idea, maybe.

Whenever the mouse cursor is moved or the keyboard is typed an audio signal is generated. Some kind of software would have to do that. Then this signal is recorded to a separated audio channel into OBS. I know that OBS can do this. This signal would not be audible, but it would be silently recorded.

 If we had these audio signals in the recording only then ae could try to detect them and decide what to cut out and what not.

But this is a problem with a two part solution. We would have to come up with the OBS part first. Then Wyatt could try and see if this is doable. I do not know if this would be in his interest. So I am only giving ideas and speculating here.

**Comment by syntacops** [comment]
Actually I found something that seems to be promisin. There is another python script called [DVR-Scan](https://dvr-scan.readthedocs.io/en/latest/). I will play around with it. If this doing its job maybe some of the features of this packages could be integrated into auto-editor.

**Comment by sasa** [comment]
That sounds promising. I hope it works out. Keep us updated.

**Comment by WyattBlue** [comment]
Thanks for the suggestion. I'll review all the options and see which is right for auto-editor.

**Comment by WyattBlue** [comment]
This feature was added in 20w48a. See [this post I wrote](https://github.com/WyattBlue/auto-editor/blob/master/resources/motionDetection.md)
