### ISSUE TITLE
Cut by all tracks always fails

### ISSUE THREAD

**Issue by BigB00st** [WyattBlue/auto-editor#71]
**Tell us what went wrong**

When using auto-editor on a file with multiple audio tracks, and using the flag  **--cut_by_all_tracks**, there is always an error:

[Terminal output](https://ghostbin.co/paste/yojyv)

From further inspection: I can confirm this issue is caused because the file `f'{TEMP}/combined.wav'` is never created. The file is never created because of an error while running ffmpeg.

[Using debug output](https://ghostbin.co/paste/hjs6c)

Tested in both windows and linux, same error occurs.

When manually running the same ffmpeg command that crashed with `combined.wav,` but using `combined.ogg` as output file, it creates the file succesfully.

**Possible steps to fix**

- solve the **wav** codec issue 

- add an argument that specifys the audio output file format

**Comment by naharia2006** [comment]
Same

**Comment by MegaNoam** [comment]
I see the problem still exists, there is still no answer from the developer of the project @WyattBlue

**Comment by WyattBlue** [comment]
I fixed this problem in the multi-track branch by changing the [ffmpeg](https://github.com/WyattBlue/auto-editor/commit/29f8ea994c756bc951afef2b4ecea3497974e94c) command, although I added `-f wav` just to be safe. I'll add these changes to master when I fix issue #70.

**Comment by BigB00st** [comment]
Thank you, the problem has been resolved, closing this issue.
