### ISSUE TITLE
When using --keep_tracks_seperate, a false error message is printed and the file is created in a temp directory

### ISSUE THREAD

**Issue by BigB00st** [WyattBlue/auto-editor#72]
**Tell us what went wrong**

When using the flag `--keep_tracks_seperate`, there is an error message that the file is not created, but the file is actually created in the %TEMP% directory.

Can confirm that the flag causes this, when running without the flag there is no such error message and the output file is created in the same directory.

[Error message](https://ghostbin.co/paste/d7zvw)

[Contents of the created temp directory](https://ghostbin.co/paste/jastj)

**Comment by WyattBlue** [comment]
I'm 90% sure that the new update fixed this bug but check again just in case.

**Comment by syntacops** [comment]
As you can see here [https://youtu.be/uDC4hZELHgo](https://youtu.be/uDC4hZELHgo) --keep_tracks_separate still does not work in the newest version.
