### ISSUE TITLE
NameError: name 'sort' is not defined

### ISSUE THREAD

**Issue by syntacops** [WyattBlue/auto-editor#73]
When I use choose a folder path instead of a single file I get the following error message:

```
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\auto-editor.exe\__main__.py", line 7, in <module>
    import sys
  File "c:\program files\python37\lib\site-packages\auto_editor\__main__.py", line 195, in main
    inputList += sort(os.listdir(myInput))
NameError: name 'sort' is not defined
```

Commands i tried:
```
auto-editor . (after I cd's to the directory)
auto-editor D:\User\Videos\OBS\archive\likes\test\
```

Only when I specify the name of a single file it works.

`auto-editor filename.mp4`

**Comment by WyattBlue** [comment]
I just fixed this error in 20w26a. Using a folder as the input should work perfectly now.

**Comment by syntacops** [comment]
Thanks for your efforts.

Unfortunately I get another error message now. Just tested it again with a folder that contains two mp4 files:

![image](https://user-images.githubusercontent.com/68994521/92322009-f8b51400-f02e-11ea-83f7-17bb22da7020.png)

**FileExistsError**

![image](https://user-images.githubusercontent.com/68994521/92322041-213d0e00-f02f-11ea-963f-d9a6329e2b4e.png)

It only processes the first video and then throws the error message:

![image](https://user-images.githubusercontent.com/68994521/92322058-4df12580-f02f-11ea-9a5e-2d20e0252cfc.png)
This also happens when I add "**--video_codec copy**"
