### ISSUE TITLE
Large output video, with same codec

### ISSUE THREAD

**Issue by shojaeix** [WyattBlue/auto-editor#75]
Hello 
This script is very fast and seems powerfull . but i couldn't use it because of this below issue :(

So i tried to edit an video with h264 codec. The input video has about 63M size, but the output has 113M.
I'll put details here, please tell me if i am missing something. 

Version: Auto-Editor version 20w36a
The input video link:  https://www.youtube.com/watch?v=iMqIhhsuGtU with quality 360p.
The used command:  `auto-editor --video_codec h264 Webinarexample.mp4 `
Terminal output: 
```
Finished. took 170.52 seconds (0:02:51)
Warning! Could not open output file.
```

I was able to run the `example.mp4` video and the result was OK, but i guess it's not a good example because it has no motion in it.

The ``auto-editor --debug`` output:

```
Python Version: 3.8.2 64-bit
Platform: Linux
FFmpeg path: ffmpeg
Auto-Editor version 20w36a
```

Thanks for your help

**Comment by WyattBlue** [comment]
I changed the method how auto-editor compresses video so it should be a lot better.

**Comment by shojaeix** [comment]
Tested it again, same result. 
Should i change the command? `auto-editor --video_codec h264 Webinarexample.mp4`

**Comment by WyattBlue** [comment]
You can set `--preset veryslow` And use `--videobitrate` to target the size of the video that you want.
