### ISSUE TITLE
Is it possible to use Nvidia GPU acceleration?

### ISSUE THREAD

**Issue by zenimarc** [WyattBlue/auto-editor#77]
I really like the software, but I think it's not so fast,, and I see it doesn't use my Nvidia video card.
Maybe it's possible to implement GPU acceleration.
Thank you

**Comment by WyattBlue** [comment]
There's very little reason to implement this feature considering how hard it is to implement. Just export the cuts to Premiere or DaVinci and let those programs do the GPU acceleration.
