### ISSUE TITLE
No such file or directory after downloading successful from youtube.

### ISSUE THREAD

**Issue by nicklaposky1** [WyattBlue/auto-editor#80]
C:\WINDOWS\system32>auto-editor "https://www.youtube.com/watch?v=bgA0q0TwLIQ"
Warning! You have the 32-bit version of Python, which means you won't be able to handle long videos.
URL detected, using youtube-dl to download from webpage.
[youtube] bgA0q0TwLIQ: Downloading webpage
[youtube] bgA0q0TwLIQ: Downloading MPD manifest
[download] https-www-youtube-com-watch-v-bgA0q0TwLIQ.f135 has already been downloaded
[download] 100% of 3.50MiB
[download] https-www-youtube-com-watch-v-bgA0q0TwLIQ.f140 has already been downloaded
[download] 100% of 561.87KiB
[ffmpeg] Merging formats into "https-www-youtube-com-watch-v-bgA0q0TwLIQ.mp4"
ERROR: file:https-www-youtube-com-watch-v-bgA0q0TwLIQ.f135: No such file or directory
Warning! Couldn't automatically detect audio bitrate.
Warning! frame rate detection failed.
If your video has a variable frame rate, ignore this message.
Warning! ffprobe had an invalid output.
Warning! Couldn't automatically detect the video codec.
Error! Audio track not found!

C:\WINDOWS\system32>

**Comment by WyattBlue** [comment]
Run your command again but add the `--debug` flag.
