### ISSUE TITLE
This CV2 only uses single thread, which is not that faster than JumpCutter's ffmpeg extract method. 

### ISSUE THREAD

**Issue by HaujetZhao** [WyattBlue/auto-editor#81]
I wonder if the auto-editor uses multi-core when processing the video part?

**Comment by WyattBlue** [comment]
> I wonder if the auto-editor uses multi-core when processing the video part?

It doesn't.

**Comment by HaujetZhao** [comment]
@WyattBlue Is there a possible a way to let ffmpeg just read all the chunk[0] ~ chunk[1] frames directly and then concatenate?

**Comment by WyattBlue** [comment]
I don't know, and I think cv2 does a better job anyway.
