### ISSUE TITLE
[Question] - How does copy video_codec work?

### ISSUE THREAD

**Issue by Saya47** [WyattBlue/auto-editor#83]
From my experience working with FFMpeg, I know that when cutting the video while using the `copy video codec` causes imprecise cuts and sometimes out of sync audio. I'm talking about the `-ss` and `-t` options used in FFMPeg.

Does the same thing happen when using Auto-Editor with copy video_codec?

Thanks in advance and thanks for this awesome program!

**Comment by WyattBlue** [comment]
Auto-Editor uses cv2 to edit the video so the cuts will always be precise regardless of video codec.

<20w41a. The "copy" codec copies the codec of the uncompressed video cv2 spits out.
>=20w41a. The "copy" codec copies the the original codec. The "uncompressed" codec is now used like "copy" in older versions.
