### ISSUE TITLE
Ability to specify ffmpeg path

### ISSUE THREAD

**Issue by ProcessingGit** [WyattBlue/auto-editor#91]
Add the ability to specify ffmpeg path to --my_ffmpeg argument.

**Comment by WyattBlue** [comment]
Thanks for the suggestion.

After careful thought, I decided not to implement this feature because it would:
 1. Mangle the design. 
    * The flag type and general option type would need to be combined to make this feature happen.
 2. Easy to workaround. 
    * Users can alias ffmpeg to whatever path they want and use `--my_ffmpeg` just as normal without modifying the software.

If you have any other suggestions or ideas, please make a new feature request.
