### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9b in position 421: invalid start byte

### ISSUE THREAD

**Issue by gentilmente** [WyattBlue/auto-editor#93]
With OS X videos taken from Photobooth or screen capture all works as expected but
with videos .mov from Nikon D5100 I get this error

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9b in position 421: invalid start byte
```

```Python Version: 3.8.2 64-bit                                                                                      
Platform: Darwin 19.6.0
FFmpeg path: /Library/Python/3.8/site-packages/auto_editor/mac-ffmpeg/bin/ffmpeg
FFmpeg version: 4.3
Auto-Editor version 20w43b
Traceback (most recent call last):
  File "/usr/local/bin/auto-editor", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/3.8/site-packages/auto_editor/__main__.py", line 397, in main
    output = pipeToConsole([ffmpeg, '-i', INPUT_FILE, '-hide_banner'])
  File "/Library/Python/3.8/site-packages/auto_editor/__main__.py", line 40, in pipeToConsole
    return stdout.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9b in position 421: invalid start byte
```

Maybe here are some clues
[https://stackoverflow.com/questions/42339876/error-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xff-in-position-0-in](url)

**Comment by WyattBlue** [comment]
Looking around the web, I think the cause is that INPUT_FILE contains characters that are not ASCII. I would like to know what INPUT_FILE is before trying to attempt to fix it since I can't yet replicate the error.

**Comment by gentilmente** [comment]
This is weird, I record a short video for testing purposes to share with you, it worked ok. So it isn´t the camera format.
I realize that all the ones that doesn't work were imported with iMovie, not directly from the SD card.
So, it's not a auto-editor problem, sorry for open this issue bro.
[https://drive.google.com/drive/folders/1xtn6rc08ZpfMyMrQfOn90YvJSHU_hMJc?usp=sharing](url)
there are the two versions of the video if you want to test by yourself.
