### ISSUE TITLE
Allow custom ffmpeg options for output

### ISSUE THREAD

**Issue by nilekurt** [WyattBlue/auto-editor#99]
Hello and thank you for making this tool. Please add a parameter to specify custom ffmpeg options for the output file.

While it is convenient to have simple options like "output video codec" and "output bitrate" exposed, it would be far more flexible to allow the user (e.g. me) to manually specify output encoding flags. One may want to filter the video/audio and employ different encoding modes (e.g. the now-standard CRF for libx26*) when writing the output file. At the moment one can work around the limitations by specifying a lossless output format or just very high bitrates, but I would much rather do it all in one go.

If you agree that it should be a parameter, but don't have the time to implemt it, I could take a look at making a pull request.

**Comment by WyattBlue** [comment]
Putting aside the security concerns, the main reason I would not put this feature in this program is the following:

**Auto-Editor Is Not FFmpeg**

Auto-Editor is not meant to be a wrapper or a replacement for ffmpeg. Auto-Editor's purpose is not to deeply interact with video like what ffmpeg can do. In theory, ffmpeg should be able to be replaced with something else (in the long term future) without breaking backwards compatibility with old/existing commands and workflows. 

There's also the practical concern that inputing in ffmpeg commands may not be the most awesome thing ever. eg.

```auto-editor example.mp4 --ffmpeg_commands '-crf', '18', '-pix_fmt', 'yuv420p', ...```

It would be more convenient to simply type that in as a regular ffmpeg command without having to worry about extra quotes or commas. There's also the fact that most people who know ffmpeg well generally have ffmpeg already installed and can use it at any time.

```ffmpeg -i example_ALTERED.mp4 -crf 18 -pix_fmt yuv420p ...```


I do sympathize with letting the user use different encoding methods and stuff similar so if you have any specific suggestions on what most needs adding.

**Comment by MihaiVoinea** [comment]
Hello @WyattBlue,

I can't speak for others, but a feature I myself need is the ability to
choose crf.

**Comment by WyattBlue** [comment]
> Hello @WyattBlue, I can't speak for others, but a feature I myself need is the ability to choose crf.

That's fair. Maybe this new option can be grouped together with --preset, --tune, and --video_codec under the 
banner of `exportOps`, so it would look like:

`auto-editor example.mp4 exportOps --crf 18 --preset slow`

`auto-editor exportOps --help`

```
exportOps
  |
    --crf,
    --preset,
    --tune
    --video_codec, set the video codec for the output media file
```

I think this would help declutter the general help screen and make it more obvious which options will be used when exporting to a video editor program like premiere vs exporting as a media file.

**Comment by 0xpr03** [comment]
My use case would be `-hwaccel` per [docs](https://trac.ffmpeg.org/wiki/HWAccelIntro) since I'm not using this to edit stuff but just run it on presentations to watch as jump cut..
